### ISSUE TITLE
Peterborough council?

### ISSUE THREAD

**Issue by gr4z** [robbrad/UKBinCollectionData#1]
Hi, any chance of the Peterborough Council code? Web page is here
https://www.peterborough.gov.uk/residents/rubbish-and-recycling/bins
You have to put in a postcode (try PE46PE), any number house. I would try myself but wouldn't know where to start!
Many thanks

**Comment by robbrad** [comment]
Hi @gr4z 

There isnt a need for Beautiful soup here - Peterborough have an API that gives a ready made JSON - the Python scripts just give you this in the absense of an API.

_Change the postcode as required:_
https://www.peterborough.gov.uk/api/addresses/**PE46PE**

_Find your uprn for your address_
e.g. 100090181402 = 12 CANTERBURY ROAD

Then put it at the end of this url (note the date covers you to the end of the year):

https://www.peterborough.gov.uk/api/jobs/2020-1-01/2020-12-31/**100090181402**

This could then feed HA directly - just a tip to keep your scan interval low or you will hammer your council for data and they may block you

Let me know how you get on

Thanks
Rob
