### ISSUE TITLE
Mid Suffolk Garden Waste - cannot specify day of collection

### ISSUE THREAD

**Issue by SingingDwarf** [robbrad/UKBinCollectionData#1026]
### Name of Council

Mid Suffolk District Council

### Issue Information

Cannot specify the day of the week for collection of the garden waste (brown) bin collection, implemented in #995

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by m26dvd** [comment]
I've updated this in the next release.

It will require the garden collection day to be passed in the UPRN field

**Comment by SingingDwarf** [comment]
Awesome, this works very well.
Thank you @dp247
