### ISSUE TITLE
The latest build failed and I deleted all the entities and rolled back to version 0.116

### ISSUE THREAD

**Issue by RJN368** [robbrad/UKBinCollectionData#1030]
### Home Assistant Version

2024.11.2

### Installation Method

Using HACS

### Issue Information

It looks like the code is not recreating the entities if they don't exist (at a guess)

Logger: custom_components.uk_bin_collection
Source: custom_components/uk_bin_collection/__init__.py:250
integration: UK Bin Collection Data (documentation, issues)
First occurred: 18:36:29 (19 occurrences)
Last logged: 18:58:40

[UKBinCollection] Unexpected error: 'NoneType' object has no attribute 'next_element'
Traceback (most recent call last):
  File "/config/custom_components/uk_bin_collection/__init__.py", line 250, in _async_update_data
    data = await asyncio.wait_for(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 101, in run
    return self.client_code(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 121, in client_code
    return get_bin_data_class.template_method(address_url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 61, in template_method
    bin_data_dict = self.get_and_parse_data(this_url, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 82, in get_and_parse_data
    bin_data_dict = self.parse_data(page, url=address_url, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/councils/WarwickDistrictCouncil.py", line 26, in parse_data
    collectionDateElement = element.next_sibling.next_element.next_element
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'next_element'

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] If trying to add a specific council, I've checked it is listed as working at https://robbrad.github.io/UKBinCollectionData/3.12/
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by dp247** [comment]
Looks like the council website has changed

**Comment by m26dvd** [comment]
I'm on v0.118 and adding a test service with Warwick District Council seems to work fine. Can you retry please @RJN368 

Also, looking at the release notes, there has been no changes to this local authority in the since 0.116 so rolling back to a previous version wouldn't change anything

**Comment by RJN368** [comment]
I was on 119 and the entities stopped working, I've had this before where the entities got recreated, so I deleted them all expecting them to recreate.  Unfortunately they didn't and so I decided to roll back to see if that was the cause.  I've now rolled back to latest 119 and it's still throwing the same error.

**Comment by madnat** [comment]
I Amin the same council (Warwick) and have the same issue.  The URL config returns a valid page, so guess the page has changed and parsing needs updating.
