### ISSUE TITLE
Broxtowe Borough Council Calendar Issue

### ISSUE THREAD

**Issue by bobbinz** [robbrad/UKBinCollectionData#1042]
### Name of Council

Broxtowe Borough Council

### Issue Information

Very similar to https://github.com/robbrad/UKBinCollectionData/pull/662 really only this time its about calendar items.

At the moment BBC have failed to tell anybody when the next brown bin is collected so the 2nd column is empty causing an error.

UPRN is 100031314280.

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by m26dvd** [comment]
@bobbinz I have just checked using the example UPRN you have given and it is returning the brown bin okay. I did find another URPN that was not showing the brown bin however it didn't cause any error.

Can you provide more detail on the errors you are seeing and any error logs please?

**Comment by bobbinz** [comment]
Ahh, interesting!

The council seem to have fixed their end.  I guess we'll have to wait until it breaks again :)
