### ISSUE TITLE
West Lancashire Borough Council 

### ISSUE THREAD

**Issue by ID-Ant** [robbrad/UKBinCollectionData#1043]
Hi all,

relatively new to HA - so bear with me please. Really like the idea of seeing the Bin and have installed (correctly i think) the UK Bin Collection Data. How ever when i set the config it not showing any data - any suggestions?

<img width="758" alt="Screenshot 2024-11-23 at 15 17 57" src="https://github.com/user-attachments/assets/3ef09ae6-b25b-4c94-bb3b-03b469e2ca1d">

<img width="937" alt="Screenshot 2024-11-23 at 15 03 28" src="https://github.com/user-attachments/assets/557fe171-ada3-4b96-8558-5f73ac88fd9d">

Clearly doing something incorrectly, but failing to understand what it is. Also not show how to add this into the Dashboard as nothing is coming up either. 

Greatly appreciate any guidance on this.

Thanks all.

**Comment by m26dvd** [comment]
@ID-Ant I've just double checked an example address and it is returning results correctly.

If you can make sure you are populating your postcode and UPRN correctly (you can find your UPRN by visiting https://www.findmyaddress.co.uk) and let us know how you get on!

**Comment by ID-Ant** [comment]
> postcode

So, turns out the post code has to be in the form XXX XXX i had it as XXXXXX - might be worth as a future enchantment to have validation on that field :) - all is working now :)
