### ISSUE TITLE
BMBC not pulling all bins

### ISSUE THREAD

**Issue by soulehmoo** [robbrad/UKBinCollectionData#1044]
### Name of Council

Barnsley Metropolitan Borough Council

### Issue Information

Hi All,
Recently the script has only pulled through 2 bins, namely Grey and Brown:

![image](https://github.com/user-attachments/assets/7106ae48-5773-4782-9ed8-201d7d6c0f18)

I ran the script separately and it appears to corroborate that:

`PS C:\temp\uk_bin_collection> python collect_data.py BarnsleyMBCouncil https://waste.barnsley.gov.uk/ViewCollection/Collections -s -u ********** -p "*** ***"
{
    "bins": [
        {
            "type": "Grey bin",
            "collectionDate": "26/11/2024"
        },
        {
            "type": "Brown bin",
            "collectionDate": "03/12/2024"
        }
    ]
}`

There should be 4 bins, Blue, Brown, Grey, and Green.
I don't believe the website has changed.

Best Regards,
Shaun.

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by m26dvd** [comment]
@soulehmoo I've just had a look at the code and my example address returns all four bin colours but only because all four appear on the local authority website with dates associated with them.

Could you manually check the local authority website to see if the missing bin colours appear there - and if they do, can you provide an example postcode/UPRN for me to test with please?

**Comment by soulehmoo** [comment]
@m26dvd Thank you for the reply, I have tried with a different UPRN and postcode and got the same behaviour.
An example is 2007018325 and S751DF.

**Comment by m26dvd** [comment]
@soulehmoo The integration can only return the data that is available from the local authority website.

If there are only 2 bins showing for that address, it will only return the 2 bins.

I'm not sure this is a bug in the integration but can only suggest handling the sensors dynamically within HA if you have automations running that are looking for all 4 bins

**Comment by soulehmoo** [comment]
@m26dvd Thank you very much for looking, I will mark this as closed, it makes sense now :)
