### ISSUE TITLE
East Ayrshire Not Pulling All Bins

### ISSUE THREAD

**Issue by dodger421** [robbrad/UKBinCollectionData#1045]
### Name of Council

East Ayrshire Council

### Issue Information

The integration only returns 4x devices (2 bins), there should be 6x devices (3 bins). Every 3 weeks the Recycling trolley and General waste bin are collected but the integration only returns the Recycling trolley and Garden waste bin (collected on a different day).

I think this because the python script only returns the first ScheduleItem class from each <time> block. I've tried the usual of reloading, reconfiguring and reinstalling the integration and I've waited until a 2 bin day was the next collection. None of these have returned General waste bin collection.

Raw JSON returned: {"Recycling trolley": "25/11/2024", "Garden waste bin": "06/12/2024"}

Snippet from website showing collection schedule

```html
<div id="CollectionDates" class="BinCalendar">
	<time datetime="2024-11-25">
		<span class="ScheduleHeader">
			<span class="ScheduleDay">Monday</span>
			<span class="ScheduleDate">25 November 2024</span>
		</span>
		<span class="ScheduleItem Recycling">Recycling trolley</span>
		<span class="ScheduleItem General">General waste bin</span>
	</time>
	<time datetime="2024-12-02">
		<span class="ScheduleHeader">
			<span class="ScheduleDay">Monday</span>
			<span class="ScheduleDate">2 December 2024</span>
		</span>
		<span class="ScheduleItem Recycling">Recycling trolley</span>
	</time>
	<time datetime="2024-12-06">
		<span class="ScheduleHeader">
 			<span class="ScheduleDay">Friday</span>
			<span class="ScheduleDate">6 December 2024</span>
		</span>
		<span class="ScheduleItem Garden">Garden waste bin</span>
	</time>
``` 

Python script 
```python
for entry in soup.find_all("time"):
	dict_data = {
		"type": entry.find(class_="ScheduleItem").text.strip(),
		"collectionDate": datetime.strptime(
			entry["datetime"],
			"%Y-%m-%d",
		).strftime("%d/%m/%Y"),
	}
        bindata["bins"].append(dict_data)

        bindata["bins"].sort(
		key=lambda x: datetime.strptime(x.get("collectionDate"), "%d/%m/%Y")
)
``` 

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by dodger421** [comment]
That would have been useful, sorry for the oversight.

KA18 2RX/UPRN 127067889 is a good example.

**Comment by m26dvd** [comment]
@dodger421 Thanks! Easy fix, it will be included in my next release! Thanks for spotting!
