### ISSUE TITLE
Failed setup, will retry: Unexpected error

### ISSUE THREAD

**Issue by blaired** [robbrad/UKBinCollectionData#1049]
### Home Assistant Version

2024.11.3

### Installation Method

Using HACS

### Name of Council (if relevant)

Babergh District Council

### Issue Information

The integration was failing to load I think after a recent update to HA. I delete the integration and re added. I think from memory for my council a UPRN wasn’t needed but when I setup this is mandatory. After putting this in I get the below error. 

Failed setup, will retry: Unexpected error: '[*************]is not in list

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] If trying to add a specific council, I've checked it is listed as working at https://robbrad.github.io/UKBinCollectionData/3.12/
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by m26dvd** [comment]
@blaired Babergh was updated to allow you to specify the DAY for garden collection which we use the UPRN field. 
Wiki updated here - https://github.com/robbrad/UKBinCollectionData/wiki/Councils#babergh-district-council

**Comment by blaired** [comment]
Perfect, thank you.  All fixed :-)
