### ISSUE TITLE
Manchester City Council

### ISSUE THREAD

**Issue by PhotosBySimonH** [robbrad/UKBinCollectionData#105]
### Name of Council

Manchester City Council

### Example Postcode

M22 1RU

### Additional Information

https://www.manchester.gov.uk/bincollections

**Comment by dp247** [comment]
@PhotosBySimonH done and done! 

@robbrad will check and push to master when he gets the chance, I'm sure 😁.

Documentation has been [added here](https://github.com/robbrad/UKBinCollectionData/wiki/Councils#manchester-city-council).
