### ISSUE TITLE
Waverley Borough Council

### ISSUE THREAD

**Issue by Lloytron** [robbrad/UKBinCollectionData#108]
### Name of Council

Waverley Borough Council

### Example Postcode

GU9 9QG

### Additional Information

Here is an example URL for a local property; https://wav-wrp.whitespacews.com/mop.php?Track=2022/09/22/TDJKLHU0PD&serviceID=A&seq=3&pIndex=1#!

**Comment by dp247** [comment]
The code of this is done, just got to finish some project-specific stuff 😄
