### ISSUE TITLE
London Borough of Merton format and uri changed

### ISSUE THREAD

**Issue by drae** [robbrad/UKBinCollectionData#1086]
### Name of Council

London Borough of Merton

### Issue Information

Merton seem to have completely changed their format (and source uri).

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by dp247** [comment]
Could be the fix for #1072

**Comment by dp247** [comment]
In fact, will merge with #1072
