### ISSUE TITLE
Tonbridge and Malling Borough council datas shifted from 1 to 3 years

### ISSUE THREAD

**Issue by mimikm** [robbrad/UKBinCollectionData#1102]
### Name of Council

Tonbridge and Malling Borough council

### Issue Information

Hi,

Dates for Tonbridge and Malling Borough council are not working properly, see screenshot attached. 

![tmbc](https://github.com/user-attachments/assets/d1f2c625-33e8-4895-9a0a-19af0eab2281)

Regards
mimikm

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by dp247** [comment]
Would you mind emailing me your UPRN and postcode so I can take a look, please? Our testing one still works okay, but happy to see why yours doesn't. My contact info is on my Github profile.

**Comment by mimikm** [comment]
> Would you mind emailing me your UPRN and postcode so I can take a look, please? Our testing one still works okay, but happy to see why yours doesn't. My contact info is on my Github profile.

Thanks, just looked and it its showing ok now, must have been something on council side and I have panicked:)

**Comment by dp247** [comment]
Cool, good to hear 😊
