### ISSUE TITLE
bin collection Bolton

### ISSUE THREAD

**Issue by joseph15562** [robbrad/UKBinCollectionData#116]
### Name of Council

Bolton

### Example Postcode

BL1 6NH

### Additional Information

https://maps.bolton.gov.uk/residents/getdata.aspx?requesttype=LocalInfo&ms=Bolton/MyHouse&group=My%20house%20data%7Cbin_collections_combined&format=jsonp&uid=100010944541

**Comment by dp247** [comment]
Looks like JSON with padding that returns a dictionary of UPRN with HTML for bins - I'll have a crack at it 😄
