### ISSUE TITLE
Bexley Council Request

### ISSUE THREAD

**Issue by vaderag** [robbrad/UKBinCollectionData#123]
### Name of Council

Bexley

### Example Postcode

DA6 8DB

### Additional Information

Bexley have an excessively complex system/schedule to find your bin day

https://www.bexley.gov.uk/services/rubbish-and-recycling/find-your-collection-day-and-report-missed-bin/when-my-rubbish-and-recycling-collected

https://mybexley.bexley.gov.uk/service/When_is_my_collection_day

This then gives you a listing based on a schedule. The schedule needs to be looked up elsewhere

**Comment by dp247** [comment]
Ah yes, a worthy adversary
