### ISSUE TITLE
Cardiff Council 

### ISSUE THREAD

**Issue by DJ-Q** [robbrad/UKBinCollectionData#13]
https://www.cardiff.gov.uk/ENG/resident/Rubbish-and-recycling/When-are-my-bins-collected/Pages/default.aspx

Example postcode - CF5 3SX

**Comment by jone9618** [comment]
Hi. I’m also interested in getting data for Cardiff’s bins. 

The webpage to access this is at

https://www.cardiff.gov.uk/ENG/resident/Rubbish-and-recycling/When-are-my-bins-collected/Pages/default.aspx

It requires both a house number and a postcode. Test address 11 CF23 6QY

Any help gratefully received. Thanks

**Comment by dp247** [comment]
Reminder for later:
> https://api.cardiff.gov.uk/WasteManagement/index.html?urls.primaryName=Waste%20Management%20API%20V1.0

**Comment by dp247** [comment]
Request body:

> {
  "language": "json",
  "uprn": XXXXXXXXXX,
  "fromDate": "2022-07-22",
  "weeksToReturn": 4
}

**Comment by jone9618** [comment]
Much appreciated. Thank you
