### ISSUE TITLE
High Peak Borough Council - Request

### ISSUE THREAD

**Issue by rick165** [robbrad/UKBinCollectionData#130]
### Name of Council

High Peak Borough Council

### Example Postcode

SK23 6BQ

### Additional Information

URL : https://www.highpeak.gov.uk/findyourbinday

**Comment by OliverCullimore** [comment]
@robbrad should this one be closed now?

**Comment by dp247** [comment]
Yes, probably, maybe?

**Comment by rick165** [comment]
Thanks for this, works a treat
