### ISSUE TITLE
ModuleNotFoundError on Windows

### ISSUE THREAD

**Issue by dp247** [robbrad/UKBinCollectionData#133]
Seems to be getting a ModuleNotFoundError on Windows even after `poetry install` succeeds in installing the project.

```commandline
Traceback (most recent call last):
  File "G:\Projects\Python\UKBinCollectionData\uk_bin_collection\uk_bin_collection\collect_data.py", line 6, in <module>
    from uk_bin_collection.uk_bin_collection.get_bin_data import AbstractGetBinDataClass
ModuleNotFoundError: No module named 'uk_bin_collection'
```

@robbrad have I just become accustomed to running in PyCharm and missed a step? 😅

**Comment by robbrad** [comment]
@dp247 Dont think it's specifically a Windows thing - basically Pythonis unable to find the module in its path

Steps to get this to work from scratch

1. Fresh repo clone
2. Change Directory into `UKBinCollectionData`
3. `poetry install`
4. `poetry shell`
5. Change Directory into `uk_bin_collection/uk_bin_collection/`
6. python collect_data.py <council> <url>

Steps to run when you already have a venv

1. poetry run python collect_data.py <council> <url>

Other options are use Pythons Setup tools to create a single executable for this

**Comment by dp247** [comment]
<img src="https://media0.giphy.com/media/K5YC2HXUjUPjDM3kjj/giphy.gif"/>

Ahhh, thank you - I was missing `poetry shell`!
