### ISSUE TITLE
London Borough of Hounslow council request

### ISSUE THREAD

**Issue by ronschaeffer** [robbrad/UKBinCollectionData#144]
### Name of Council

London Borough of Hounslow

### Example Postcode

TW7 7HX

### Additional Information

UPRN 100021577765

https://www.hounslow.gov.uk/homepage/86/recycling_and_waste_collection_day_finder

Also asks for house number. I am happy to share my house number in private message if needed.

Thanks

**Comment by ZackaryH8** [comment]
I'm working on this :)

**Comment by robbrad** [comment]
Not working for me 

context.parse_result
'{\n    "bins": []\n}'

https://robbrad.github.io/UKBinCollectionData/3.9/507/#suites/98d3104e051c652961429bf95fa0b5d6/ece4f0a5bb525d6d/

**Comment by ZackaryH8** [comment]
> Not working for me

I will check and get back to you

**Comment by ZackaryH8** [comment]
I've just ran the code using this command

```
python ./collect_data.py LondonBoroughHounslow https://www.hounslow.gov.uk/homepage/86/recycling_and_waste_collection_day_finder -u 100021577765
```

and got the expected output.

**Comment by robbrad** [comment]
Still something fun my going on with this one

https://robbrad.github.io/UKBinCollectionData/3.9/515/#suites/98d3104e051c652961429bf95fa0b5d6/bee2aa5c77386bae/

maybe I need to add some more logging to the step files as to why it’s not working.

**Comment by ZackaryH8** [comment]
I ran the tests locally and it seemed to work? Very odd...

**Comment by robbrad** [comment]
can you try with the integration tests?

Basically clone the repo - setup poetry / venv

Open the .feature file in the test folder and comment out the other councils. Make sure you keep the top | council | line

Then from, the venv run 

make integration_tests

You can also step though using vscode and when you have setup the launch.json to do so

I'd take a look but I'm not in front of my pc sorry

**Comment by robbrad** [comment]
I'll investigate adding more logging to the steps for behave

**Comment by ZackaryH8** [comment]
Behave output:
```
(uk-bin-collection-py3.10) PS C:\Users\zacka\Documents\Scripting\UKBinCollectionData> behave -D runner.continue_after_failed_step=true uk_bin_collection/tests/features/
Feature: Test each council output matches expected results in /outputs # uk_bin_collection/tests/features/validate_council_outputs.feature:1

  Scenario Outline: Validate Council Output -- @1.1 Testing : LondonBoroughHounslow  # uk_bin_collection/tests/features/validate_council_outputs.feature:11
    Given the council: "LondonBoroughHounslow"                                       # uk_bin_collection/tests/features/steps/validate_council.py:7
    When we scrape the data from "LondonBoroughHounslow"                             # uk_bin_collection/tests/features/steps/validate_council.py:14
    Then the result is valid json                                                    # uk_bin_collection/tests/features/steps/validate_council.py:38
    And the output should validate against the schema                                # uk_bin_collection/tests/features/steps/validate_council.py:44

1 feature passed, 0 failed, 0 skipped
1 scenario passed, 0 failed, 0 skipped
4 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m2.885s
```

I've also realised I'm using `3.10.2` so maybe this is another reason?

**Comment by robbrad** [comment]
#215

**Comment by robbrad** [comment]
Looks like it working now 

I have added more logging to the behave tests - more apparent when locally testing

**Comment by ronschaeffer** [comment]
Thanks!

I'll try it out.
