### ISSUE TITLE
[Council Request] North Tyneside

### ISSUE THREAD

**Issue by AlexHedley** [robbrad/UKBinCollectionData#150]
### Name of Council

North Tyneside

### Example Postcode

NE26 2TG

### Additional Information

North Tyneside unfortunately only provides PDFs.

- https://my.northtyneside.gov.uk/category/81/bin-collection-dates

Would a manually created `json` file be acceptable?
Would a particular format be required?

**Comment by dp247** [comment]
Website gives the day of collection, so could possibly parse that and just get the dates of the next 8 days of each bin

**Comment by AlexHedley** [comment]
Example:

Bin Collections

Your bin collection day is a [**Day**]

Your special collections day is [**Day**]

**Comment by dp247** [comment]
I see, black and green alternate. And then special is just a bookable Wednesday thing. Would it be useful to include it @AlexHedley?

**Comment by AlexHedley** [comment]
Thanks @dp247

**Comment by dp247** [comment]
This one still needs a little more work, so I'll reopen for now 😊
