### ISSUE TITLE
Wakefield Council

### ISSUE THREAD

**Issue by nmcrae85** [robbrad/UKBinCollectionData#152]
### Name of Council

Wakefield Council

### Example Postcode

WF15SL

### Additional Information

Current integration doesnt seem to provide an output. Im just getting {"bins": []} returned.

**Comment by nmcrae85** [comment]
Im still seeing this @robbrad 

(uk-bin-collection-py3.9) (base) neil.mcrae@Neil-McRaes-MacBook-Pro uk_bin_collection % python collect_data.py WakefieldCityCouncil "https://www.wakefield.gov.uk/site/Where-I-Live-Results?uprn=63161064"
{
    "bins": []

**Comment by dp247** [comment]
I'll take another look 👀

**Comment by nmcrae85** [comment]
The body returned is slightly different, it's 

'<html>\r\n<head>\r\n<META NAME="robots" CONTENT="noindex,nofollow">\r\n<script src="/_Incapsula_Resource?SWJIYLWA=5074a744e2e3d891814e9a2dace20bd4,719d34d31c8e3a6e6fffd425f7e032f3">\r\n</script>\r\n<body>\r\n</body></html>\r\n'

**Comment by nmcrae85** [comment]
curl -s -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 'https://www.wakefield.gov.uk/site/Where-I-Live-Results?uprn=63161064'
<html style="height:100%"><head><META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW"><meta name="format-detection" content="telephone=no"><meta name="viewport" content="initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"></head><body style="margin:0px;height:100%"><iframe id="main-iframe" src="/_Incapsula_Resource?SWUDNSAI=31&xinfo=10-362792161-0%200NNN%20RT%281673043253621%2038%29%20q%280%20-1%20-1%20-1%29%20r%280%20-1%29%20B12%284%2c315%2c0%29%20U18&incident_id=455000870395534282-1587268356120450506&edet=12&cinfo=04000000&rpinfo=0&cts=oa6U0ZsdlCbZWRIQDlVi8czNj5Us0LxUiGBir1gxQUCmIkmTQvFlJFygNQ7lsqrS&mth=GET" frameborder=0 width="100%" height="100%" marginheight="0px" marginwidth="0px">Request unsuccessful. Incapsula incident ID: 455000870395534282-1587268356120450506</iframe></body></html>%

**Comment by dp247** [comment]
Hmmm, looks like parsing with requests may get around it too. I'll update the parser to try it out sometime this weekend.

**Comment by dp247** [comment]
@nmcrae85 here's hoping this works. I've updated how its run too, just so you're aware - you passed UPRN in now with -u as well

**Comment by nmcrae85** [comment]
Im i doing something wrong here?

python collect_data.py WakefieldCityCouncil https://www.wakefield.gov.uk/site/Where-I-Live-Results -u "63161064"
Traceback (most recent call last):
  File "/Users/neil.mcrae/Documents/UKBinCollectionData/uk_bin_collection/uk_bin_collection/collect_data.py", line 6, in <module>
    from uk_bin_collection.uk_bin_collection.get_bin_data import AbstractGetBinDataClass
ModuleNotFoundError: No module named 'uk_bin_collection'

**Comment by nmcrae85** [comment]
Sorry my bad, moved directories and forgot to install dependancies :)

However, still this

(uk-bin-collection-py3.9) (base) neil.mcrae@Neil-McRaes-MacBook-Pro uk_bin_collection % python collect_data.py WakefieldCityCouncil https://www.wakefield.gov.uk/site/Where-I-Live-Results -u "63161064"
{
    "bins": []
}

**Comment by dp247** [comment]
No worries, everyone gets module not found sometimes (even me, and I've written lots of these 😂).

If you want, you can try use [this branch](https://github.com/dp247/UKBinCollectionData/tree/152-wakefield-council)  in my repo - it's what the current PR is for 😊

**Comment by nmcrae85** [comment]
:) makes me feel better.

Im still getting this tho.

{
    "bins": []
}

**Comment by nmcrae85** [comment]
With the new commits, im seeing these errors now?

(uk-bin-collection-py3.9) (base) neil.mcrae@Neil-McRaes-MacBook-Pro uk_bin_collection % python collect_data.py WakefieldCityCouncil https://www.wakefield.gov.uk/site/Where-I-Live-Results -u "63161064"
/Users/neil.mcrae/Library/Caches/pypoetry/virtualenvs/uk-bin-collection-SJQL-SeG-py3.9/lib/python3.9/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.wakefield.gov.uk'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
Traceback (most recent call last):
  File "/Users/neil.mcrae/Documents/UKBinCollectionData/uk_bin_collection/uk_bin_collection/collect_data.py", line 71, in <module>
    main(sys.argv[1:])
  File "/Users/neil.mcrae/Documents/UKBinCollectionData/uk_bin_collection/uk_bin_collection/collect_data.py", line 57, in main
    return client_code(
  File "/Users/neil.mcrae/Documents/UKBinCollectionData/uk_bin_collection/uk_bin_collection/collect_data.py", line 23, in client_code
    return get_bin_data_class.template_method(address_url, **kwargs)
  File "/Users/neil.mcrae/Documents/UKBinCollectionData/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 53, in template_method
    bin_data_dict = self.parse_data(
  File "/Users/neil.mcrae/Documents/UKBinCollectionData/uk_bin_collection/uk_bin_collection/councils/WakefieldCityCouncil.py", line 62, in parse_data
    datetime.strptime(soup.select("#ctl00_PlaceHolderMain_Waste_output > div:nth-child(4) > "
IndexError: list index out of range

**Comment by dp247** [comment]
@nmcrae85 This is related to Wakefield Council's firewall blocking the scraper, and is unfortunately a wontfix issue.

**Comment by robbrad** [comment]
@dp247 are they blocking the IP or the session?

With requests you can make a session using cookies

**Comment by dp247** [comment]
Looks like IP for me

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by robbrad** [comment]
@nmcrae85 - reduce your scrape time down to once every 24 hrs or weekly if that works - you should be able to do this on Home Assistant https://www.home-assistant.io/integrations/rest/#scan_interval

**Comment by nmcrae85** [comment]
I cant event get it to work without being inside HA. I have just been
trying via term on mac

**Comment by robbrad** [comment]
Does it work from the website? As in if you were just using it like a typical user? 

If not does it work from another internet connection?

**Comment by nmcrae85** [comment]
It does via a web browser from the same network yes.

**Comment by robbrad** [comment]
@nmcrae85  - its not good news im afraid. So what's happening is when you go via your web browser you get the captcha from the imperva which is Wakefield councils anti scraping capability. As a human you answer this and it sets a cookie with a value `visid_incap_2049675=<GUID>` - this then continues to work for your session - now when the Python grabs the page it cant do the imperva captura so cant set the cookie value and fails.

@dp247  : FYI

Wakefield council must have a real issue with scraping to be able to fund putting in such a system (and im sure its not bin data that they are trying to govern - more than likely property data etc) - I would encourage you reach out to Wakefield council and ask them if you can get access to an API for your data - This way they can rate limit you based on an api key and you get the data as you need it.

**Comment by robbrad** [comment]
@dp247 What are your thoughts on a list in the wiki for councils like this ?

**Comment by dp247** [comment]
> @dp247 What are your thoughts on a list in the wiki for councils like this ?

I was thinking of a "not currently supported list" for ones that are hiding behind firewalls, aye. Either in the wiki or in the readme, so people don't open duplicates
