### ISSUE TITLE
Request to add Chelmsford Council

### ISSUE THREAD

**Issue by Johnyb62** [robbrad/UKBinCollectionData#156]
### Name of Council

Chelmsford Council

### Example Postcode

CM3 7AE

### Additional Information

Visiting https://www.chelmsford.gov.uk/myhome/ to enter a postcode or street name, & click Search
This provides the results within that postcode / street, clicking on the house number shows a summary of services, at the bottom  beneath 'Waste' a link "[view or download the collection calendar](https://www.chelmsford.gov.uk/bins-and-recycling/check-your-collection-day/tuesday-b-collection-calendar/)"   which takes you to page which allows you to download the PDF but also lists the next collections Eg

November 2022
Tuesday 1 November: food waste, black bin, green box, card sack
Tuesday 8 November: food waste, brown bin, paper sack, plastic and cartons bag
Tuesday 15 November: food waste, black bin, green box, card sack
Tuesday 22 November: food waste, brown bin, paper sack, plastic and cartons bag
Tuesday 29 November: food waste, black bin, green box, card sack

**Comment by OliverCullimore** [comment]
@dp247 an old version of this one already existed which I've updated to add/fix this one

**Comment by dp247** [comment]
<img src="https://media0.giphy.com/media/SPqz9tfgMGLyo/giphy.gif"/>
