### ISSUE TITLE
Request for Reigate & Banstead Council

### ISSUE THREAD

**Issue by Pathaleon** [robbrad/UKBinCollectionData#157]
### Name of Council

Reigate & Banstead Council

### Example Postcode

SM7 2NL

### Additional Information

Here is the link to check the date:
https://www.reigate-banstead.gov.uk/info/20162/your_recycling_and_refuse_service/850/check_your_bin_collection_dates

Look forward to seeing if its an easy project :)

**Comment by OliverCullimore** [comment]
Additional information:

Final URL accepts UPRNs: https://my.reigate-banstead.gov.uk/en/service/Bins_and_recycling___collections_calendar?uprn=XXXXXX

The data appears to come from post request(s) within the iframe to https://my.reigate-banstead.gov.uk/apibroker/runLookup URLs
