### ISSUE TITLE
Add code to disable Unverified HTTPS warnings

### ISSUE THREAD

**Issue by dp247** [robbrad/UKBinCollectionData#159]
The following code needs to be added to each scraper (if its using the requests module) before the first use of requests:
```python
requests.packages.urllib3.disable_warnings() 
```

This stops the `connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host '<domain>'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings` when executing the script.

## Council list
- [x] BCP
- [x] Bexley
- [x] Blackburn
- [x] Bristol
- [x] Cardiff
- [x] Castlepoint
- [x] Crawley
- [x] Doncaster
- [x] Durham
- [x] East Riding
- [x] Fenland District
- [x] Manchester
- [x] Mid Sussex District
- [x] South Ayrshire
- [x] South Oxfordshire
- [x] South Tyneside
- [x] Tameside MB
- [x] Torridge
- [x] Wakefield
- [x] Waverley Borough
- [x] Wealden District
- [x] Wigan Borough
- [x] Windsor and Maidenhead
- [x] York

**Comment by OliverCullimore** [comment]
Ticking all off as I made sure all Councils using requests. had this added as part of #296
