### ISSUE TITLE
Staffordshire Moorlands District Council

### ISSUE THREAD

**Issue by robjakedorsett** [robbrad/UKBinCollectionData#164]
### Name of Council

Staffordshire Moorlands District Council

### Example Postcode

ST8 6HN

### Additional Information

https://www.staffsmoorlands.gov.uk/sm/bins

Looks like it has a session
https://www.staffsmoorlands.gov.uk/findyourbinday?pageSessionId=e7975220-692a-4494-9d06-bb3da9a3f712&fsn=40485a7c-b20c-46b7-8795-00daebb1a629

**Comment by m0oml** [comment]
This Looks Like Staffordshrie Moorlands not Staffordshire County Council

**Comment by OliverCullimore** [comment]
Looks to be the same/similar system to #362

Working address: 112 Tunstall Road, Biddulph, ST8 6HN
