### ISSUE TITLE
North West Leicestershire

### ISSUE THREAD

**Issue by oliverjuice** [robbrad/UKBinCollectionData#174]
### Name of Council

North West Leicestershire

### Example Postcode

DE74 2FZ

### Additional Information

https://nwleics-self.achieveservice.com/en/AchieveForms/?form_uri=sandbox-publish://AF-Process-bde93819-fa47-4bba-b094-bef375dbef0c/AF-Stage-b4ac5d55-7fb7-4c40-809f-4d1856399bed/definition.json&redirectlink=/en&cancelRedirectLink=/en&noLoginPrompt=1

**Comment by OliverCullimore** [comment]
Similar/same system as #244

**Comment by OliverCullimore** [comment]
Likely need to use the selenium approach for these ones as they're very session based

**Comment by dp247** [comment]
Works for me :D hehehe

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by robbrad** [comment]
Looks like the url above is now forbidden

**Comment by robbrad** [comment]
Need to adapt to use https://www.nwleics.gov.uk/pages/collection_information
