### ISSUE TITLE
Brighton and Hove Council Request

### ISSUE THREAD

**Issue by Callum-C** [robbrad/UKBinCollectionData#188]
### Name of Council

Brighton and Hove City Council

### Example Postcode

BN3 3GB

### Additional Information

Bin collection days can be accessed [here](https://cityclean.brighton-hove.gov.uk/link/collections), with the more general council website available [here](https://www.brighton-hove.gov.uk/).

Upon entering a postcode, the website will provide a drop down menu with every address in that postcode.

When an address has been selected, the collection days will be made available.

Best regards,
Callum

**Comment by robbrad** [comment]
@Callum-C 

Im seeing 
![image](https://github.com/robbrad/UKBinCollectionData/assets/6122503/5f6ab668-38ae-4aea-9fe6-b539b6fc5c8c)

No dates are shown here for the example postcode - do you have an example where it displays dates and bin types?

Just wondering how we integrate this one

**Comment by jawj** [comment]
Try BN1 5PP, then pick any address (e.g. 1 Coventry Street).

**Comment by jawj** [comment]
It appears to be built with Mendix. I took a quick look at the requests and responses, and I don't think I've ever seen such an enormous pile of drivel.

**Comment by robbrad** [comment]
Released
