### ISSUE TITLE
Parity between feature file and councils folder

### ISSUE THREAD

**Issue by dp247** [robbrad/UKBinCollectionData#197]
> interestingly there are only 49 councils in the feature file. 52 Schemas and 57 councils supported - needs to be 1:1:1 really - probably some only need a Schema adding etc

**Comment by robbrad** [comment]
Council Parse on the left and Council Schemas on the right

![image](https://user-images.githubusercontent.com/6122503/220270566-d9fae4d7-06d3-4df6-85aa-b105621357d2.png)

**Comment by robbrad** [comment]
imput.json has parity

**Comment by OliverCullimore** [comment]
I believe it's just Crawley Borough Council that's missing it's .json and .schema files now.

I tried to run it to be able to generate those yesterday while looking at fixing any other failing tests I could with no luck.

@dp247 if you'd be able to see if you can successfully run it if you still have whatever you may have set up ref the dotenv stuff in place. Then it should just be a case of running it with the -d flag to automatically create the .json file and then generate the schema file from that and we should have parity.
