### ISSUE TITLE
CrawleyBoroughCouncil needs OS API key

### ISSUE THREAD

**Issue by robbrad** [robbrad/UKBinCollectionData#198]
Need a way to pass OS API key in as a parameter to CrawleyBoroughCouncil as it's currently hard coded in the script

**Comment by OliverCullimore** [comment]
@dp247 while reading the docs for Crawley Borough Council to try to set it up and generate the feature test files I questioned is there any benefit over using the OS API to look up the USRN over adding a USRN parameter like we have for UPRN as the docs state you can look it up on [FindMyAddress](https://www.findmyaddress.co.uk/search) or [FindMyStreet](https://www.findmystreet.co.uk/map) like we require users to do to get their UPRN if that's required for their council?

**Comment by dp247** [comment]
I think FindMyAddress was down when I wrote it, so feel free to change it as necessary :p
