### ISSUE TITLE
Kingston Upon Thames

### ISSUE THREAD

**Issue by ManicGTI** [robbrad/UKBinCollectionData#20]
Hi there, i've been wanting to do this for a while but I don't think my skills are up to it, any help with **Kingston Upon Thames** would be greatly appreciated!

https://www.kingston.gov.uk/when-is-my-collection
They are also listed on here:   https://maps.kingston.gov.uk/propertyServices/InMyArea

Thanks!

**Comment by ManicGTI** [comment]
I've had a try at this but struggling, I have got as far as getting the Beautiful Soup extract out, but the section where the data I need is just a load of numbers, not regular html.   But if I look at it in Chrome I can see the data fields?

After a bit of googling I think that the data is embedded in an Java iframe element, so will need Dynamic scraping?

IE: https://kingston-self.achieveservice.com/service/in_my_area_results?uprn=100021782629
(not my address)

**Comment by ZackaryH8** [comment]
Drop an example postcode for me and I'll have a look at it
