### ISSUE TITLE
Forest of Dean District Council Request 

### ISSUE THREAD

**Issue by BigToze** [robbrad/UKBinCollectionData#204]
### Name of Council

Forest of Dean District Council 

### Example Postcode

GL15 6JT

### Additional Information

http://apps.fdean.gov.uk/LocationService/?Spotlight=Collections

**Comment by robbrad** [comment]
@BigToze - the URL returns a 404 do you have another one that works ?

**Comment by skelt0** [comment]
https://www.fdean.gov.uk/bins-and-recycling/check-your-collection-day/

Takes you to https://community.fdean.gov.uk/s/waste-collection-enquiry

<img width="924" alt="image" src="https://github.com/robbrad/UKBinCollectionData/assets/16990151/6e4aa8de-f189-4c54-aab3-d54de3e81e2c">

Leads into eventually:

https://community.fdean.gov.uk/s/sfsites/aura?r=18&aura.FlowRuntimeConnect.navigateFlow=1

Which looks session based and a pain. 

<img width="883" alt="image" src="https://github.com/robbrad/UKBinCollectionData/assets/16990151/5739dd38-a3e8-482b-be36-17cd598dbd96">

Selenium candidate maybe?

**Comment by dp247** [comment]
It returns some JSON, at least

**Comment by robbrad** [comment]
This one was fun!
