### ISSUE TITLE
Crawley Borough Council

### ISSUE THREAD

**Issue by graemearthur** [robbrad/UKBinCollectionData#25]
Interesting one, doesn't look like they have an API they require a log in to view your details or at least I thought
https://my.crawley.gov.uk/ 
looking at the page source you don't have to be logged in once you have a customer info via the page source, I tested this in an incognito window so it should be able to be scraped if someone with the knowhow wants to work with me to get this one working, I just don't want to publicly post my customer info

**Comment by graemearthur** [comment]
https://my.crawley.gov.uk/appshost/firmstep/self/apps/custompage/waste?language=en&uprn=x&usrn=x&day=30&month=10&year=2021

Looking in to this further I have discovered you only need the date, uprn(Unique Property Reference Number) and usrn(Unique Street Reference Number)
this should then be easy enough to scrape for someone with those skills

**Comment by graemearthur** [comment]
I have found you can lookup uprn(Unique Property Reference Number) and usrn(Unique Street Reference Number)

https://www.findmystreet.co.uk/map

https://www.findmyaddress.co.uk/search

**Comment by ZackaryH8** [comment]
There is a JSON API but it is horrible to work with, I have added it to my Postman collection [here](https://www.postman.com/payload-physicist-86737988/workspace/bin-collection-api/collection/16208242-ac6cff17-0ef1-4f46-ae7a-34141f2779aa)

On an unrelated note, they leaked their Google Maps API key
