### ISSUE TITLE
Halton Borough Council

### ISSUE THREAD

**Issue by smithlh** [robbrad/UKBinCollectionData#250]
### Name of Council

Halton Borough Council

### Example Postcode

WA7 4HA

### Additional Information

https://webapp.halton.gov.uk/PublicWebForms/WasteServiceSearchv1.aspx

**Comment by OliverCullimore** [comment]
Google reCAPTCHA in use so this one might be a no-go sadly

**Comment by robbrad** [comment]
reCAPTCHA 🎯 💥
