### ISSUE TITLE
Wigan Council

### ISSUE THREAD

**Issue by thefirstavi** [robbrad/UKBinCollectionData#26]
https://github.com/Tmp2k/wigan-council-api

GET /bins?postcode=WN1+2RW

**Comment by thefirstavi** [comment]
The actual site that can be used in browser is here https://apps.wigan.gov.uk/MyNeighbourhood/MyArea.aspx 

Example postcode WN1 2RW
Unfortunately python scripting is way beyone me, but ill pop it here in case anyone fancies a challenge,.

I think the API above is one someone has already had a bash at, but again, my technical skills are exhausted.

**Comment by robbrad** [comment]
I’ll take a look at this tonight for you mate after the kids bedtime. I have been refactoring the repo(dev branch) to use a more common approach.

**Comment by thefirstavi** [comment]
Cheers, I have managed to find this https://wigan.nemiah.uk/bins.php?postcode=wn1%202rw Which is seemingly an APi someone has written already for their own app https://binday.uk/ (github referenced above) , I've learnt a lot so far seeing as ive never tried to use an API before. 

I think ive worked out i need to look at using a rest sensor approach ?

**Comment by dp247** [comment]
Closed with #117
