### ISSUE TITLE
Debian install of HomeAssistant help with installation

### ISSUE THREAD

**Issue by jameswilso** [robbrad/UKBinCollectionData#260]
Please can you offer some help with installation on a debian installation?
I'm using Terminal through the addons
git clone https://github.com/robbrad/UKBinCollectionData
apk add poetry
cd UKbincollectiondata
poetry install

results in error failed to build psutil

Any help appreciated

**Comment by dp247** [comment]
Hi @jameswilso, what version of Python is installed on Debian?

**Comment by dp247** [comment]
Sorry for the wait, I went to get a Debian VM so I could understand a bit better 😀.

Unfortunately, I didn't reproduce your issue, but I'll write how I got it working on Debian 11:

1. Installed Python using [this](https://cloudinfrastructureservices.co.uk/how-to-install-python-3-in-debian-11-10/) guide (although I also got 3.10.10)
2. Installed `curl` so I could grab poetry - just simple `sudo apt install curl`
3. Ran the [Poetry install script](https://github.com/python-poetry/install.python-poetry.org) for Linux builds:
```bash
curl -sSL https://install.python-poetry.org | python3 -
```
4. Updated Debian's PATH variable by adding Poetry's shortcut to `.bashrc` in the home directory and rebooting the machine:
```bash
export PATH="$HOME/.local/bin:$PATH"
```
5. Cloned the repo as above:
```bash
git clone https://github.com/robbrad/UKBinCollectionData
```
6. Opened a Terminal window in the folder and installing the dependencies with Poetry:
```bash
poetry install
``` 
*It's important you get a message that says `Installing the current project: uk_bin_collection (0.1.0)`, or you'll get a module error when running the script - this actually took me a couple of times.
7. Still in the top folder running the following:
```bash
poetry run python uk_bin_collection/uk_bin_collection/collect_data.py
```

**Comment by robbrad** [comment]
@jameswilso - also try installing python-header files

This looks like an issue with your python installation 

`sudo apt-get install python-dev`

**Comment by jameswilso** [comment]
I've managed to make some steps forward and can now retrieve my councils data successfully from the CLI. How do I introduce it into Home Assistant as an automated script? I can't see it in the instructions I'm sure it is obvious but not done before.

**Comment by dp247** [comment]
> I've managed to make some steps forward and can now retrieve my councils data successfully from the CLI. How do I introduce it into Home Assistant as an automated script? I can't see it in the instructions I'm sure it is obvious but not done before.

@robbrad will be able to help, he's the home assistant wizard

**Comment by robbrad** [comment]
@jameswilso before we try to make this a Home Assistant extension, you have a few options 

You can use https://www.home-assistant.io/integrations/script/ with an automation to either create a json file on your file system, then use a home assistant rest sensor to extract the value.

or similarly use a bash script with cronjob to make a json file on a schedule see : https://community.home-assistant.io/t/iterate-a-json-file-object-with-a-sensor/421611

**Comment by jameswilso** [comment]
Any advise on running a Cron job to periodically retrieve the json file? I can run as a manual execute of the script but as a cronjob I get the error:
poetry: command not found

**Comment by dp247** [comment]
> Any advise on running a Cron job to periodically retrieve the json file? I can run as a manual execute of the script but as a cronjob I get the error: poetry: command not found

How did you set it up?

**Comment by jameswilso** [comment]
using root ran
crontab -e
*/2 * * * * poetry run python /usr/share/hassio/collect_data.py SomersetCouncil https://www.somerset.gov.uk/ -u XXXXXXXX -p "BSXXXXX" > /usr/share/hassio/homeassistant/www/homebinschedule.json 2>&1

also tried:
*/2 * * * * /usr/share/hassio/ukbinrun.sh > /usr/share/hassio/homeassistant/www/homebinschedule.json 2>&1

ukbinrun.sh:
poetry run python /usr/share/hassio/UKBinCollectionData/uk_bin_collection/uk_bin_collection/collect_data.py SomersetCouncil https://www.somerset.gov.uk/ -u XXXXXXX -p "BSXXXX" > /usr/share/hassio/homeassistant/www/homebinschedule.json

**Comment by robbrad** [comment]
Hi @jameswilso 

As a guess - is poetry installed as root? Crontab here is running as root.

When you install poetry it puts it in the python installation modules folder. This is relative to the user

Does it need to run as root?

Also I'm guessing, is python an alias for python3?

Poetry's only job is package management and creation of a python virtual environment(venv). Without poetry you could activate the venv manually from the shell. Something like 

`source /path/to/venv/bin/activate`

Once active you can just run 

python collect_data.py

**Comment by robbrad** [comment]
Closing due to no response. Reopen if needed
