### ISSUE TITLE
West Suffolk Council

### ISSUE THREAD

**Issue by Delta1292** [robbrad/UKBinCollectionData#262]
### Name of Council

West Suffolk Council

### Example Postcode

IP33 3YU

### Additional Information

https://westsuffolk-self.achieveservice.com/service/Waste_New_Round_Interim_Postcode_Lookup

https://westsuffolk-self.achieveservice.com/service/WSS_EX_Inf_Bin_Collection_Postcode_Lookup

**Comment by OliverCullimore** [comment]
Similar/same system as #174 if using the https://westsuffolk-self.achieveservice.com/service/WSS_EX_Inf_Bin_Collection_Postcode_Lookup method
