### ISSUE TITLE
Woking Borough Council

### ISSUE THREAD

**Issue by silentnight08** [robbrad/UKBinCollectionData#263]
### Name of Council

Woking Borough Council 

Our service is provided by "jointwastesolutions.org" - adding support would work the same for atleast:

- Woking Borough Council
- Elmbridge Borough Council
- Mole Valley District Council
- Surrey Heath Borough Council

### Example Postcode

GU21 4JY

### Additional Information

https://www.jointwastesolutions.org/check-my-collection-day-2/
https://asjwsw-wrpwokingmunicipal-live.whitespacews.com/?Track=2023/04/05/AEHIC6NMNRYXC&serviceID=A&seq=1

I have been able to pull the information and filter it a little using this command:
`curl -s 'https://asjwsw-wrpwokingmunicipal-live.whitespacews.com/mop.php?Track=2023/04/05/AEHIC6NMNRYXC&serviceID=A&seq=3&pIndex=2#!' | pup '.displayinlineblock li json{}' > binCollection.json`

Then filter it further to 
`cat binCollection.json | jq '.[] | select(.tag == "li" and (.children[]? | select(.tag == "p" and (.text | test("(Recycling|Rubbish|Food waste|Batteries-small electricals-textiles|\\d{2}/\\d{2}/\\d{4})"; "i"))))) | .children[]? | select(.tag == "p") | .text'`

This might not be the most efficient methods above - and food waste/battery collection likely isn't relevant for most people so should be removed from the output (not sure how to do this)

Sample output after above commands:
`"05/04/2023"
"Recycling"
"05/04/2023"
"Food waste"
"05/04/2023"
"Batteries-small electricals-textiles"
"12/04/2023"
"Rubbish"
"12/04/2023"
"Food waste"
"12/04/2023"
"Batteries-small electricals-textiles"
"19/04/2023"
"Recycling"
"19/04/2023"
"Food waste"
"19/04/2023"
"Batteries-small electricals-textiles"
"26/04/2023"
"Rubbish"
"26/04/2023"
"Food waste"
"26/04/2023"
"Batteries-small electricals-textiles"
"03/05/2023"
"Recycling"
"03/05/2023"
"Food waste"
"03/05/2023"
"Batteries-small electricals-textiles"`

If I can provide any further information or assist in any way please let me know.

Thanks for everything you do for the community!

**Comment by dp247** [comment]
Hmmm, I was so ready to submit this, then I realized that each request has a unique URL, so it'll take a bit longer 😅

**Comment by silentnight08** [comment]
I'm just really happy someone is looking at it (thank you!!!) :) I was trying to do it for a day or two when I submitted and I keep going back to it but failing :'D

**Comment by dp247** [comment]
You're welcome! I can comment my code extra well if you'd like to learn how I went about it?

**Comment by silentnight08** [comment]
Thank you again for doing this! honestly amazing work and very much appreciated.
I did already read through the code (not that I understood all too much!).

is there a guide posted anywhere for implementing into home assistant? will try to work this part out myself meanwhile.

**Comment by dp247** [comment]
You're very welcome! 😊

I don't use HomeAssistant myself, but @robbrad may be able to point you in the right direction!
