### ISSUE TITLE
Rushmoor Council

### ISSUE THREAD

**Issue by PortlyAssassin** [robbrad/UKBinCollectionData#266]
### Name of Council

Rushmoor Council

### Example Postcode

gu148hq

### Additional Information

https://www.rushmoor.gov.uk/recycling-rubbish-and-environment/bins-and-recycling/bin-collection-day-finder/

The only link I can see that include the address data is if you choose the option view the data in another format, which will open the following link;

https://www.rushmoor.gov.uk/recycling-rubbish-and-environment/bins-and-recycling/download-or-print-your-bin-collection-calendar/?address=1%20Longfield%20Close,%20Farnborough,%20Hampshire,%20GU14%208HQ&uprn=100060545025&weeks=26

You can change the weeks argument to be 1 to limit the data returned. I tried retrieving this url with curl but it just times out for me.

**Comment by dp247** [comment]
This one is interesting, you can also cut out the address entirely like so:
https://www.rushmoor.gov.uk/recycling-rubbish-and-environment/bins-and-recycling/download-or-print-your-bin-collection-calendar/?uprn=100060545025&weeks=12

**Comment by robbrad** [comment]
@dp247 : this one is broken :(

but the good news is a url like : https://www.rushmoor.gov.uk/Umbraco/Api/BinLookUpWorkAround/Get?selectedAddress=100060545034

returns

```
<string>
{"UPRN":"100060545034","NextCollection":{"CollectionDay":"Wednesday","CollectionSchedule":"A","RefuseCollectionBinDate":"2023-12-29T00:00:00","RefuseBinExceptionMessage":"Christmas and New Year","RecyclingCollectionDate":"2023-12-20T00:00:00","RecyclingExceptionMessage":"","GardenWasteCollectionDate":"2023-12-29T00:00:00","GardenWasteExceptionMessage":"Christmas and New Year","FoodWasteCollectionDate":"2023-12-20T00:00:00","FoodWasteExceptionMessage":""},"PreviousCollection":{"CollectionDay":"Wednesday","CollectionSchedule":"A","RefuseCollectionBinDate":"2023-12-13T00:00:00","RefuseBinExceptionMessage":"","RecyclingCollectionDate":"2023-12-20T00:00:00","RecyclingExceptionMessage":"","GardenWasteCollectionDate":"2023-12-13T00:00:00","GardenWasteExceptionMessage":"","FoodWasteCollectionDate":"2023-12-13T00:00:00","FoodWasteExceptionMessage":""},"BulkCollectionDetails":null}
</string>
```

**Comment by dp247** [comment]
> @dp247 : this one is broken :(
> 
> but the good news is a url like : https://www.rushmoor.gov.uk/Umbraco/Api/BinLookUpWorkAround/Get?selectedAddress=100060545034
> 
> returns
> 
> ```
> <string>
> {"UPRN":"100060545034","NextCollection":{"CollectionDay":"Wednesday","CollectionSchedule":"A","RefuseCollectionBinDate":"2023-12-29T00:00:00","RefuseBinExceptionMessage":"Christmas and New Year","RecyclingCollectionDate":"2023-12-20T00:00:00","RecyclingExceptionMessage":"","GardenWasteCollectionDate":"2023-12-29T00:00:00","GardenWasteExceptionMessage":"Christmas and New Year","FoodWasteCollectionDate":"2023-12-20T00:00:00","FoodWasteExceptionMessage":""},"PreviousCollection":{"CollectionDay":"Wednesday","CollectionSchedule":"A","RefuseCollectionBinDate":"2023-12-13T00:00:00","RefuseBinExceptionMessage":"","RecyclingCollectionDate":"2023-12-20T00:00:00","RecyclingExceptionMessage":"","GardenWasteCollectionDate":"2023-12-13T00:00:00","GardenWasteExceptionMessage":"","FoodWasteCollectionDate":"2023-12-13T00:00:00","FoodWasteExceptionMessage":""},"BulkCollectionDetails":null}
> </string>
> ```

I'll have a looksy
