### ISSUE TITLE
Waltham Forest Council

### ISSUE THREAD

**Issue by spamawaymate** [robbrad/UKBinCollectionData#269]
### Name of Council

Waltham Forest 

### Example Postcode

E17 5DX

### Additional Information

Hi,
Can anyone help with Waltham Forest council please? 
Web address is below: 
Thank you
https://portal.walthamforest.gov.uk/AchieveForms/?mode=fill&consentMessage=yes&form_uri=sandbox-publish://AF-Process-d62ccdd2-3de9-48eb-a229-8e20cbdd6393/AF-Stage-8bf39bf9-5391-4c24-857f-0dc2025c67f4/definition.json&process=1&process_uri=sandbox-processes://AF-Process-d62ccdd2-3de9-48eb-a229-8e20cbdd6393&process_id=AF-Process-d62ccdd2-3de9-48eb-a229-8e20cbdd6393

**Comment by OliverCullimore** [comment]
@spamawaymate struggling to find a working address with that postcode, please could you provide a working example address for us to use when we get to this one?

**Comment by OliverCullimore** [comment]
Similar/same system as #174

**Comment by spamawaymate** [comment]
Hi. For Waltham forest try:
204 as door number. It's billet road.
Postcode is E17 5DX. 
The addresses pop up once you've entered a postcode at the link

**Comment by dp247** [comment]
This portal seems to be broken
![image](https://github.com/robbrad/UKBinCollectionData/assets/9065463/69b6cb4d-968f-488b-84aa-947e47814016)

**Comment by OliverCullimore** [comment]
@spamawaymate it looks like the council's bin collection days checker is broken.

If you can find and send over a new example address that's working we can try to implement this for you.

Otherwise, without your council fixing the checker (which you may wish to contact them about) we can't add support for this.

**Comment by spamawaymate** [comment]
Hi,
Thanks for checking this for me. I have tried 176 as the door number and it loads just fine. Some of the door numbers in that drop down box don't seem to load any details like in your image.
![E175DX](https://github.com/robbrad/UKBinCollectionData/assets/11852681/7c810f84-af64-4e35-bead-be121a0c3a79)
