### ISSUE TITLE
East Riding Council

### ISSUE THREAD

**Issue by pjd15** [robbrad/UKBinCollectionData#27]
https://www.eastriding.gov.uk/environment/bins-rubbish-recycling/bins-and-collections/bin-collection-dates/

**Comment by ZackaryH8** [comment]
Linked below is a postman collection, it returns addresses and collection dates

[Click Here](https://www.postman.com/payload-physicist-86737988/workspace/bin-collection-api/collection/16208242-0d4c6051-f897-410e-a738-83e07fa24878)

**Comment by dp247** [comment]
I did this... but apparently didn't write a close note in the PR...

**Comment by robbrad** [comment]
VERY broken - taking 12 mins to time out 

Suggest selenium approach here

https://www.eastriding.gov.uk/environment/bins-rubbish-recycling/bins-and-collections/bin-collection-dates/

Postcode: HU178LL

Full address Approach : 21 CENTRAL AVENUE BEVERLEY HU17 8LL

See : #204 code for example
