### ISSUE TITLE
Bolton Council Bins - Broken

### ISSUE THREAD

**Issue by compynei** [robbrad/UKBinCollectionData#272]
### Name of Council

Bolton Council

### Example Postcode

BL1 5PQ

### Additional Information

https://www.bolton.gov.uk/next-bin-collection#collectionday

Used to be able to parse the JSON as per the below:
https://community.home-assistant.io/t/bin-waste-collection/55451/265

But this seems to have stopped working and the new page must be used:
https://www.bolton.gov.uk/next-bin-collection#collectionday

**Comment by compynei** [comment]
Editing this to be clear that the BoltonCouncil way in the .py file no longer returns true results and hte page seems to have moved here: https://www.bolton.gov.uk/next-bin-collection

The current script returns data from 2022 (now all invalid)

**Comment by dp247** [comment]
I've just added #275 as a fix. It uses the new site URL (which is hardcoded, but a URL is required in the console command) and passes in the UPRN needed by the site. A full run command will look like:
```commandline
python collect_data.py BoltonCouncil https://www.bolton.gov.uk/next-bin-collection -u "uprn|street-address"
```
A couple things about this:
- The UPRN needs double quotes - it complained for me with single quotes
- `uprn` should be taken from [FindMyAddress](https://www.findmyaddress.co.uk/search)
- `street-address` should be taken from the Bolton Council results page after the address is selected - just copy and paste the grey, all-caps text on [this](https://www.bolton.gov.uk/next-bin-collection#collectionday) page.
- Make sure there are no spaces between quotes or the pipe separator - the only ones that can be should be in address.

**Comment by compynei** [comment]
> I've just added #275 as a fix. It uses the new site URL (which is hardcoded, but a URL is required in the console command) and passes in the UPRN needed by the site. A full run command will look like:
> 
> ```
> python collect_data.py BoltonCouncil https://www.bolton.gov.uk/next-bin-collection -u "uprn|street-address"
> ```
> 
> A couple things about this:
> 
> * The UPRN needs double quotes - it complained for me with single quotes
> * `uprn` should be taken from [FindMyAddress](https://www.findmyaddress.co.uk/search)
> * `street-address` should be taken from the Bolton Council results page after the address is selected - just copy and paste the grey, all-caps text on [this](https://www.bolton.gov.uk/next-bin-collection#collectionday) page.
> * Make sure there are no spaces between quotes or the pipe separator - the only ones that can be should be in address.

Awesome thanks! Look forward to trying this out with the fix! Great project guys
