### ISSUE TITLE
Andrew-Chen-Wang/github-wiki-action v3 ➡ v4 has a different interface

### ISSUE THREAD

**Issue by jcbhmr** [robbrad/UKBinCollectionData#284]
Hello! 👋
I am @jcbhmr one of the contributors from Andrew-Chen-Wang/github-wiki-action

I think that #281 may have borked the wiki deployment action by updating to a different **major version** with an incompatible API (that is what major versions are for after all! 😅) and not changing the options passed into the action to match the new interface.

Luckily, you haven't seen it run to have an issue yet! 🎉 https://github.com/robbrad/UKBinCollectionData/actions/workflows/wiki.yml

https://github.com/robbrad/UKBinCollectionData/blob/4217b2d99efe8f53bf6033b2052e549b0364504e/.github/workflows/wiki.yml#L50-L58

https://github.com/Andrew-Chen-Wang/github-wiki-action/releases/tag/v4.0.0

> ## Migration guide
>
> _See https://github.com/Andrew-Chen-Wang/github-wiki-action/releases/tag/v4.0.0_
>
> Here's an example of the transition:
> 
> ```yaml
> - uses: Andrew-Chen-Wang/github-wiki-action@v2
>   env:
>     WIKI_DIR: my-wiki/
>     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>     GH_MAIL: ${{ secrets.YOUR_EMAIL }}
>     GH_NAME: ${{ github.repository_owner }}
>     EXCLUDED_FILES: "Special-page.md Hidden.md"
> ```
> 
> ```yaml
> - uses: Andrew-Chen-Wang/github-wiki-action@v4
>   with:
>     path: my-wiki
>     ignore: |
>       Special-page.md
>       Hidden.md
> ```

cc @robbrad since I see you merged #281

**Comment by robbrad** [comment]
Fixed thanks @jcbhmr
