### ISSUE TITLE
Add South Gloucestershire council

### ISSUE THREAD

**Issue by ayshfm1** [robbrad/UKBinCollectionData#287]
### Name of Council

South Gloucestershire

### Example Postcode

BS32 8ES

### Additional Information

https://beta.southglos.gov.uk/waste-and-recycling-collection-date/

**Comment by OliverCullimore** [comment]
Data URL: https://webapps.southglos.gov.uk/Webservices/SGC.RefuseCollectionService/RefuseCollectionService.svc/getCollections/566419

Where 566419 is the UPRN

C1, C2 & C3 look to map to "Recycling, food bin"
G1, G2 & G3 look to map to "Garden waste"
R1, R2 & R3 look to map to "Black bin"

**Comment by ChrisThomas42** [comment]
Another request for South Glos please.

My response:
```[{"C1":"17\/11\/2023","C2":"01\/12\/2023","C3":"15\/12\/2023","CalendarName":"FA","G1":"24\/11\/2023","G2":"08\/12\/2023","G3":"22\/12\/2023","R1":"24\/11\/2023","R2":"08\/12\/2023","R3":"22\/12\/2023"}]```
