### ISSUE TITLE
Fix Allure reports for 3.8

### ISSUE THREAD

**Issue by OliverCullimore** [robbrad/UKBinCollectionData#298]
As mentioned on #191 it looks like the 3.8 Allure reports haven't been updated since sometime in February as the report we're seeing lists it's executor as https://github.com/robbrad/UKBinCollectionData/actions/runs/4272808681

**Comment by robbrad** [comment]
@OliverCullimore - im seeing 3.8 reports https://robbrad.github.io/UKBinCollectionData/3.8/516/

But I am seeing Allure reports being skipped on the action when not merged to master

**Comment by OliverCullimore** [comment]
@robbrad I'm seeing the last run of the tests in 3.8 as 25/02/2023

![Screenshot_2023-07-16-22-41-22-29_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/robbrad/UKBinCollectionData/assets/17053927/a5ffd55e-ab49-4c48-9616-e879a0cb0fd3)

The 3.9 tests history seemed okay though.

I'm not familiar with Allure tests, is it possible I'm seeing cached version or are you seeing the same?

**Comment by robbrad** [comment]
@OliverCullimore Fixed... - but we lost our history - I had to recreate the gh-pages branch as an empty branch - also noticed allure reports keeping more than 20 in the history - so we should keep an eye on this and its size

**Comment by OliverCullimore** [comment]
Amazing @robbrad more green showing now for 3.8 as I'd hoped

**Comment by robbrad** [comment]
Still happening :( - the 3.8 reports are there but the index.html for it points at an old run

**Comment by dp247** [comment]
Only difference I can see is that [Action ID 804](https://github.com/robbrad/UKBinCollectionData/actions/runs/5571001354/jobs/10175610285) in the 3.8 action ends like: 
![image](https://github.com/robbrad/UKBinCollectionData/assets/9065463/c17decfe-5e93-47c1-9ab8-919df17d8968)
whereas the others [e.g. Action 809](https://github.com/robbrad/UKBinCollectionData/actions/runs/5594430632/jobs/10229260311) end like:
![image](https://github.com/robbrad/UKBinCollectionData/assets/9065463/6161f207-7d8f-4b9f-a910-167f4094f189)

...but not sure if that's actually related 😂

**Comment by robbrad** [comment]
Simple fix in the end !!

https://github.com/robbrad/UKBinCollectionData/commit/99a5928f6e4c2464718bcfdad4882f448655869f
