### ISSUE TITLE
Request Aylesbury Vale Council (Bucks)

### ISSUE THREAD

**Issue by MrSeanRoss** [robbrad/UKBinCollectionData#312]
### Name of Council

Aylesbury Vale

### Example Postcode

LU7 9EQ

### Additional Information

https://www.buckinghamshire.gov.uk/waste-and-recycling/find-out-when-its-your-bin-collection/

https://account.aylesburyvaledc.gov.uk/resident2/s/guest-flow-form?service_ref=DSHLC_AVDC_Find_Bin_Days

This council site is a child of the Buckinghamshire Council site and seems to work the same as the Chilterns site [#chilter](https://github.com/robbrad/UKBinCollectionData/issues/154#issue-1523059303)

**Comment by danielcecil** [comment]
Hi, I've been looking at this as Aylesbury Vale have changed their website which is a bit more tricky to scrape. However I have intercepted their mobile app which uses a SOAP API if anyone clever enough can code it up?

I've attached a Postman collection for the two endpoints available here: http://avdcbins.web-labs.co.uk/RefuseApi.asmx
[Aylesbury_Bins.postman_collection.zip](https://github.com/robbrad/UKBinCollectionData/files/12293411/Aylesbury_Bins.postman_collection.zip)

**Comment by OliverCullimore** [comment]
Addressed by #313
