### ISSUE TITLE
Request to add Gateshead Council

### ISSUE THREAD

**Issue by dan-abc** [robbrad/UKBinCollectionData#316]
### Name of Council

Gateshead Council

### Example Postcode

NE16 5LQ

### Additional Information

Bin day checker URL is https://www.gateshead.gov.uk/article/3150/Bin-collection-day-checker

Requires a postcode and address. Address is selected via a select element, populated via javascript.

**Comment by OliverCullimore** [comment]
Looks to be the same/similar system to #362
