### ISSUE TITLE
Line endings

### ISSUE THREAD

**Issue by aejh** [robbrad/UKBinCollectionData#32]
Hi Rob,

I'm having a hack around with the scripts, but am having line ending issues, specifically adding the shebang `#!/usr/bin/env python3` to collect_data.py in develop. It looks like the master branch uses LF endings, but the develop has switched to CRLF. Was this a deliberate choice? (If so, HuntingdonDistrictCouncil.py in develop appears to be LF endings). 

I'm totally unfamiliar with git/github's line end mangling and the expected formatting in repo and working copy, except on *nix files must be LF for shebangs to work. If it wasn't intentional, I *think* I've sorted it in aejh/UKBinCollectionData@ 46e00c992ce51ce31a65ae4eb90cc53391d91ff1 (from here: https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/#a-simple-gitattributes-config), can make a pull request if you think I'm barking up the right tree!

Cheers, Al.

**Comment by ZackaryH8** [comment]
`HuntingdonDistrictCouncil.py` in my VS Code was set to CRLF when I pushed as far as I know

**Comment by robbrad** [comment]
Hey @aejh - I'd advise following this http://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_formatting_and_whitespace

TL:DR
On your Mac or Linux you want to set `git config --global core.autocrlf input`
On Windows I have set `git config --global core.autocrlf true`

**Comment by aejh** [comment]
Finally got a moment to have a play and read up on this.

@robbrad:  I've tried with that setting enabled, but with no luck. According to the doc linked, "This setup should leave you with CRLF endings in Windows checkouts, but LF endings on macOS and Linux systems **and in the repository**." (emphasis mine). Unfortunately, there appears to be a mix of file ending in the repo. From [here](https://stackoverflow.com/questions/35801024/how-to-see-what-type-of-line-endings-are-already-in-git-repository),  `git ls-files --eol` in a checkout shows both types of line ending. I guess when the new files for the develop branch were added, they were CRLF (looks like core.autocrlf=true makes them CRLF in the repo, but that's not what the docs suggest?!). I can't find any git settings to convert from CRLF (in repo) to LF (locally).  This [post](https://www.edwardthomson.com/blog/git_for_windows_line_endings.html) says,  "The problem with core.autocrlf is that if some people have it set to true and some don’t, you’ll get a mix of line endings in your repository.", which appears to be what's happened. It suggests using a .gitattributes file to have line ending settings set with the repo, rather than each client/contributor.

@ZackaryH8: What OS did you commitfrom? I guess your CRLFs was converted to LF by your core.autocrlf setting when it was added. You can get it with `git config --get core.autocrlf`.

**Comment by ZackaryH8** [comment]
I committed from a Windows based system

```
git config --get core.autocrlf
true
```

**Comment by aejh** [comment]
Well, at least that behaviour matches the docs (CRLF locally, LF in the repo)!

**Comment by robbrad** [comment]
Ok interesting: do we need to do a bit of a check all cut and run?

**Comment by aejh** [comment]
It feels like it'd be worth sorting out. In my  [develop-lineendings](https://github.com/aejh/UKBinCollectionData/tree/develop-lineendings) fork I:

 1. Created `.gitattributes` (copied from [here](https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/#a-simple-gitattributes-config)):
 ```
# We'll let Git's auto-detection algorithm infer if a file is text. If it is,
# enforce LF line endings regardless of OS or git configurations.
* text=auto eol=lf

# Isolate binary files in case the auto-detection algorithm fails and
# marks them as text files (which could brick them).
*.{png,jpg,jpeg,gif,webp,woff,woff2} binary
```
 2. Ran `git add --renormalize .`
 3. Commit.

This produced a large change (all CRLF files becoming LF), but now can be checked and works with Linux and MacOS, with standard `#!/usr/bin/env python` shebangs. The blog I copied the .gitattributes from states (emphasis mine):

 >That's what text=auto does in the config above—it tells git to apply its auto-detection algorithm to determine whether a file is a text file. Then, eol=lf tells git to enforce LF line endings for text files on **both checkout and commit**. This should work well on both Windows and Linux since a majority of cross-platform text editors support LF."

What I'm not not sure about is whether you (Windows devs) have a preference/problem with forcing LF on your checkouts. I don't give a hoot :grin: but it'd be a bit daft if it breaks for someone else and I'm not mad keen on "should work well". From the [docs](https://git-scm.com/docs/gitattributes#_text):
> If you want to ensure that text files that any contributor introduces to the repository have their line endings normalized, you can set the text attribute to "auto" for all files.

so perhaps leave the `eol=lf` off? Or just see if my fork checks out and behaves fine on your Windows setup (if the docs are right, you'll end up with LF files, no line end mangling happens at all). If it works, create that .gitattributes, run `git add --renormalize .`, commit in each of your branches, profit! Or something like that.

**Comment by robbrad** [comment]
Is this still an issue? can we validate? Thanks !

**Comment by robbrad** [comment]
closing for now
