### ISSUE TITLE
Request to Add Harrogate Borough Council

### ISSUE THREAD

**Issue by MystifiedMeat** [robbrad/UKBinCollectionData#320]
### Name of Council

Harrogate Borough Council

### Example Postcode

HG2 7SG

### Additional Information

You enter your postcode at https://secure.harrogate.gov.uk/inmyarea then select your house from the list of addresses to get to a url with a uprn: https://secure.harrogate.gov.uk/inmyarea/Property/?uprn=100050414309

**Comment by OliverCullimore** [comment]
Addressed by #321
