### ISSUE TITLE
Add Home Assistant Custom Component to HACS

### ISSUE THREAD

**Issue by OliverCullimore** [robbrad/UKBinCollectionData#327]
Make the custom component installable via HACS.

The docs [here](https://hacs.xyz/docs/publish/start/) detail what's necessary to do for this.

As a start, I'll submit a PR to add the hacs.json file and README instructions for installing via the HACS custom repositories method.

Ideally, we eventually could submit for this to be [included](https://hacs.xyz/docs/publish/include/) in the HACS default repository making installation via HACS as simple as just searching for the component and clicking download.

**Comment by robbrad** [comment]
FYI @OliverCullimore https://github.com/hacs/default/pull/2255

**Comment by robbrad** [comment]
Pending HACS

**Comment by robbrad** [comment]
We are now officially back in HACS

@OliverCullimore and @dp247 

We might need to update our docs
