### ISSUE TITLE
Bolton Council Broken

### ISSUE THREAD

**Issue by rjosborne** [robbrad/UKBinCollectionData#329]
Apologies if I am missing something, but I can't work out how to get the newly added home assistant component to create any sensors / entities?

I have gone through the install process with the following settings, so I believe I've done it right:

- Installed the component via the HACS instructions in the readme
- Location: Home
- Council: Bolton Council
- UPRN: xxxxxxxxxx|NN STREET NAME, BOLTON, ZZZ ZZZ

The UPRN is following the instructions and format on the wiki, which in turn points to [this issue](https://github.com/robbrad/UKBinCollectionData/issues/272)

The config flow accepts my various inputs, completes and shows a service entry, but then it just says "No devices or entities"

**Comment by OliverCullimore** [comment]
Doesn't appear to be an issue with the custom component itself but actually the Bolton Council scraper erroring as seen by the feature test failing https://robbrad.github.io/UKBinCollectionData/3.11/913/#suites/98d3104e051c652961429bf95fa0b5d6/cbdd1e6e0bb987a3/

Looking into if we can fix it now

**Comment by OliverCullimore** [comment]
Updating HACS component doesn't appear to have resolved this, will try to investigate further, possibly the Python library doesn't get updated as part of that.

**Comment by OliverCullimore** [comment]
Released the Python library won't be updated until we create a release, opened #332 to achieve that, once this is merged the HACS integration should show another update and on restart after installing the update the Bolton Council fix should come into effect.

**Comment by OliverCullimore** [comment]
@rjosborne if you can update via the component in HACS, restart Home Assistant then delete and re-add the integration and see if the entities appear within a few minutes

**Comment by rjosborne** [comment]
Still doesn’t seem to be working.

**Comment by OliverCullimore** [comment]
@rjosborne it looks like you managed to find another broken council which I've just submitted a PR for to fix it so thank you for that.

I believe I've narrowed down the issue you're having with Bolton (updating the component still isn't updating the Python library unless we change the requirements to specify a different version to install which I'm working on a fix for at present).

In the meantime would you be able to give BCP Council a go with the UPRN 100040810214 as I've tested that one's working via HACS and see if that comes up with entities to double-check it's just that you're missing the updated library?

**Comment by rjosborne** [comment]
Yes - BCP council worked straight away so at least you’re looking in the right place.

thanks for all the help!

**Comment by OliverCullimore** [comment]
@rjosborne I'm hoping the merge of #341 will trigger a release which has all the appropriate files updated so when the HACS component is updated to it, it also updates the Python library and therefore includes the Bolton fix

I'll drop another update here once that's been merged and I've checked all the files were updated successfully
