### ISSUE TITLE
Automate creating releases

### ISSUE THREAD

**Issue by OliverCullimore** [robbrad/UKBinCollectionData#333]
@robbrad @dp247 FYI

Would it be worth us setting up a new GitHub action to create and publish releases on a schedule (maybe nightly) if any changes to the `uk_bin_collection/uk_bin_collection` folder have been made since the last release? (I think that should cover any changes that would affect the Python library but feel free to correct me if not)

Just aware that I think until we create a release the custom component won't see any changes that have been merged since the last one.

**Comment by robbrad** [comment]
@OliverCullimore what about using some thing like https://python-poetry.org/docs/cli/#version bump on merge to master?

**Comment by OliverCullimore** [comment]
@robbrad That looks interesting

I've had a look to see if we could automate passing in patch vs minor etc and discovered [python-semantic-release](https://python-semantic-release.readthedocs.io/en/latest/index.html) which can "detect what the next version of the project should be based on the commits" so as long as we started prefixing commits with "feat:", "fix:" or "docs:" etc it should be able to auto-increment by patch and minor versions automatically for us.

(I'm imagining fix will trigger a patch, docs won't trigger anything and feat will trigger a new minor version?)

**Comment by OliverCullimore** [comment]
@robbrad Just sharing my further thoughts on this, we might be able to update release.yml to be run on push/a schedule and to do the following:

1. Checkout repo (passing a Personal Access Token to the token field to allow pushes to master for the version number amend)
1. Setup Python
1. Install poetry
1. Install pip, wheel & twine
1. Run make install
1. Bump pyproject.toml version using [python-semantic-release](https://python-semantic-release.readthedocs.io/en/latest/index.html based on commits since the last release then committing and pushing the change to master (if possible, otherwise we can go the create PR route)
1. Build and publish package to PyPi

Would that work for you?

**Comment by robbrad** [comment]
That sounds great! Must be other other repos doing something similar? Maybe there is a GH action for this?

**Comment by robbrad** [comment]
Nice work @OliverCullimore
