### ISSUE TITLE
Wakefield

### ISSUE THREAD

**Issue by nmcrae85** [robbrad/UKBinCollectionData#339]
Is this council still not supported?

**Comment by dp247** [comment]
I haven't been back to it - so unless it has changed, the answer is no, still not supported

**Comment by nmcrae85** [comment]
Just listed on the supported page so didnt know if its changed. It does seem like they have changed the page a bit not sure if the backend has also changed. Are you able to do a little test when/ if you get some time or im happy to do it if you can instruct me :)

**Comment by OliverCullimore** [comment]
Taking a look at this one we may now be able to use the approach we use for North Lanarkshire Council where you navigate to the page yourself then pass the URL into the script.

@nmcrae85 can you give the below URL a go and see if it just loads for you to prove they're not using anything IP/session based still and then we can have a look at updating the council's method for you?

https://www.wakefield.gov.uk/where-i-live/?uprn=63035490&a=115%20Elizabeth%20Drive%20Castleford%20WF10%203RR&usrn=41801243&e=445418&n=426091&p=WF10%203RR

**Comment by nmcrae85** [comment]
Do you want me to apply this to the HACS config or just via a web browser? Sorry just checking.

**Comment by nmcrae85** [comment]
This is my URL - https://www.wakefield.gov.uk/where-i-live/?uprn=63161064&a=Old%20Hall%20Gardens%20Heath%20Wakefield%20WF1%205SL&usrn=41801827&e=435185&n=420116&p=WF1%205SL

**Comment by OliverCullimore** [comment]
@nmcrae85 I spotted the captcha issue in the end.

There's currently some issues with the automated releases so HACS and PyPi both won't currently include the Wakefield fix quite yet only if you clone the repo and use collect_data.py from a terminal.

I'll drop an update on here once a successful release is out for HACS and PyPi so you can simply update via HACS and re set up Wakefield.

**Comment by nmcrae85** [comment]
Is there a guide for this? Im not sure im following the documentation correclty with copying the files into the custom_components folder... I have sensor.py and other files not collect_data.py
