### ISSUE TITLE
Icon for Home Assistant Integrations Page

### ISSUE THREAD

**Issue by holdestmade** [robbrad/UKBinCollectionData#354]
Missing Icon for the integration.

I have created this one and can do a PR for it in HA if its acceptable ?

![uk bin dates](https://github.com/robbrad/UKBinCollectionData/assets/13977244/ecd18a39-fb6a-477e-8fee-a73be7b46d29)

**Comment by robbrad** [comment]
@holdestmade so cool!!

**Comment by holdestmade** [comment]
https://github.com/home-assistant/brands/pull/4749

**Comment by holdestmade** [comment]
It's been merged so I'll close this
