### ISSUE TITLE
Knowsley Metropolitan Borough Council

### ISSUE THREAD

**Issue by c-r-s** [robbrad/UKBinCollectionData#355]
### Name of Council

Knowsley Metropolitan Borough Council

### Example Postcode

L369UX

### Additional Information

https://knowsleytransaction.mendixcloud.com/link/youarebeingredirected?target=bincollectioninformation

**Comment by OliverCullimore** [comment]
Address with bin collections available: 2 ALTMOOR ROAD HUYTON L36 3UY
