### ISSUE TITLE
HA Component: Bolton Council

### ISSUE THREAD

**Issue by bobat-h** [robbrad/UKBinCollectionData#356]
Hi,
After adding the integration in devices and after setting my council and location I get this window when clicking the configuration option. It’s not showing any devices or entities. What do I need to do?

![IMG_0006](https://github.com/robbrad/UKBinCollectionData/assets/95458229/23fe2182-e74f-41d9-a9c2-e0d314328335)

**Comment by bobat-h** [comment]
I’m using Bolton Council

**Comment by OliverCullimore** [comment]
@bobat-h Testing this with Home Assistant 2023.9.3 it seems to be working with our test UPRN value of:
100010886949|21 HEATON AVENUE, BOLTON, BL1 5PQ

Can you confirm you entered the UPRN in this format? (UPRN|ADDRESS)

**Comment by bobat-h** [comment]
Hi,
It’s working now, I missed the step of adding my physical address to the UPRN

Thanks

**Comment by OliverCullimore** [comment]
Amazing, happy to help 🙂
