### ISSUE TITLE
Request to add Rhondda Cynon Taff

### ISSUE THREAD

**Issue by production-raps-adam** [robbrad/UKBinCollectionData#357]
### Name of Council

Rhondda Cynon Taff

### Example Postcode

CF72 9JD

### Additional Information

https://www.rctcbc.gov.uk/EN/Resident/RecyclingandWaste/RecyclingandWasteCollectionDays.aspx - bin collection

https://www.rctcbc.gov.uk/EN/Contactus/OnlineServices.aspx - Generic services

Been trying to find any form of web API to pull services from but havent managed to find anything myself just yet.

**Comment by dp247** [comment]
Would you be okay with having only the next dates for each collection, or would you rather have the entire list?

**Comment by dp247** [comment]
@production-raps-adam This should do the trick!
