### ISSUE TITLE
East Lindsey District Council

### ISSUE THREAD

**Issue by kieran5566** [robbrad/UKBinCollectionData#363]
### Name of Council

East Lindsey District Council

### Example Postcode

LN4 4SY

### Additional Information

https://www.e-lindsey.gov.uk/article/6714/Your-Waste-Collection-Days

**Comment by OliverCullimore** [comment]
Working address: Raf Coningsby, Old Boston Road, Coningsby, LINCOLN, Lincolnshire, LN4 4SY

**Comment by OliverCullimore** [comment]
Looks to be the same/similar system to #362

**Comment by robbrad** [comment]
![image](https://github.com/robbrad/UKBinCollectionData/assets/6122503/668299cc-d269-416a-ae8f-bada5e0c82a3)

#191 

No longer working looks like the council has moved to PDF
