### ISSUE TITLE
Integration not loading after latest update 

### ISSUE THREAD

**Issue by Yorkie71** [robbrad/UKBinCollectionData#365]
Since updating to v0.13.1 the integration fails to load with the following log errors.

Logger: homeassistant.setup
Source: setup.py:185
First occurred: 19:38:54 (1 occurrences)
Last logged: 19:38:54

Setup failed for custom integration uk_bin_collection: Requirements for uk_bin_collection not found: ['uk-bin-collection>=0.13.1'].
![Screenshot_20231015-194118](https://github.com/robbrad/UKBinCollectionData/assets/9529010/cc1a1186-fba7-4ed2-8d3c-d22c5d1feaa9)
![Screenshot_20231015-194038](https://github.com/robbrad/UKBinCollectionData/assets/9529010/a18b0ad0-152c-41ba-99b8-22094d0751ef)

Adding a service also fails.
![Screenshot_20231015-194604](https://github.com/robbrad/UKBinCollectionData/assets/9529010/bfed8e11-2005-4e0a-acb4-237cf0713cdf)

Hopefully this is a simple issue as this was a very useful integration.

**Comment by OliverCullimore** [comment]
@Yorkie71 can you please confirm your home assistant version?

**Comment by Yorkie71** [comment]
@OliverCullimore sure. Here you go.
![Screenshot_20231015-195550](https://github.com/robbrad/UKBinCollectionData/assets/9529010/ee60b833-0ec8-443d-bc0c-55ab36446b4b)

**Comment by Yorkie71** [comment]
I've just redownloaded and now got 0.31.2 but still got the same error I'm afraid.
`Logger: homeassistant.setup
Source: setup.py:185
First occurred: 21:15:49 (1 occurrences)
Last logged: 21:15:49

Setup failed for custom integration uk_bin_collection: Requirements for uk_bin_collection not found: ['uk-bin-collection>=0.13.2'].`

**Comment by OliverCullimore** [comment]
I'm also seeing the same.

There looks to be a conflict with the urllib3 we're trying to request and the version home assistant requires which @RealGandy's logs showed on #347 who's now seeing the same.

I'm submitting another PR now which may fix this but I'm unable to test until it's released as the Home Assistant dev container unhelpfully isn't running into the same issues.

**Comment by Yorkie71** [comment]
Thanks for the update. Sounds promising that you have found the issue. I'll sit tight and wait for the update. If you can remember to remind me that it's the green bin on Wednesday, that would be great. 🤣

**Comment by OliverCullimore** [comment]
@Yorkie71  the latest version appears to be working for me now if you can update and give it another go

**Comment by Yorkie71** [comment]
Hi @OliverCullimore thanks for the note. I just checked and yes, all looks back to normal. Thanks for looking at this and thanks for a really useful integration. Perfect timing for the fix too. Just in time for the bin day alert! 🤣
![image](https://github.com/robbrad/UKBinCollectionData/assets/9529010/ba7532d4-0645-4329-823f-bfbe40cf92d1)
