### ISSUE TITLE
Replace East Northamptonshire Council with North Northamptonshire Council

### ISSUE THREAD

**Issue by dp247** [robbrad/UKBinCollectionData#378]
### Name of Council

East Northamptonshire Council

### Issue Information

Investigating the East Northamptonshire Council failure and found that North Northamptonshire Council's website is now used for bin collections. This will need replacing at some point.

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by dp247** [comment]
NNC uses the following URL:
`https://cms.northnorthants.gov.uk/bin-collection-search/calendarevents/<uprn>/yyyy-mm-dd <from>/yyyy-mm-dd <to>`
e.g:
`https://cms.northnorthants.gov.uk/bin-collection-search/calendarevents/100031021318/2023-10-17/2023-10-01`

This returns JSON data that looks half broken, but I think the date value is an epoch for collection, and the color value is the bin type. It's the only thing I could find whilst scraping.

**Comment by dp247** [comment]
I think `"color":"rgb(192,192,192)"` is the recycling bins and `"color":"rgb(0,0,0)"` is general refuse. Epoch dates are not ordered either, but that can be arranged.

**Comment by joxta** [comment]
Forgive me, but I don't really understand how git works for pulls and merges etc, but I found this project whilst looking into why my own scraper for North Northants Council had stopped working. I modified the East Northants one and got it working as attached:

[NorthNorthamptonshireCouncil.txt](https://github.com/robbrad/UKBinCollectionData/files/13196755/NorthNorthamptonshireCouncil.txt)

**Comment by robbrad** [comment]
@dp247 - you got this one? otherwise ping me and Ill change

**Comment by dp247** [comment]
> @dp247 - you got this one? otherwise ping me and Ill change

Feel free @robbrad - I'm flying back from Europe most of today, so if you're game for it then it's all yours
