### ISSUE TITLE
Buckinghamshire Council

### ISSUE THREAD

**Issue by felixnurse** [robbrad/UKBinCollectionData#38]
name: Council Request
description: Request for a council to be added to the repository
labels: ['Class: enhancement']

body:
    - type: input
      id: council
      attributes:
          label: Buckinghamshire
          description: Buckinghamshire - Chiltern Area
          placeholder: e.g. Huntingdon District Council
      validations:
          required: true
    - type: input
      id: postcode
      attributes:
          label: Example Postcode
          description: Please provide and example postcode for the area
          placeholder: e.g. HP14 3NL
      validations:
          required: true
    - type: textarea
      id: extra
      attributes:
          label: Additional Information
          description: The actual site is a Chiltern.gov site which is a child of the main Buckinghamshire site.
          placeholder: (https://www.chiltern.gov.uk/collection-dates) - It seems to take a form submission with a session ID, which is redirected and provides results back in an HTML format. The table at the bottom of the returned page lists the next collection date for each bin type. Thank you!
![Capture](https://user-images.githubusercontent.com/49407043/148702339-c6dfd2b3-7b64-4c65-bfe5-2948276cc59c.PNG)

**Comment by ZackaryH8** [comment]
There seems to be an issue with how you have used the issue template
