### ISSUE TITLE
Central Bedfordshire council request 

### ISSUE THREAD

**Issue by LouisCoates** [robbrad/UKBinCollectionData#387]
### Name of Council

Central Bedfordshire 

### Example Address/Postcode

SG19 2UP

### Additional Information

Website for collection dates:

https://www.centralbedfordshire.gov.uk/info/163/bins_and_waste_collections_-_check_bin_collection_days

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by simondrake** [comment]
@robbrad @dp247 @LouisCoates - this can be closed now, I believe.

**Comment by LouisCoates** [comment]
Works excellent! Thanks!
