### ISSUE TITLE
Bexley @Home app not working, what is solution? 

### ISSUE THREAD

**Issue by ArnSu** [robbrad/UKBinCollectionData#388]
### Name of Council

Bexley council 

### Issue Information

@Home app (android) not working anymore. No address coming up after entering postcode.
What is the solution?
Post code used DA16 3BJ. 

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by robbrad** [comment]
Will be fixed as part of #191 
and PR https://github.com/robbrad/UKBinCollectionData/pull/499

**Comment by ArnSu** [comment]
Great news. Thank you!
