### ISSUE TITLE
Request for Mid and East Antrim Borough Council

### ISSUE THREAD

**Issue by xbmctim** [robbrad/UKBinCollectionData#390]
### Name of Council

Mid and East Antrim Borough Council

### Example Address/Postcode

BT42 2EU

### Additional Information

Link to the council Bins and recycling webiste
https://www.midandeastantrim.gov.uk/resident/waste-recycling
The council is available on the Bin-Ovation App
https://www.midandeastantrim.gov.uk/resident/waste-recycling/bin-ovation-app/

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by PhilDB-cloud** [comment]
Attempting to do this here https://github.com/PhilDB-cloud/UKBinCollectionData.  It is working standalone but needs to be set up for importing to HomeAssistant and testing.

**Comment by PhilDB-cloud** [comment]
@xbmctim this is now complete.  check your address on the website first and use it in the integration.
