### ISSUE TITLE
Adding Chelmsford doesn't create entities

### ISSUE THREAD

**Issue by Johnyb62** [robbrad/UKBinCollectionData#393]
### Home Assistant Version

2023.10.5

### Installation Method

Using HACS

### Name of Council (if relevant)

Chelmsford Council

### Issue Information

I’m able to add my council (chelmsford) and the URL for my property - but beneath the integration it shows ‘no devices or entities’.

Here's a test URL for a random property in my area that could be used for testing:-
https://www.chelmsford.gov.uk/myhome/?entry[655e95fb-5f84-4d1b-ab65-878a2f3e3ce4]=14155765

I’m using HA core (Home Assistant 2023.10.3) docker on an Unraid server.

Believe this could be same as this issue - https://github.com/robbrad/UKBinCollectionData/issues/381
For testing purposes I was also able to add North Lanarkshire (which correctly created entities)

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] If trying to add a specific council, I've checked it is listed as working at https://robbrad.github.io/UKBinCollectionData/3.11/
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by OliverCullimore** [comment]
@Johnyb62 it looks like this one's more of a general issue with the council changing their site that hopefully this PR will fix
