### ISSUE TITLE
Refuse and recycling the wrong way round

### ISSUE THREAD

**Issue by cstosgale** [robbrad/UKBinCollectionData#394]
### Name of Council

Harrogate Borough Council

### Issue Information

I’ve noticed that in the latest version the date for refuse and recycling are the wrong way round. So my recycling gets collected on a Wednesday and refuse on a Thursday, but the sensors are reporting the dates the opposite way round.

I’m not sure if this issue is specific to Harrogate or affects other councils.

I’ve  deleted and re-created my sensors but that hasn’t resolved the issue

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by cstosgale** [comment]
Apologies, it looks like this is fixed in the current version!

**Comment by cstosgale** [comment]
It does appear this is still happening. I have now deleted and re-created the sensors again, following it happening, and low and behold, the following happens:
- Once the current date for a collection has passed, each sensor reports the incorrect day (so Wednesday for refuse, Thursday for recycling) for exactly one day.
- The next day they swap round again, and the correct day is reported:

![image](https://github.com/robbrad/UKBinCollectionData/assets/39710503/8486ff4c-5ab1-4b30-b0cc-420416c3f79d)
![image](https://github.com/robbrad/UKBinCollectionData/assets/39710503/86ea3935-71f3-485f-abbd-6f2e39921209)

**Comment by dandantheitman** [comment]
I've added a pull request to get rid of the numerical indexes and use a bin_type keyed disctionary to store and access the data. It's working for me locally and should make sure data is always applied to the correct entity.

https://github.com/robbrad/UKBinCollectionData/pull/475
