### ISSUE TITLE
South Tyneside Council

### ISSUE THREAD

**Issue by Evildave3** [robbrad/UKBinCollectionData#4]
Please could South Tyneside be added?

https://www.southtyneside.gov.uk/article/33352/Bin-collection-dates

Example post code: NE33 3LH

**Comment by ZackaryH8** [comment]
[Postman Collection](https://www.postman.com/payload-physicist-86737988/workspace/bin-collection-api/collection/16208242-8d0974d7-e83c-4a27-b49a-59229974a272)
