### ISSUE TITLE
Adding Calderdale Council doesn't create entities

### ISSUE THREAD

**Issue by OliverCullimore** [robbrad/UKBinCollectionData#402]
Thank you for adding this so soon! The only issue is it doesn't seem to pull any entities from the site when you enter: name, council, UPRN NO. & postcode (Given as AB12 3CD format) Any ideas?

_Originally posted by @LostkingZ in https://github.com/robbrad/UKBinCollectionData/pull/398#issuecomment-1785062617_

**Comment by OliverCullimore** [comment]
@LostkingZ can you confirm using the test UPRN and postcode below also doesn't generate entities?

UPRN: `010035034598`

Postcode: `OL14 7EX`

**Comment by LostkingZ** [comment]
Hi, 

I'm sorry for not getting back to you sooner.

Yes that UPRN and Postcode work however any other UPRN and the same postcode doesn't work. Do you have any idea why that could be? 

How did you pick that UPRN number? was it random based on the postcode?

**Comment by robbrad** [comment]
Calderdale will be moved to Selenium as its currently very flaky on connection tries - see #499 and #191 

@OliverCullimore FYI

**Comment by robbrad** [comment]
Tested this - its working in HA
