### ISSUE TITLE
Replace schema files

### ISSUE THREAD

**Issue by OliverCullimore** [robbrad/UKBinCollectionData#406]
We can look to replace the schema files per council with a single one

We can possibly utilise "minItems" to check at least one entry exists in the bins dictionary

We can also use [regular expressions](https://json-schema.org/learn/miscellaneous-examples#regular-expression-pattern) to validate the collectionDate of the entries

**Comment by robbrad** [comment]
I did a quick sanity check and most of the Schemas are 99% the same - just bin type so I thin ka check for at least one element should be fine !

Also JSON Schema supports a date check 👍 

```
"date": {
  "type": "string",
  "format": "date"
}
```

**Comment by robbrad** [comment]
This issue will also fix 4 of the councils currently failing schema validation in the feature tests

**Comment by robbrad** [comment]
Do you think we need the output files anymore? @OliverCullimore

**Comment by OliverCullimore** [comment]
@robbrad I guess not now we're using a common format as they were only ever for reference I thought?
