### ISSUE TITLE
Chelmsford council works initially then goes unavailable  

### ISSUE THREAD

**Issue by Johnyb62** [robbrad/UKBinCollectionData#407]
### Home Assistant Version

2023.10.5

### Installation Method

Using HACS

### Name of Council (if relevant)

Chelmsford Council

### Issue Information

After the last release fixed adding Chelmsford council which resulted in two entities being added & working.  However some time afterwards both entities are showing as ‘unavailable’
(Original case raised - https://github.com/robbrad/UKBinCollectionData/issues/393)

Here's a test URL for a random property in my area that could be used for testing:-
[https://www.chelmsford.gov.uk/myhome/?entry[655e95fb-5f84-4d1b-ab65-878a2f3e3ce4]=14155765](https://www.chelmsford.gov.uk/myhome/?entry%5B655e95fb-5f84-4d1b-ab65-878a2f3e3ce4%5D=14155765)

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] If trying to add a specific council, I've checked it is listed as working at https://robbrad.github.io/UKBinCollectionData/3.11/
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by OliverCullimore** [comment]
@Johnyb62 can you confirm if that property link is still working for you?

It shows "The requested record is no longer available" for me.

Can you confirm if you just copied that link from the other issue or generated it freshly on the council's website? (This will help us check if it's a session-based timeout or if the URL changes)

**Comment by Johnyb62** [comment]
> @Johnyb62 can you confirm if that property link is still working for you?
> 
> It shows "The requested record is no longer available" for me.
> 
> Can you also confirm if you just copied that link from the other issue or generated it freshly on the council's website? (This will help us check if it's a session-based timeout or if the URL changes)

No it doesn't now, not sure why.  Try this one, just tested it adds for me ok... 
https://www.chelmsford.gov.uk/myhome/?entry[655e95fb-5f84-4d1b-ab65-878a2f3e3ce4]=14494162

**Comment by OliverCullimore** [comment]
@Johnyb62 can you confirm if when you opened this issue this morning you just copied the URL under "Here's a test URL for a random property in my area that could be used for testing" from the previous issue you opened? Or did you go to your council's website this morning and grab it?

**Comment by Johnyb62** [comment]
Copied from previous issue. But the one added an hour ago is new via the council web site

**Comment by Johnyb62** [comment]
@OliverCullimore Is there anything else I can do to help, probably not, but let me know. Thanks.

**Comment by OliverCullimore** [comment]
@Johnyb62 Apologies I haven't had a chance to look at this one again for you

I have a feeling this one might be a session expiry issue so it might be easiest to convert this one over to using selenium to get around that

**Comment by dp247** [comment]
> @Johnyb62 Apologies I haven't had a chance to look at this one again for you
> 
> I have a feeling this one might be a session expiry issue so it might be easiest to convert this one over to using selenium to get around that

I'll have a dig into it too

**Comment by Johnyb62** [comment]
@dp247 @OliverCullimore  Happy Christmas both.  Gentle reminder to take if look if you can please.

**Comment by robbrad** [comment]
Now fixed
