### ISSUE TITLE
North East Lincolnshire

### ISSUE THREAD

**Issue by grannysmith59** [robbrad/UKBinCollectionData#41]
### Name of Council

North East Lincolnshire

### Example Postcode

DN36 4DQ

### Additional Information

https://www.nelincs.gov.uk/?s=dn36+4dq

**Comment by grannysmith59** [comment]
Once a UPRN is obtained, a permanent link for it may be generated
Thanks in advance

**Comment by dp247** [comment]
@grannysmith59 thanks for the tip! It was really helpful in finding out the best way to scrape this.
