### ISSUE TITLE
Council Request - Mid Suffolk Council

### ISSUE THREAD

**Issue by aaronchidgey** [robbrad/UKBinCollectionData#426]
### Name of Council

Mid Suffolk Council

### Example Address/Postcode

10 Lindsey Way

### Additional Information

https://bmsdchosting.net/waste-services/mid-suffolk-bin-collection/

Have tested but it seems only to accept address and not postcode.

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by dp247** [comment]
Apparently this was completed by #77
