### ISSUE TITLE
Council request for reading please

### ISSUE THREAD

**Issue by boxofrabbits** [robbrad/UKBinCollectionData#430]
### Name of Council

Reading Borough Council

### Example Address/Postcode

RG1 2NU

### Additional Information

https://www.reading.gov.uk/bin-calendar/

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by M0LTE** [comment]
Address 27, RG30 4JT is an example with green waste collection service currently paid for

**Comment by M0LTE** [comment]
A GET to https://api.reading.gov.uk/api/collections/<uprn> fetches you a nice chunk of JSON

An example UPRN: 310032783

**Comment by boxofrabbits** [comment]
Hey guys, these seems to have broken.

**Comment by M0LTE** [comment]
No, the council website is just returning 500 Internal Server Error now.

The 'When is my bin collected' page on their website, which uses this API, is also broken.
