### ISSUE TITLE
Request: London Borough of Redbridge

### ISSUE THREAD

**Issue by ncodee** [robbrad/UKBinCollectionData#431]
### Name of Council

London Borough of Redbridge

### Example Address/Postcode

54 Eastern Avenue, Ilford, IG1 5AA (Coverage IG1-11)

### Additional Information

https://my.redbridge.gov.uk/RecycleRefuse

Website uses some sort of Geolocation API to lookup postal address in the borough.

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by ncodee** [comment]
Any updates?

**Comment by robbrad** [comment]
This has been released
