### ISSUE TITLE
Add bin collection South Kesteven

### ISSUE THREAD

**Issue by marcusb3495** [robbrad/UKBinCollectionData#439]
### Name of Council

South Kesteven District Council 

### Example Address/Postcode

PE68BL

### Additional Information

https://www.southkesteven.gov.uk/bins-street-care-recycling-and-commercial-waste/find-your-bin-collection-day

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by robbrad** [comment]
https://pre.southkesteven.gov.uk/binsearch.aspx
