### ISSUE TITLE
Bradford Council Request

### ISSUE THREAD

**Issue by purp23** [robbrad/UKBinCollectionData#442]
### Name of Council

Bradford

### Example Address/Postcode

BD13 2NB

### Additional Information

https://onlineforms.bradford.gov.uk/ufs/collectiondates.eb?ebd=0&ebp=30&ebz=1_1701123159341

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by dp247** [comment]
Ooooh, someone local to me - finally!

**Comment by jimmygulp** [comment]
Also from Bradford and had some time on my hands, so have knocked together what I believe is a working script to get the next Green/Grey bin day. I may add upcoming dates if folks want it.

I'm not happy about the HTML in the council page, it disturbs me!

Just need to fork/update/merge/pull request it. Should just need to take the UPRN (form FindMyAddress) as that's what the council site uses (when you click on your address).

**Comment by serversonic** [comment]
That's great, I had started looking at it (and thought I'd spotted another council that used a similar system) but I'm happy to test it out.

**Comment by jimmygulp** [comment]
I've worked out forks & branches and pull requests, so it's just waiting to be merged now, assuming I've done it all right!

**Comment by serversonic** [comment]
Installed this via HACS on Yunohost and it was complaining about dumper not being installed, which I suspect is a leftover from testing. Commented it out and cleared __pycache__ and it works.

**Comment by jimmygulp** [comment]
My apologies, I missed taking that out. I've updated the file and there's a pull request so it should get fixed when the next merge gets done.

**Comment by serversonic** [comment]
I'm getting this in HA and on the command  line from the latest release:
```
  File "/home/simong/code/bins/UKBinCollectionData/uk_bin_collection/uk_bin_collection/collect_data.py", line 127, in <module>
    run()
  File "/home/simong/code/bins/UKBinCollectionData/uk_bin_collection/uk_bin_collection/collect_data.py", line 123, in run
    print(app.run())
          ^^^^^^^^^
  File "/home/simong/code/bins/UKBinCollectionData/uk_bin_collection/uk_bin_collection/collect_data.py", line 96, in run
    return self.client_code(
           ^^^^^^^^^^^^^^^^^
  File "/home/simong/code/bins/UKBinCollectionData/uk_bin_collection/uk_bin_collection/collect_data.py", line 115, in client_code
    return get_bin_data_class.template_method(address_url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simong/code/bins/UKBinCollectionData/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 78, in template_method
    bin_data_dict = self.parse_data(
                    ^^^^^^^^^^^^^^^^
  File "/home/simong/code/bins/UKBinCollectionData/uk_bin_collection/uk_bin_collection/councils/BradfordMDC.py", line 92, in parse_data
    "type": bin_type,
            ^^^^^^^^
UnboundLocalError: cannot access local variable 'bin_type' where it is not associated with a value
```

**Comment by serversonic** [comment]
Deleted my comment, I'd got my UPN wrong, but the script doesn't handle having no variable called bin_type, which you get if you're not right sharp.
