### ISSUE TITLE
Leeds Council doesnt support brown bins

### ISSUE THREAD

**Issue by Frooodle** [robbrad/UKBinCollectionData#447]
### Name of Council

Leeds City Council

### Issue Information

When running script i only get output for black and green bins, no brown

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by dp247** [comment]
This _should_ be fixed in the LeedsV3 branch when I push it. It's very slow (#141) atm and was the first scraper I wrote, so hoping the experience will speed it up a bit 😆.

**Comment by dp247** [comment]
Could you provide the settings you're using (or one nearby)? Also, do the brown bin collections show on the council site?

**Comment by Frooodle** [comment]
Ls13 1rd.  


House #1 

![Screenshot_20231129-073015.png](https://github.com/robbrad/UKBinCollectionData/assets/77850077/aa99b3d4-046d-4170-8059-eeec2711fd04)
