### ISSUE TITLE
West Lindsey District Council

### ISSUE THREAD

**Issue by cadwizzard** [robbrad/UKBinCollectionData#474]
### Name of Council

West Lindsey District Council

### Example Address/Postcode

LN8 2AR

### Additional Information

Entering a postcode and choosing a name here allows to find the info and download the calendar:
https://www.west-lindsey.gov.uk/bins-waste-recycling/find-your-bin-collection-day

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by cadwizzard** [comment]
Sounds about right for that council!
Can you work with it?

**Comment by skelt0** [comment]
> Sounds about right for that council!
> 
> Can you work with it?
> 
> 

Oh yeah for sure it's definitely possible
