### ISSUE TITLE
Dartford Council

### ISSUE THREAD

**Issue by Muncee** [robbrad/UKBinCollectionData#476]
### Name of Council

Dartford Borough Council 

### Example Address/Postcode

DA9 9YS

### Additional Information

https://windmz.dartford.gov.uk/ufs/WS_CHECK_COLLECTIONS.eb?ebd=0&ebp=10&ebz=2_1702120613704

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by skelt0** [comment]
This UX is absolutely legendary. 

<img width="1153" alt="image" src="https://github.com/robbrad/UKBinCollectionData/assets/16990151/8c37c611-55ce-45e0-bc74-ec2f696c03af">

❗️I can't seem to get the example postcode to give me any bin data from this form. 

<img width="970" alt="image" src="https://github.com/robbrad/UKBinCollectionData/assets/16990151/d66f29ac-99a5-4820-9f7f-8ade209219ab">

**Comment by dp247** [comment]
> This UX is absolutely legendary.

What a terrible day to have eyes

**Comment by Muncee** [comment]
DA9 9YX

This one shows it... Yes it's not fun to use manually!

**Comment by robbrad** [comment]
https://windmz.dartford.gov.uk/ufs/WS_CHECK_COLLECTIONS.eb?UPRN=010094157511

No need for Selenium on this one - working on this now
