### ISSUE TITLE
Request for new forest council

### ISSUE THREAD

**Issue by TomForeman86** [robbrad/UKBinCollectionData#484]
### Name of Council

New Forest

### Example Address/Postcode

SO41 0GJ

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by duckfullstop** [comment]
I did spend a little bit of time trying to figure this one out a while ago, but came out a bit blank. Looks like it heavily relies on a server side session, with 3 required steps:

1) User navigates to `https://forms.newforest.gov.uk/ufs/FIND_MY_COLLECTION.eb` - 302 redirect to `FIND_MY_COLLECTION.eb?ebd=0&ebz=[random_numerical_string]` and `JSESSIONID` cookie
2) User inputs postcode into `CTRL:1:_:A` form field and POST to above new URL - 302 redirect to same URL as GET request but new page contents
3) User selects UPRN from dropdown by address and POST to same new URL - 302 redirect to same URL as GET request but scrapable bin information

That's a very brief synopsis - removing `eb` or `ebz` at any point yeets the session.

**Comment by robbrad** [comment]
Selenium required for this one

**Comment by robbrad** [comment]
Proving pretty difficult this one as the page in Selenium just comes up with ERR_TOO_MANY_REDIRECTS

**Comment by robbrad** [comment]
Sorted  !
