### ISSUE TITLE
Issue with Guildford

### ISSUE THREAD

**Issue by TomForeman86** [robbrad/UKBinCollectionData#485]
### Name of Council

Guildford

### Issue Information

I've not tested it in python but in the code for Guildford Council the FWUID value is pre-defined in the code rather than being retrieved dynamically from the council website.

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by robbrad** [comment]
Tracking against #191
