### ISSUE TITLE
Home Assisant - Not working for Leeds Council Since New Release. 

### ISSUE THREAD

**Issue by vishnurpatel** [robbrad/UKBinCollectionData#493]
### Home Assistant Version

2023.12

### Installation Method

Using HACS

### Name of Council (if relevant)

Leeds

### Issue Information

Was working until i updated the HACS integration (UkBinCollection)
looking at the code i assume its because we have moved to used either UPRN or selenium? 

i tried to install a previous version but dosent seem to be a supported feature with this add on.

Repo: try and use Leeds council returns 0 entities. 

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] If trying to add a specific council, I've checked it is listed as working at https://robbrad.github.io/UKBinCollectionData/3.11/
- [x] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by vishnurpatel** [comment]
Note to self: Dont not update if everything is working fine

**Comment by robbrad** [comment]
@vishnurpatel the previous version was taking 3-4 minutes to download the ~150meg csv. We have been looking for ways to reduce this as a long standing issue.

Are you able to get this working with the new changes?

**Comment by robbrad** [comment]
Hold that thought - there is a bug in headless mode. Working on the fix now

**Comment by robbrad** [comment]
Reopening to with for @vishnurpatel confirmation.

**Comment by robbrad** [comment]
Just some more justification for this change :

We only get 2000 free minutes of GitHub actions running time per month - without reducing action time we were up to 30 mins per pipeline run - and id like to keep the project free.

@dp247 / @OliverCullimore FYI : https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions

**Comment by vishnurpatel** [comment]
Still having issues after updating. 
(last night when i logged the bug, i could still get a Manchester UPRN to work.
but Leeds now seems to be dead (providing a UPRN, Postcode & House no. as All are now required)

**Comment by dp247** [comment]
I actually installed HA Core this morning and also got no entities (I also don't understand HA words), but there's also no place to put the webdriver URL

**Comment by robbrad** [comment]
Works for me with the following (picked at random)

        "uprn": "72078487",
        "postcode": "LS8 5ER",
        
        and this from input.json 
        
        "uprn": "72041563",
        "postcode": "LS9 9JU"

**Comment by robbrad** [comment]
Ahh         "web_driver": "http://selenium:4444",
 is missing from the input.json

**Comment by robbrad** [comment]
Confirmed its working now

![image](https://github.com/robbrad/UKBinCollectionData/assets/6122503/f41edf1c-5d38-49f8-aad5-c3fb46d3e1e2)

I added the following container and pointed the Selenium url at http://<server_ip>:4444

https://hub.docker.com/r/selenium/standalone-chrome

**Comment by vishnurpatel** [comment]
Resolved, had to spin up a docker running https://hub.docker.com/r/selenium/standalone-chrome
but yup, all working now.

thanks guys.

**Comment by dp247** [comment]
![image](https://github.com/robbrad/UKBinCollectionData/assets/9065463/5e8de4a5-492c-4b6f-864a-e522f8fbfc60)

Is it usual to see this message all the time, or is it my standalone-chrome?

**Comment by vishnurpatel** [comment]
> ![image](https://private-user-images.githubusercontent.com/9065463/291117037-5e8de4a5-492c-4b6f-864a-e522f8fbfc60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NjM0NDEsIm5iZiI6MTcwMjg2MzE0MSwicGF0aCI6Ii85MDY1NDYzLzI5MTExNzAzNy01ZThkZTRhNS00OTJjLTRiNmYtODY0YS1lNTIyZjhmYmZjNjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMThUMDEzMjIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTlhMmFmNzgzMDg3ODgyODhmZDA2NWE2NzJiZmVlYTU4ODNkY2RmZTk3MmY3ZThlYzE1MzI4Mjg1NjYwMzQ3NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tkQQHEQXpPPlLILZKaPJvlvC4EOn-DXE5UnpvZT5J-k)
> 
> Is it usual to see this message all the time, or is it my standalone-chrome?

Erm no, i have the same issue after rebooting. The Check My Bin Day site is up.
so not sure how its just broken again -_-  
(deleted the Leeds Council entity in Home assistant, added it again with it pointing to selenium returning 0 entities again)

could just be an issue with Leeds council, as it was working fine like two hours ago.

**Comment by vishnurpatel** [comment]
working fine for me this morning @dp247, how about you?

**Comment by vishnurpatel** [comment]
Edit, iv noticed the eneties seem to go "dead" after some time and stop reporting. 
and show the message David posted.

**Comment by vishnurpatel** [comment]
logically we should close this bug, as Leeds now works i think theres a bug for the scraper/selinum thing used for Home assistant.?

**Comment by dp247** [comment]
Your wish is my command

**Comment by robbrad** [comment]
> Edit, iv noticed the eneties seem to go "dead" after some time and stop reporting. 
> 
> and show the message David posted.
> 
> 
> 
> 
> 
> Logger: homeassistant.components.sensor
> 
> Source: helpers/entity_platform.py:361
> 
> Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
> 
> First occurred: 10:14:43 AM (3 occurrences)
> 
> Last logged: 10:18:37 AM
> 
> 
> 
> Error while setting up uk_bin_collection platform for sensor
> 
> Traceback (most recent call last):
> 
>   File "/config/custom_components/uk_bin_collection/sensor.py", line 122, in _async_update_data
> 
>     data = await self.hass.async_add_executor_job(self.ukbcd.run)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> asyncio.exceptions.CancelledError
> 
> 
> 
> During handling of the above exception, another exception occurred:
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
> 
>     self.data = await self._async_update_data()
> 
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/config/custom_components/uk_bin_collection/sensor.py", line 119, in _async_update_data
> 
>     async with async_timeout.timeout(30) as cm:
> 
>   File "/usr/local/lib/python3.11/site-packages/async_timeout/__init__.py", line 141, in __aexit__
> 
>     self._do_exit(exc_type)
> 
>   File "/usr/local/lib/python3.11/site-packages/async_timeout/__init__.py", line 228, in _do_exit
> 
>     raise asyncio.TimeoutError
> 
> TimeoutError
> 
> 
> 
> The above exception was the direct cause of the following exception:
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
> 
>     await asyncio.shield(task)
> 
>   File "/config/custom_components/uk_bin_collection/sensor.py", line 68, in async_setup_entry
> 
>     await coordinator.async_config_entry_first_refresh()
> 
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 272, in async_config_entry_first_refresh
> 
>     raise ex
> 
> homeassistant.exceptions.ConfigEntryNotReady

This looks like it could be related to the custom component in some way
