### ISSUE TITLE
Using docker image seleniarm/standalone-chromium for ARM64 Architecture

### ISSUE THREAD

**Issue by andywaddy** [robbrad/UKBinCollectionData#497]
### Home Assistant Version

2023.12.1

### Installation Method

Using HACS

### Name of Council (if relevant)

Blackburn

### Issue Information

After the Blackburn Council fix #488, I setup a seleniarm/standalone-chromium container and added the appropriate url when trying to add the integration. I'm still getting no entities showing up in HA. Does the "web_driver": "http://seleniarm:4444/" need to be added to the input.json? 
I'm running ARM64, hence the seleniarm instead of selenium. 

Cheers for the quick turnaround on the Blackburn Council issue by the way - your efforts are hugely appreciated :)

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] If trying to add a specific council, I've checked it is listed as working at https://robbrad.github.io/UKBinCollectionData/3.11/
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by robbrad** [comment]
The url in the input json is just a place folder and helps the custom component know you need to put "a url" in when you load it up into home assistant 

For your url when you running the container you gonna want something like 

http://ip-of-the-seleniarm-server:4444

Check your home assistant logs for errors

**Comment by andywaddy** [comment]
Yep, definitely an issue connection-wise:


This error originated from a custom integration.

Logger: custom_components.uk_bin_collection.sensor
Source: helpers/update_coordinator.py:300
Integration: UK Bin Collection Data (documentation, issues)
First occurred: 21:33:47 (2 occurrences)
Last logged: 21:36:43

Unexpected error fetching Home data: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff6e7fa510>: Failed to establish a new connection: [Errno 111] Connection refused'))
Unexpected error fetching Home data: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff84d57e10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.11/http/client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1332, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1041, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0xffff6e7fa510>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/uk_bin_collection/sensor.py", line 122, in _async_update_data
    data = await self.hass.async_add_executor_job(self.ukbcd.run)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 82, in run
    return self.client_code(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 69, in client_code
    return get_bin_data_class.template_method(address_url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 69, in template_method
    bin_data_dict = self.parse_data(
                    ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uk_bin_collection/uk_bin_collection/councils/BlackburnCouncil.py", line 45, in parse_data
    driver = create_webdriver(web_driver)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uk_bin_collection/uk_bin_collection/common.py", line 259, in create_webdriver
    return webdriver.Remote(command_executor=web_driver, options=options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 209, in __init__
    self.start_session(capabilities)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 293, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    response = self.command_executor.execute(driver_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py", line 300, in execute
    return self._request(command_info[0], url, body=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py", line 321, in _request
    response = self._conn.request(method, url, body=body, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/request.py", line 81, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/request.py", line 173, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 827, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 827, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 827, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff6e7fa510>: Failed to establish a new connection: [Errno 111] Connection refused'))


My first rodeo when it comes to dockers, so I'm probably doing something stupid.

**Comment by robbrad** [comment]
So had the exact same error when I put http://localhost:4444

What worked instead was http://lan-ip-of-the-docker-server:4444

**Comment by andywaddy** [comment]
Thanks for the info.

Any pointers on where to find the docker IP?

**Comment by robbrad** [comment]
Is your docker server the same as your home assistant one?

**Comment by robbrad** [comment]
btw welcome to Docker - its one of my fave technologies by far. Portainer is a good thing to get started with if you wana UI to manage your containers. 

Where ever you ran the docker command to start the seleniarm server - find out its lan IP - either with ifconfig if its linux or ipconfig if its Windows

Mine Selenium address was: http://192.168.x.x:4444

**Comment by andywaddy** [comment]
Cheers man, appreciate the pointers. 
So I'm running HA via UTM ARM64 VM. I'm using Docker Desktop to run the seleniarm server. When I do an ifconfig on it, it's returning as 172.17.0.2. 
But I stick that and a UPRN in the component fields, still no entities. Same issue with the connection issue. 
<img width="1296" alt="Screenshot 2023-12-17 at 22 21 25" src="https://github.com/robbrad/UKBinCollectionData/assets/153558711/f5078d3b-35d1-498c-8a42-ad92385b160d">

**Comment by andywaddy** [comment]
> Is your docker server the same as your home assistant one? If so whats the IP of your Home Assistant

Docker ip is: 172.17.0.2
HA ip: 192.168.1.102

**Comment by robbrad** [comment]
Docker has different network modes. Host where ports exposed run on the hosts IP address

Bridge where it exposes the ports via network address translation eg 4444 on docker to 4445 on the host.

172.17.0.2 is the internal docker network and rightfully should not be accessible from your lan. This is a docker concept that provides isolation from other networks. This is used if you use docker to run multiple containers in the same isolated network- allowing them to talk to each other.

Is docker running on the same machine as home assistant?

What happens if you go to 192.168.1.102:4444 ?

**Comment by andywaddy** [comment]
Again, cheers for the explanation. This is a bit of a learning on the job exercise!

Docker and HA are running on the same machine yes. Trying 192.168.1.102:4444 brings back nothing unfortunately. 192.168.1.102:8123 is obviously by HA but :4444 is dead.

**Comment by robbrad** [comment]
Ok few things to check - can you access the address from your web browser? Do you need to open any ports on a firewall?

From docker have you exposed the 4444 port on 0.0.0.0

**Comment by andywaddy** [comment]
Hi Rob, I'm using the following to setup a container:
docker run -d -p 4444:4444 seleniarm/standalone-chromium

I can access the Selenium grid UI via http://0.0.0.0:4444 on my browser.

I've checked the firewall and nothing causing issues there.

**Comment by robbrad** [comment]
If 0.0.0.0 is working from your browser then you're good. If 192.168.1.102:4444 is also working great.

Is HA also running in a container? My thoughts are HA can't access the lan IP the same way your browser can.

Can you get a terminal open on HA container and vm and try to nc -v 192.168.1.102 4444

**Comment by andywaddy** [comment]
HA runs inside the UTM VM. I think you may be right with it can't see the lan IP.

<img width="1029" alt="Screenshot 2023-12-18 at 17 43 20" src="https://github.com/robbrad/UKBinCollectionData/assets/153558711/71063296-6c58-4edd-8f1f-5770b586f9b4">

I used the terminal add on inside of HA and tried the command you suggested (see screenshot).

I did have to disable IPv6 network interfaces in the HA settings or the 'host internet' and 'supervisor internet' get set to false and there's no way back from it if I leave the IPv6 interfaces to 'Automatic'. Would this cause an issue?

**Comment by robbrad** [comment]
Your ideally looking for an output like this:

Connection to 192.168.10.14 22 port [tcp/ssh] succeeded!

**Comment by robbrad** [comment]
@andywaddy what network mode is your UTM VM? https://docs.getutm.app/settings-qemu/devices/network/network/

**Comment by andywaddy** [comment]
So I've been using it in the Bridged Mode and in the most part, it's been fine. I've just changed it to Emulated VLAN, and re-ran your nc -v 192.168.1.102 4444 command. It's now come back as 'Connection to 192.168.1.102 port 4444 [tcp/krb524] succeeded!', but now I can't access my HA whatsoever.

**Comment by robbrad** [comment]
> So I've been using it in the Bridged Mode and in the most part, it's been fine. I've just changed it to Emulated VLAN, and re-ran your nc -v 192.168.1.102 4444 command. It's now come back as 'Connection to 192.168.1.102 port 4444 [tcp/krb524] succeeded!', but now I can't access my HA whatsoever. 

Oh no!! Please tell me you can change it back

**Comment by andywaddy** [comment]
Haha yep, went through the different modes and Bridged is definitely the most stable/best behaved. I'm back working now but I'll have to stick with checking the damn council website every Wed night whilst I work out a solution to this! Cheers for the quick replies and trying to help though.

**Comment by robbrad** [comment]
Out of interest have you considered running Home Assistant in a Docker container or direct on the VM host? - just wondering the need for a VM

**Comment by andywaddy** [comment]
I'm only a week into HA ownership tbh. I had a MacBook Pro sat about doing nothing so just went onto the HA website and followed their instructions to get HA onto a Mac, hence running it via VM in UTM. I'm more than open to other methods...it's all an experiment at the min :)

**Comment by robbrad** [comment]
Do you have a firewall run on on the Mac?

**Comment by andywaddy** [comment]
Yep, firewall is currently running.

**Comment by robbrad** [comment]
As a test. Disable it and try the connection again. It feels like the VM is getting blocked or the connection is just not able to get to its destination

**Comment by andywaddy** [comment]
Just given it a go, still no entities created. I'll try the HA in docker container tomorrow, unless you know a way of running HA OS natively on the Mac?

**Comment by robbrad** [comment]
Go here

https://www.home-assistant.io/installation/macos

Scroll down to

Install Home Assistant Core

You'll need python on the Mac but installing direct on the make is pretty easy

**Comment by andywaddy** [comment]
Thanks man, I'll give it a run through in the morning and let you know how I get on. Thanks again for your patience/help!

**Comment by robbrad** [comment]
@andywaddy any news? - if your good ill close the issue

**Comment by andywaddy** [comment]
Hi Rob, still not working yet but got a couple of things to try this weekend hopefully. I'll keep you posted here if I find something that works 😃

**Comment by robbrad** [comment]
Closing issue - can carry on as a discussion if required. https://github.com/robbrad/UKBinCollectionData/discussions

**Comment by andywaddy** [comment]
Hi mate, all sorted. Changed my HA over onto a micro PC and ran the docker through Proxmox. All working now 😃
