### ISSUE TITLE
Uttlesford District Council Request

### ISSUE THREAD

**Issue by MankeyJohn** [robbrad/UKBinCollectionData#507]
### Name of Council

Uttlesford District Council

### Example Address/Postcode

84 Birchanger Lane, Birchanger, Bishop's Stortford CM23 5QF

### Additional Information

https://bins.uttlesford.gov.uk/

UPRN: 100090643434

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by MankeyJohn** [comment]
How can I found out what this is and how to use it?

**Comment by MankeyJohn** [comment]
> Probably a good Selenium council

How can I find out what this is and how to use it?

**Comment by dp247** [comment]
> How can I find out what this is and how to use it?

Oh, it's more of a note for developers that they'll probably have better results getting the data by scraping with selenium as opposed to emulating requests.
