### ISSUE TITLE
Issue with South Oxfordshire Council

### ISSUE THREAD

**Issue by tewksy** [robbrad/UKBinCollectionData#514]
### Name of Council

South Oxfordshire District Council

### Issue Information

None of the devices or sensors load for South Oxfordshire District Council. I've tried a couple of different UPRN's (my address and my parents) and neither load. I can get other councils to load, just not this one. 

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by robbrad** [comment]
Issue already known - see #191

Please check https://robbrad.github.io/UKBinCollectionData/3.11/1320/#suites/98d3104e051c652961429bf95fa0b5d6/9f2c467007363661/history

**Comment by tewksy** [comment]
Ahh thank you, missed that
