### ISSUE TITLE
Add Docker API server to Docker hub

### ISSUE THREAD

**Issue by robbrad** [robbrad/UKBinCollectionData#529]
Add the Docker Server  image to https://hub.docker.com/repository/docker/robbrad182/uk-bin-collection/general

**Comment by robbrad** [comment]
@OliverCullimore !!!

https://hub.docker.com/repository/docker/robbrad182/uk-bin-collection/general  🥳 

https://github.com/robbrad/UKBinCollectionData/actions/runs/7410757126

**Comment by OliverCullimore** [comment]
@robbrad looks good to me!! 🎉 

Can this one can be closed now?

**Comment by dp247** [comment]
Looking good guys, I'll publish it to Unraid's CA store too sometime this weekend
![image](https://github.com/robbrad/UKBinCollectionData/assets/9065463/7a217f21-7409-4323-b27c-def946a15f65)
