### ISSUE TITLE
Version bump runs twice and fails

### ISSUE THREAD

**Issue by robbrad** [robbrad/UKBinCollectionData#538]
Hi @OliverCullimore 

Looks like the release process has a bug

![image](https://github.com/robbrad/UKBinCollectionData/assets/6122503/48f1d8a2-c5a8-4303-ae3b-3013de75fa14)

I looks to run for the bump change as well as the merge

Can you take a look?

**Comment by robbrad** [comment]
Fixed: [734eec4](https://github.com/robbrad/UKBinCollectionData/commit/734eec4017b0bb0f6296f6077bc95b3712ebd902)

**Comment by OliverCullimore** [comment]
@robbrad Sorry only just seen this, managed to miss that when I set it up, good spot and thanks for fixing.
