### ISSUE TITLE
Adjusted collection dates cannot be read (Kingston)

### ISSUE THREAD

**Issue by andypiper** [robbrad/UKBinCollectionData#545]
### Name of Council

Kingston upon Thames

### Issue Information

Due to the Christmas holidays, the website currently displays, e.g.

`Tuesday, 9 January\n              (this collection has been adjusted from its usual time) 2024`

There's a simple but annoying-to-need-it fix via regex, insert this where the collection date is retrieved to sanitise the string into a format that the data function can handle:

[KingstonUponThamesCouncil.py#L28](https://github.com/robbrad/UKBinCollectionData/blob/49c5879501892bd58528341d7417389cef1d0491/uk_bin_collection/uk_bin_collection/councils/KingstonUponThamesCouncil.py#L28)
```python
collection_date = re.sub(r'\n\s*\(this.*?\)', '', collection_date)
```

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by andypiper** [comment]
Additional note - I'm seeing this call only be successful approximately one in five successive calls.

The page depends on HTMX / AJAX elements and refreshes every 2 seconds to load the table of collection dates. For the "failed" calls, the content passed to BS does not have the `waste__loading_wrapper` element populated. On the ~fifth iteration, that section is populated and the call therefore works successfully.

I've done some digging around into HTMX headers, no cache HTTP headers etc but I'm not currently finding a trigger that works to enable the call to work more regularly. It may require the Selenium driver instead.

**Comment by robbrad** [comment]
@andypiper : could move it to Selenium like some of the other councils?

**Comment by andypiper** [comment]
see #548 👍🏻 seems to work much more successfully.
