### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by robbrad** [robbrad/UKBinCollectionData#55]
As an end user I would like to have the ability to learn how to run the library/debug/develop

consider read the docs (RST) or readme.md / build.md etc

**Comment by dp247** [comment]
I'm going to add a revised README.md to a branch that could be a good starting point. Might also be worth opening up the wiki and discussions tabs to keep issues for future enhancements and bugs 😀

**Comment by robbrad** [comment]
Added https://github.com/robbrad/UKBinCollectionData/blob/master/CONTRIBUTING.md

**Comment by robbrad** [comment]
Think this can be closed - we have an established contributing.md and a wiki. Future could be readthedocs but until then im happy we are at a good level for now
