### ISSUE TITLE
Bedfordshire council only showing Garden Waste and Black Bins, not Recycling or Food Waste

### ISSUE THREAD

**Issue by LouisCoates** [robbrad/UKBinCollectionData#553]
### Home Assistant Version

2024.1.2

### Installation Method

Using HACS

### Name of Council (if relevant)

Bedfordshire

### Issue Information

When setting up the integration it only gives me 2 entities, the black bins, and the garden waste. If I look on the council webpage though it shows 4 schedules, black bins, garden waste, food waste, and recycling. 

![image](https://github.com/robbrad/UKBinCollectionData/assets/23196110/e900ce49-cdbd-4600-8408-24e5709e3feb)

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] If trying to add a specific council, I've checked it is listed as working at https://robbrad.github.io/UKBinCollectionData/3.11/
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by LouisCoates** [comment]
@simondrake Is it still working for you? I know you needed it for home assistant

**Comment by simondrake** [comment]
@LouisCoates it looks like the Recycling has broken, but Black still seems to work. 

What are you seeing?

**Comment by LouisCoates** [comment]
Yes I see black and garden waste. But i don't see recycling and food waste

**Comment by simondrake** [comment]
I'll have to have a look at what's changed. Probably won't be today, but I'll let you know.

**Comment by LouisCoates** [comment]
No worries, thanks mate :)

**Comment by simondrake** [comment]
Just had a very quick look - they've changed the site. I know how to fix it, so I'll try to do that tonight.

**Comment by simondrake** [comment]
@LouisCoates this should be fixed now. 

@robbrad thanks for merging.

**Comment by LouisCoates** [comment]
Oh excellent! Yes that's working for me now! Thanks!

**Comment by robbrad** [comment]
![image](https://github.com/robbrad/UKBinCollectionData/assets/6122503/7d03e64b-af1a-4190-8550-57a0bc888b7d)

Great work!
