### ISSUE TITLE
Council stopped working randomly

### ISSUE THREAD

**Issue by nmr94** [robbrad/UKBinCollectionData#556]
### Name of Council

Wakefield City Council

### Issue Information

I've noted that the UKDB Homeassistant addon was no longer providing any entities. I've attempted to re-add it, updated the version and I've had no luck. Looking at the logs on the Selenium webdriver container, there seems to be some kind of error:

`webdriver-selenium-1  |  [Capabilities {browserName: chrome, goog:chromeOptions: {args: [--headless, --no-sandbox, --disable-gpu, --start-maximized, --disable-dev-shm-usage], excludeSwitches: [enable-logging], extensions: []}, pageLoadStrategy: normal}]
webdriver-selenium-1  | 22:02:22.470 INFO [LocalNode.newSession] - Session created by the Node. Id: d1b4cca8579921fbd4d500a332db0351, Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome-headless-shell, browserVersion: 120.0.6099.109, chrome: {chromedriverVersion: 120.0.6099.109 (3419140ab66..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:45965}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://172.27.0.2:4444/sessio..., se:cdpVersion: 120.0.6099.109, se:vnc: ws://172.27.0.2:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.27.0.2:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
webdriver-selenium-1  | 22:02:22.477 INFO [LocalDistributor.newSession] - Session created by the Distributor. Id: d1b4cca8579921fbd4d500a332db0351 
webdriver-selenium-1  |  Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome-headless-shell, browserVersion: 120.0.6099.109, chrome: {chromedriverVersion: 120.0.6099.109 (3419140ab66..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:45965}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://172.27.0.2:4444/sessio..., se:cdpVersion: 120.0.6099.109, se:vnc: ws://172.27.0.2:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.27.0.2:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
webdriver-selenium-1  | 22:02:23.410 INFO [LocalSessionMap.lambda$new$0] - Deleted session from local Session Map, Id: d1b4cca8579921fbd4d500a332db0351
webdriver-selenium-1  | 22:02:23.411 INFO [GridModel.release] - Releasing slot for session id d1b4cca8579921fbd4d500a332db0351
webdriver-selenium-1  | 22:02:23.412 INFO [SessionSlot.stop] - Stopping session d1b4cca8579921fbd4d500a332db0351
webdriver-selenium-1  | 22:02:23.427 WARN [SeleniumSpanExporter$1.lambda$export$1] - Unable to execute request for an existing session: Unable to find session with ID: d1b4cca8579921fbd4d500a332db0351
webdriver-selenium-1  | Build info: version: '4.16.1', revision: '9b4c83354e'
webdriver-selenium-1  | System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.5.0-14-generic', java.version: '11.0.21'
webdriver-selenium-1  | Driver info: driver.version: unknown
webdriver-selenium-1  | 22:02:23.428 WARN [SeleniumSpanExporter$1.lambda$export$1] - org.openqa.selenium.NoSuchSessionException: Unable to find session with ID: d1b4cca8579921fbd4d500a332db0351
webdriver-selenium-1  | Build info: version: '4.16.1', revision: '9b4c83354e'
webdriver-selenium-1  | System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.5.0-14-generic', java.version: '11.0.21'
webdriver-selenium-1  | Driver info: driver.version: unknown
webdriver-selenium-1  | 	at org.openqa.selenium.grid.sessionmap.local.LocalSessionMap.get(LocalSessionMap.java:132)
webdriver-selenium-1  | 	at org.openqa.selenium.grid.sessionmap.SessionMap.getUri(SessionMap.java:84)
webdriver-selenium-1  | 	at org.openqa.selenium.grid.router.HandleSession.lambda$loadSessionId$4(HandleSession.java:223)
webdriver-selenium-1  | 	at io.opentelemetry.context.Context.lambda$wrap$2(Context.java:224)
webdriver-selenium-1  | 	at org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:180)
webdriver-selenium-1  | 	at org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:382)
webdriver-selenium-1  | 	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
webdriver-selenium-1  | 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)
webdriver-selenium-1  | 	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
webdriver-selenium-1  | 	at org.openqa.selenium.grid.router.Router.execute(Router.java:87)
webdriver-selenium-1  | 	at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)
webdriver-selenium-1  | 	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
webdriver-selenium-1  | 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)
webdriver-selenium-1  | 	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
webdriver-selenium-1  | 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)
webdriver-selenium-1  | 	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
webdriver-selenium-1  | 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)
webdriver-selenium-1  | 	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
webdriver-selenium-1  | 	at org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)
webdriver-selenium-1  | 	at org.openqa.selenium.remote.http.Route.execute(Route.java:69)
webdriver-selenium-1  | 	at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)
webdriver-selenium-1  | 	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
webdriver-selenium-1  | 	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
webdriver-selenium-1  | 	at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)
webdriver-selenium-1  | 	at org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)
webdriver-selenium-1  | 	at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)
webdriver-selenium-1  | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
webdriver-selenium-1  | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
webdriver-selenium-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
webdriver-selenium-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
webdriver-selenium-1  | 	at java.base/java.lang.Thread.run(Thread.java:829)
webdriver-selenium-1  | 
webdriver-selenium-1  | 22:02:23.430 WARN [SeleniumSpanExporter$1.lambda$export$3] - {"traceId": "662c1b441a654e041b4a7675bc687334","eventTime": 1704751343424119226,"eventName": "exception","attributes": {"exception.message": "Unable to execute request for an existing session: Unable to find session with ID: d1b4cca8579921fbd4d500a332db0351\nBuild info: version: '4.16.1', revision: '9b4c83354e'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.5.0-14-generic', java.version: '11.0.21'\nDriver info: driver.version: unknown","exception.stacktrace": "org.openqa.selenium.NoSuchSessionException: Unable to find session with ID: d1b4cca8579921fbd4d500a332db0351\nBuild info: version: '4.16.1', revision: '9b4c83354e'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.5.0-14-generic', java.version: '11.0.21'\nDriver info: driver.version: unknown\n\tat org.openqa.selenium.grid.sessionmap.local.LocalSessionMap.get(LocalSessionMap.java:132)\n\tat org.openqa.selenium.grid.sessionmap.SessionMap.getUri(SessionMap.java:84)\n\tat org.openqa.selenium.grid.router.HandleSession.lambda$loadSessionId$4(HandleSession.java:223)\n\tat io.opentelemetry.context.Context.lambda$wrap$2(Context.java:224)\n\tat org.openqa.selenium.grid.router.HandleSession.execute(HandleSession.java:180)\n\tat org.openqa.selenium.remote.http.Route$PredicatedRoute.handle(Route.java:382)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\n\tat org.openqa.selenium.grid.router.Router.execute(Router.java:87)\n\tat org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0(EnsureSpecCompliantResponseHeaders.java:34)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\n\tat org.openqa.selenium.remote.http.Route$CombinedRoute.handle(Route.java:345)\n\tat org.openqa.selenium.remote.http.Route.execute(Route.java:69)\n\tat org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0(AddWebDriverSpecHeaders.java:35)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)\n\tat org.openqa.selenium.remote.ErrorFilter.lambda$apply$0(ErrorFilter.java:44)\n\tat org.openqa.selenium.remote.http.Filter$1.execute(Filter.java:63)\n\tat org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0(SeleniumHandler.java:44)\n\tat java.base\u002fjava.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base\u002fjava.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\u002fjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\u002fjava.lang.Thread.run(Thread.java:829)\n","exception.type": "org.openqa.selenium.NoSuchSessionException","http.flavor": 1,"http.handler_class": "org.openqa.selenium.grid.router.HandleSession","http.host": "192.168.1.20:4444","http.method": "DELETE","http.scheme": "HTTP","http.target": "\u002fsession\u002fd1b4cca8579921fbd4d500a332db0351","http.user_agent": "selenium\u002f4.15.2 (python linux)","session.id": "d1b4cca8579921fbd4d500a332db0351"}}`

Here is my docker-compose.yml file for the webdriver, just taken directly from the docs, and this was working for a couple of weeks:

`version: '3'

services:
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    restart: unless-stopped`

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by nmr94** [comment]
Opened #557 which fixes the error.

I'm still for some reason getting an empty array returned for the bins, I'll try and look in to this and update #557 if I figure it out.

**Comment by nmr94** [comment]
`<html style="height:100%"><head><meta name="ROBOTS" content="NOINDEX, NOFOLLOW"><meta name="format-detection" content="telephone=no"><meta name="viewport" content="initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"></head><body style="margin:0px;height:100%"><iframe id="main-iframe" src="/_Incapsula_Resource?SWUDNSAI=31&amp;xinfo=13-254127148-0%200NNN%20RT%281704757070990%2015%29%20q%280%20-1%20-1%20-1%29%20r%280%20-1%29%20B12%284%2c315%2c0%29%20U18&amp;incident_id=374001220593181133-1172298356961451661&amp;edet=12&amp;cinfo=04000000&amp;rpinfo=0&amp;cts=UiSMerFqxWlkLuPBn3gosaTM77UcQJ2ZvYse1qbceSw9lHiS6Uu2Z94%2bd%2bk1GyNY&amp;mth=GET" frameborder="0" width="100%" height="100%" marginheight="0px" marginwidth="0px">Request unsuccessful. Incapsula incident ID: 374001220593181133-1172298356961451661</iframe></body></html>
`

Is returned as the page source. So it looks like they've introduced some protection against scraping.

**Comment by robbrad** [comment]
@nmr94 - I just ran the test manually and can see it works

Also the execution history on the nightly tests looks to have a strong history

![image](https://github.com/robbrad/UKBinCollectionData/assets/6122503/8ae2b2d9-8836-4efe-944e-baf197f655c1)

Are you still seeing issues?
