### ISSUE TITLE
Please add Dacorum to the Council List

### ISSUE THREAD

**Issue by jimbox8** [robbrad/UKBinCollectionData#559]
### Name of Council

Dacorum Borough Council

### Example Address/Postcode

HP3 9JY

### Additional Information

https://webapps.dacorum.gov.uk/bincollections/
Requires postcode in text input then select house number from option list

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by edmooredop** [comment]
Seconded!

**Comment by Jim-Noble** [comment]
Thirded
