### ISSUE TITLE
Request to add Mansfield District Council

### ISSUE THREAD

**Issue by DeviantPanda** [robbrad/UKBinCollectionData#560]
### Name of Council

Mansfield District Council

### Example Address/Postcode

NG18 4QX

### Additional Information

https://www.mansfield.gov.uk/xfp/form/1327

Form asks for postcode and returns a list of addresses within that postcode. 

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by DeviantPanda** [comment]
Found a working API URL and key:

API : https://portal.mansfield.gov.uk/MDCWhiteSpaceWebService/WhiteSpaceWS.asmx/GetCollectionByUPRNAndDate

API Key: mDc-wN3-B0f-f4P
Using postman, managed to get a working response from the API URL (found the API in the page source).

Additional Params

UPRN and coldate

Working API example request:

https://portal.mansfield.gov.uk/MDCWhiteSpaceWebService/WhiteSpaceWS.asmx/GetCollectionByUPRNAndDate?apiKey=mDc-wN3-B0f-f4P&UPRN=100031396580&coldate=23/01/2024

**Comment by dp247** [comment]
> Found a working API URL and key:
> 
> API : https://portal.mansfield.gov.uk/MDCWhiteSpaceWebService/WhiteSpaceWS.asmx/GetCollectionByUPRNAndDate
> 
> API Key: mDc-wN3-B0f-f4P Using postman, managed to get a working response from the API URL (found the API in the page source).
> 
> Additional Params
> 
> UPRN and coldate
> 
> Working API example request:
> 
> https://portal.mansfield.gov.uk/MDCWhiteSpaceWebService/WhiteSpaceWS.asmx/GetCollectionByUPRNAndDate?apiKey=mDc-wN3-B0f-f4P&UPRN=100031396580&coldate=23/01/2024

Thanks so much for this, made writing the parser so much easier! 😄

**Comment by DeviantPanda** [comment]
Many thanks Rob, much appreciated.
