### ISSUE TITLE
Gloucester City Council

### ISSUE THREAD

**Issue by gjpgjp** [robbrad/UKBinCollectionData#565]
### Name of Council

Gloucester City Council 

### Example Address/Postcode

73 Quayside Way, Hempsted, Gloucester, GL2 5EX

### Additional Information

Link is https://gloucester-self.achieveservice.com/en/service/Bins___Check_your_bin_day

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by simoncozens** [comment]
We can probably use the same one as ±Tendering and change the URL - same underlying service company.

**Comment by simoncozens** [comment]
Oh, sorry, did I make the mistake of assuming that the same council service contractor would do the same thing for different councils in the same way? No, of course not, the whole thing is completely different. PR incoming.

**Comment by gjpgjp** [comment]
Thanks for working on this. I’ve tried adding the configuration but I am not getting any entities or devices.
