### ISSUE TITLE
Add West Northamptonshire Council

### ISSUE THREAD

**Issue by Rappoman** [robbrad/UKBinCollectionData#567]
### Name of Council

West Northamptonshire

### Example Address/Postcode

NN3 2JB

### Additional Information

https://www.northampton.gov.uk/info/200084/bins-waste-and-recycling/1602/check-your-collection-day

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by Rappoman** [comment]
Is there any other information required to add West Northamptonshire Council?

**Comment by dp247** [comment]
> Is there any other information required to add West Northamptonshire Council?

Nah, looks good. Everyone is probably just a bit busy atm - every so often we complete requests, so don't worry about it.

**Comment by dp247** [comment]
@Rappoman is just the next bin date fine for this? The API that's used only gives the next X-colored bin

**Comment by Rappoman** [comment]
@dp247 whatever you can pull using the API is better than I have at the moment thanks.

**Comment by dp247** [comment]
Cool, I'll pull that
