### ISSUE TITLE
West Lindsey District Council no longer working

### ISSUE THREAD

**Issue by cadwizzard** [robbrad/UKBinCollectionData#568]
### Name of Council

West Lindsey District Council

### Issue Information

Today I noticed all my entities were unavailable. They were fine a week or so ago.
I've updated to the latest version of the integration
I've deleted the service for my address and added back. It adds back without issue, but now no entities appear.

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by dp247** [comment]
@robbrad / @OliverCullimore perhaps we should add an FAQ entry for suggestions to resolve this since it's a somewhat common one

**Comment by cadwizzard** [comment]
Could you please link me to the steps I need from another post if there is a known fix?
Happy to adapt if there is a method w expected to work

**Comment by dp247** [comment]
> Could you please link me to the steps I need from another post if there is a known fix? Happy to adapt if there is a method w expected to work

Sorry, that wasn't a sly at you. These may help for now: https://community.home-assistant.io/t/bin-waste-collection/55451/448

**Comment by cadwizzard** [comment]
Thanks, I tried that as far as I can. But I dont have Selenium (i'm not a dev). I've also since tried completed removing the council and integration, restarting HA, redownloading the integration and re-adding the location for West Lindsey. No entities.
My Postcode is LN8 2AR if that helps you check if the (West Lindsey District) council have changed something

**Comment by robbrad** [comment]
West Lindsey is working here is the nightly test run for it

![image](https://github.com/robbrad/UKBinCollectionData/assets/6122503/cacce88b-b3f7-4992-a50a-79648c7284b2)

@cadwizzard - can you share any more info on this?

Selenium is not required for West Lindsey

**Comment by cadwizzard** [comment]
I still get no entities, but I did get screenshots and a log with some errors (relating to day/date out of range)

![Screenshot 2024-02-05 121705](https://github.com/robbrad/UKBinCollectionData/assets/7688705/d0a05ebb-ec31-4b4b-9cd8-0d1e3d64a297)
![Screenshot 2024-02-05 121721](https://github.com/robbrad/UKBinCollectionData/assets/7688705/bb78a58e-4986-4d62-b7a1-e9c15b1b8f07)

[home-assistant_uk_bin_collection_2024-02-05T12-17-34.806Z.log](https://github.com/robbrad/UKBinCollectionData/files/14165557/home-assistant_uk_bin_collection_2024-02-05T12-17-34.806Z.log)


Does that help?

**Comment by dp247** [comment]
> Does that help?

Yes, yes it does haha. The issue here is that the council provides dates in DD/MM format, and the code was trying to add a year to that to build it into a full datetime, which defaults to 1900. However, since this year is a leap year and the collection was on 29/02, it threw an error since 29/02/1900 doesn't exist as a date. This PR should fix it though.

**Comment by cadwizzard** [comment]
Awesome. Glad that's figured out. Only a guess if other councils work that way too. Which build will have this PR please? :)

**Comment by dp247** [comment]
It's the great thing about not having a standardised system - you get nice surprises every so often.

Build will be deployed automatically whenever someone reviews my PR, which is usually pretty quickly hehe

**Comment by cadwizzard** [comment]
Hopefully Soon !! :)
