### ISSUE TITLE
Perth and Kinross council

### ISSUE THREAD

**Issue by hippytyre** [robbrad/UKBinCollectionData#572]
### Name of Council

Perth and Kinross council

### Example Address/Postcode

PH1 3EZ / 124037249

### Additional Information

Can someone please add Perth and Kinross council?

URL to the website : https://my.pkc.gov.uk/service/Bin_collection_dates?referrer=MyPKC_Services

My girlfriend works for this council and she informs me that they use the same system as Falkirk council (Granicus).

Thanks!

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by cowieson** [comment]
Just adding myself as another person who would benefit from this!
