### ISSUE TITLE
Add additional aggregated sensor to show next bin[s]

### ISSUE THREAD

**Issue by skelt0** [robbrad/UKBinCollectionData#574]
At the moment the integration provides one sensor per bin type - with each sensor having additional attributes. 

It would be useful if additional sensor was added called 'Next Bin' which displayed the type of the next bin due based on the dates. If multiple bins on the next date due, then provide multiple. 

This would allow much easier automations to be driven from this rather than having to work things out. 

For an example automation, it would be useful to trigger a light to show Blue, if the Blue bin was due to go out tomorrow. This light would go off on the trigger of an additional automation once the bin has been taken out. 

I think this is possible in the current setup but adding this sensor would make it far simpler to implement for users. This may also be a more useful dashboard view for some users / reduce clutter. 

Example entity:
Name: Next Bin
Data: Blue

Additional attributes: 
Date: <date> ('tomorrow') 
Days: 3

**Comment by mrw298** [comment]
If it helps anyone, this is the template I use:
```
sensor:
    - name: "Next Bin"
      state: >-
        {% if (state_attr("sensor.black_bin", "days") | int(99)) < (state_attr("sensor.blue_bin", "days") | int(99)) %}
        Black Bin
        {% else %}
        Blue Bin
        {% endif %}
      attributes:
        days: >-
          {% if (state_attr("sensor.black_bin", "days") | int(99)) < (state_attr("sensor.blue_bin", "days") | int(99)) %}
          {{ state_attr("sensor.black_bin", "days") }}
          {% else %}
          {{ state_attr("sensor.blue_bin", "days") }}
          {% endif %}
        next_collection: >-
          {% if (state_attr("sensor.black_bin", "days") | int(99)) < (state_attr("sensor.blue_bin", "days") | int(99)) %}
          {{ state_attr("sensor.black_bin", "next_collection") }}
          {% else %}
          {{ state_attr("sensor.blue_bin", "next_collection") }}
          {% endif %}
        friendly_date: >-
          {% if (state_attr("sensor.black_bin", "days") | int(99)) < (state_attr("sensor.blue_bin", "days") | int(99)) %}
          {{ states("sensor.black_bin") }}
          {% else %}
          {{ states("sensor.blue_bin") }}
          {% endif %}
        color: >-
          {% if (state_attr("sensor.black_bin", "days") | int(99)) < (state_attr("sensor.blue_bin", "days") | int(99)) %}
          black
          {% else %}
          blue
          {% endif %}
        icon: >-
          {% if (state_attr("sensor.black_bin", "days") | int(99)) < (state_attr("sensor.blue_bin", "days") | int(99)) %}
          mdi:trash-can
          {% else %}
          mdi:recycle
          {% endif %}

```

**Comment by robbrad** [comment]
So in summary @skelt0 your asking for the attributes to be broken out into sensors?

**Comment by robbrad** [comment]
Maybe the bin should be a “Device” ?

**Comment by skelt0** [comment]
Sorry for the lack of feedback - Yes, these changes make a huge difference and make automations significantly simpler! I updated the plugin last night and it works brilliantly - Thanks for all your continued work on this!
