### ISSUE TITLE
Add new council: Teignbridge

### ISSUE THREAD

**Issue by get-fooby** [robbrad/UKBinCollectionData#580]
### Name of Council

Teignbridge District Council

### Example Address/Postcode

TQ14 9HZ

### Additional Information

https://www.teignbridge.gov.uk/recycling-and-waste/waste-and-recycling-collections/when-are-my-bins-and-boxes-collected

valid UPRN https://www.teignbridge.gov.uk/recycling-and-waste/waste-and-recycling-collections/when-are-my-bins-and-boxes-collected?UPRN=100040338929

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by ScubyG** [comment]
Amazing work, thank you. I have now integrated it in my HA dashboard :)

![image](https://github.com/user-attachments/assets/43d87bec-daf5-4ac7-81b1-8de8d03960f3)

**Comment by robbrad** [comment]
Kudos to @m26dvd !
