### ISSUE TITLE
Error running collect_data.py on new server install

### ISSUE THREAD

**Issue by rick165** [robbrad/UKBinCollectionData#588]
I'm trying to move this over to a different server and so have followed the instructions to clone the repo, then do the poetry install, then activate the virtualenv before running collect_data.py however I get the following error about google-chrome, however I didnt have google-chrome installed on the server the script is working on currently.

```
uk-bin-collection-py3.11) rick@Teraserver2:~/scripts/UKBinCollectionData/uk_bin_collection/uk_bin_collection $ python collect_data.py HighPeakCouncil https://www.highpeak.gov.uk/findyourbinday -s -p "SK13 XXX" -n "redacted address" 
/bin/sh: 1: google-chrome: not found
/bin/sh: 1: google-chrome-stable: not found
/bin/sh: 1: google-chrome-beta: not found
/bin/sh: 1: google-chrome-dev: not found
/bin/sh: 1: google-chrome: not found
/bin/sh: 1: google-chrome-stable: not found
/bin/sh: 1: google-chrome-beta: not found
/bin/sh: 1: google-chrome-dev: not found
An error occurred: 'NoneType' object has no attribute 'split'
```

Any advice as to what might be missing?

**Comment by dp247** [comment]
Looks like you're missing the url of selenium webdriver:
https://github.com/robbrad/UKBinCollectionData/wiki/Councils#high-peak-council

**Comment by rick165** [comment]
Yes. you're correct. The older version of this repo I had on my previous server didnt need the remote selenium web server specifying, whereas the version I cloned down to my new server did.
