### ISSUE TITLE
Add new council: Canterbury

### ISSUE THREAD

**Issue by CharlotteSjothun** [robbrad/UKBinCollectionData#590]
### Name of Council

Canterbury City Council

### Example Address/Postcode

CT3 4FP

### Additional Information

Link with valid uprn and usrn: https://www.canterbury.gov.uk/bins-and-waste/find-your-bin-collection-dates?uprn=10094583174&usrn=5605848

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by JakeStanger** [comment]
Although not documented, Canterbury have updated their site and now has an API you can use without too much difficulty.

Using the above UPRN/USRN values as an example:

bash:
```bash
curl -X POST 'https://zbr7r13ke2.execute-api.eu-west-2.amazonaws.com/Beta/get-bin-dates' \
  --data '{ "uprn": "10094583174", "usrn": "5605848" }' | jq -r '.dates' | jq
```

js:
```js
const url = 'https://zbr7r13ke2.execute-api.eu-west-2.amazonaws.com/Beta/get-bin-dates'
const dates = await fetch(url, {
    method: 'POST',
    body: JSON.stringify({ "uprn": "10094583174", "usrn": "5605848" }),
  })
    .then((r) => r.json())
    .then((r) => r.dates)
    .then(JSON.parse);
```


The only oddity is that the API returns a JSON object where all the data is then inside a string, so you have to double-parse it.

**Comment by robbrad** [comment]
We have another council just like that
