### ISSUE TITLE
Reading Council Misbehaving 

### ISSUE THREAD

**Issue by boxofrabbits** [robbrad/UKBinCollectionData#591]
### Name of Council

Reading Borough Council

### Issue Information

This has stopped working. It appears the /api/ access no longer exists. 

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by dp247** [comment]
Looks like an issue with the council site than with this project

**Comment by boxofrabbits** [comment]
Hiya, thanks for your reply. Is it possible the API addresses have changed?
I get results for:
https://api.reading.gov.uk/rbc/mycollections/310055593

But don't get anything from the:
https://api.reading.gov.uk/api/collections/XXXXXXXX

Included in the addon.

**Comment by boxofrabbits** [comment]
> Hiya, thanks for your reply. Is it possible the API addresses have changed? I get results for: https://api.reading.gov.uk/rbc/mycollections/310055593
> 
> But don't get anything from the: https://api.reading.gov.uk/api/collections/XXXXXXXX
> 
> Included in the addon.



> Looks like an issue with the council site than with this project

Hiya, thanks for your reply. Is it possible the API addresses have changed?
I get results for:
https://api.reading.gov.uk/rbc/mycollections/310055593

But don't get anything from the:
https://api.reading.gov.uk/api/collections/XXXXXXXX

Included in the addon.

**Comment by boxofrabbits** [comment]
> Looks like an issue with the council site than with this project

Hiya, thanks for your reply. Is it possible the API addresses have changed?
I get results for:
https://api.reading.gov.uk/rbc/mycollections/310055593

But don't get anything from the:
https://api.reading.gov.uk/api/collections/XXXXXXXX

Included in the addon.
