### ISSUE TITLE
Council Request: St Albans City & District Council

### ISSUE THREAD

**Issue by root3d1** [robbrad/UKBinCollectionData#592]
### Name of Council

St Albans City & District Council

### Example Address/Postcode

AL3 7EX

### Additional Information

https://gis.stalbans.gov.uk/NoticeBoard9/NoticeBoard.aspx

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by dp247** [comment]
Completed in #596
