### ISSUE TITLE
Returning incorrect results

### ISSUE THREAD

**Issue by sym0nd0** [robbrad/UKBinCollectionData#594]
### Name of Council

Gedling Borough Council

### Issue Information

All addresses are returning days/dates that don't match to the councils schedule.

Examples (random addresses from across the borough):
- 63 Godfrey Street's next bin collection (FridayG2-2024.pdf) is the black bin on Friday 26th January, but results are returned showing green bin Tuesday 30th January. Garden bin (Garden Waste E.pdf) is due for collection 6th April, results show Thursday 14th March.
- 1 Chadburn Road (MondayG1-2024.pdf) is black bin on Monday 29th January, results show green bin Friday 26th January. Garden bin (Garden Waste A.pdf) is due Monday 4th March, results show Thursday 7th March.
- 30 Haddon Road (MondayG4-2024.pdf) is recycling bin on Monday 29th January, results show black bin Wednesday 31st January. Garden bin (Garden Waste C.pdf) is due Wednesday 6th March, results show Monday 4th March.

Steps to reproduce:
1. Install in HACs
2. Add integration in HA
3. Add Service
4. Enter street name in Location field (e.g. Haddon Road)
5. Choose Gedling Borough Council from dropdown
6. Submit
7. Enter house number in house number field (e.g. 30)
8. Submit and recieve success prompt
9. Check entities have been created
10. Check dates shown for entities against Councils pdfs

1 Chadburn results:
![image](https://github.com/robbrad/UKBinCollectionData/assets/55590428/90853b8d-c6f6-4a66-9e95-1e08e4acfd1c)
![image](https://github.com/robbrad/UKBinCollectionData/assets/55590428/8a6bed2e-98d0-48fd-9822-5bae9906e568)
![image](https://github.com/robbrad/UKBinCollectionData/assets/55590428/98f6d3c3-9633-4263-a102-e344c588eaf9)
![image](https://github.com/robbrad/UKBinCollectionData/assets/55590428/f51ee238-c1fe-45f7-b3b8-a79a53230653)

1 Chadburn council PDF:
![image](https://github.com/robbrad/UKBinCollectionData/assets/55590428/ce60abe4-db95-4164-9d06-8d1c0a255d33)
![image](https://github.com/robbrad/UKBinCollectionData/assets/55590428/4767d149-357c-4bc8-90bb-3d1ea7041c83)

Please let me know if you need me to provide anymore information, clarification on anything or if you require anything testing.

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by robbrad** [comment]
@skelt0 / @roberthunt FYI

**Comment by skelt0** [comment]
I'll take a look!

**Comment by skelt0** [comment]
@sym0nd0 - The council only allow parsing of street names, so please put the street name into the house number field and try again. 

The 'location' field, i believe, is how you will refer to the device location internally in Home Assistant, i.e. "Home". 

Putting "Chadburn Road" into the house number field should give you the right results. Please can you test and let me know?

Appreciate there is some confusion, there was no field for 'street name only' for me to use so had to use house number. This is loosely documented in the wiki page for the council however thats mostly talking about how to use it on the command line

**Comment by skelt0** [comment]
No worries @sym0nd0! Glad it's working now!
