### ISSUE TITLE
Bournemouth Poole Council

### ISSUE THREAD

**Issue by mtan93** [robbrad/UKBinCollectionData#6]
Please could Bournemouth Poole Council be added?

https://www.poole.gov.uk/bins-waste-and-recycling/bins/bin-collection-day-finder/

Example post code: BH14 0PD

**Comment by dp247** [comment]
For future reference:
https://online.bcpcouncil.gov.uk/bcp-apis/?api=BinDayLookup&uprn=

**Comment by dp247** [comment]
The parser is done (23c471542d62b59075e6ce5b73ecd9eb2d36799d) and will finish the project files tomorrow
