### ISSUE TITLE
Wirral Council

### ISSUE THREAD

**Issue by matteusz88** [robbrad/UKBinCollectionData#602]
### Name of Council

Wirral Council

### Example Address/Postcode

CH63 1JG

UPRN 42085478

### Additional Information

https://www.wirral.gov.uk/bins-and-recycling/bin-collection-dates?s=Oxford+Drive

This page shows one of 3 collection schedules, 2 other bins types are clickable from the page, but don't change the url.

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by tw332** [comment]
Second vote for Wirral council.

Some additional info below that may help.

Street names can span multiple wards so the query must include the council ward. From a UI perspective, if a street does span multiple wards, the user will need to select the correct one.

Ultimately, resulting in a URL similar to:
[https://ww3.wirral.gov.uk/recycling/detailContentDru7.asp?s=Oxford%20Drive&t=Thornton%20Hough&c=Non%20recycleable%20(green%20bin)](https://ww3.wirral.gov.uk/recycling/detailContentDru7.asp?s=Oxford%20Drive&t=Thornton%20Hough&c=Non%20recycleable%20(green%20bin))

The options for the different bin types would be:

1. Non recyclable (green bin)
2. Garden waste (brown bin)
3. Paper and packaging (grey bin)

For this council, non-recyclable and garden waste are often (always?) collected on the same day

**Comment by richiemuk** [comment]
Third vote here
