### ISSUE TITLE
No longer collecting data correctly from environmentfirst website

### ISSUE THREAD

**Issue by theolsen** [robbrad/UKBinCollectionData#603]
### Home Assistant Version

2024.1.6

### Installation Method

Using HACS

### Name of Council (if relevant)

environmentfirst

### Issue Information

There are 2 entities that should be scraped from the website...rubbish & recycling. Recycling is fine but rubbish now returns "This entity is no longer being provided by the uk_bin_collection integration. If the entity is no longer in use, delete it in settings." This behaviour began around one week ago.
If I go to the site (https://environmentfirst.co.uk/house.php?uprn=100060053442) I can see that the data is presented correctly.

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] If trying to add a specific council, I've checked it is listed as working at https://robbrad.github.io/UKBinCollectionData/3.11/
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by robbrad** [comment]
Can you provide any more debug logs from Home assistant?

When I run it I see both bits of data returned

![image](https://github.com/robbrad/UKBinCollectionData/assets/6122503/06acf4ea-1b25-4f0c-b9d6-72af55910948)

**Comment by theolsen** [comment]
Thanks for looking into it Rob, unfortunately I removed and tried to reinstall before I saw your reply.
When I set up again, I go through the configuration. It looks like it has completed but I now get no entities.

<img width="439" alt="Screenshot 2024-02-03 at 14 24 56" src="https://github.com/robbrad/UKBinCollectionData/assets/4518932/b750d7b1-2b6d-4c28-ac3e-b80d2ea72077">


Having said that the debug log looks like it is working! 

`[UKBinCollection]`  UKBinCollectionApp Updating
2024-02-03 14:17:12.168 INFO (MainThread) [custom_components.uk_bin_collection.sensor] [UKBinCollection]  UKBinCollectionApp: {
    "bins": [
        {
            "type": "Rubbish",
            "collectionDate": "29/01/2024"
        },
        {
            "type": "Recycling",
            "collectionDate": "02/02/2024"
        }
    ]
}
2024-02-03 14:17:12.168 INFO (MainThread) [custom_components.uk_bin_collection.sensor] [UKBinCollection]  Data Supplied: {'bins': [{'type': 'Rubbish', 'collectionDate': '29/01/2024'}, {'type': 'Recycling', 'collectionDate': '02/02/2024'}]} and type of data is <class `'dict'>`

**Comment by theolsen** [comment]
Seems to have sorted itself out now. It was the website at fault. The data there was stale.
