### ISSUE TITLE
Please Add Coventry City Council

### ISSUE THREAD

**Issue by JonathanStreet** [robbrad/UKBinCollectionData#607]
### Name of Council

Coventry City Council

### Example Address/Postcode

High Street - City Centre

### Additional Information

Search requires 'street name':
* https://www.coventry.gov.uk/bin-collection-calendar
* https://www.coventry.gov.uk/directory/search?directoryID=82&showInMap=&keywords=High+Street&search=Search+directory

There is also an A-Z of street name records - https://www.coventry.gov.uk/directory/82/a-to-z/A

Street record page:
* https://www.coventry.gov.uk/directory-record/56556/high-street-city-centre-

Can then select 'Find out which bin will be collected when.' button, which returns:
* `https://www.coventry.gov.uk/bins<day><letter>`, e.g. https://www.coventry.gov.uk/binstuesdaya

Where `<day>` is in `monday`, `tuesday`, `wednesday`, `thursday`, `friday`, and `<letter>` is in `a`, `b` (accurate as of submission, 2024-02-09).

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by danmarson** [comment]
+1 for this. Would love to be able to make use of this! @JonathanStreet
