### ISSUE TITLE
Bug in MertonCouncil.py

### ISSUE THREAD

**Issue by r-kc** [robbrad/UKBinCollectionData#609]
### Name of Council

Merton

### Issue Information

Home assistant fails with the error:

`File "/config/custom_components/uk_bin_collection/sensor.py", line 93, in get_latest_collection_info
    bin_type = bin_data["type"]`

In MertinCouncil.py I think line 42 needs to be changed from "bin_type": bin_type to "type": bin_type to fix this issue. 

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by dp247** [comment]
@r-kc: is this still an issue? The code seems to work for some addresses, so I'd be interested to find out why not for yours. If you don't want to post your URL here, my email is on my GitHub page 😄

**Comment by r-kc** [comment]
This is still an issue, I have been manually changing the code after each update. I will send you my address.

**Comment by dp247** [comment]
Cool, send me both the address and the code and I'll try work it out

**Comment by dp247** [comment]
@r-kc: This'll fix it, just waiting for the merge :)
