### ISSUE TITLE
Task exception was never retrieved

### ISSUE THREAD

**Issue by pacmac** [robbrad/UKBinCollectionData#611]
### Home Assistant Version

2024.2.1 (latest)

### Installation Method

Using HACS

### Name of Council (if relevant)

Somerset

### Issue Information

Just noticed this in the system logs, the sensors / frontend appears to be showing correctly.

Not sure what else you need ??

```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/uk_bin_collection/sensor.py:179
Integration: UK Bin Collection Data (documentation, issues)
First occurred: 08:36:13 (1 occurrences)
Last logged: 08:36:13

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 256, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 412, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 183, in async_update_listeners
    update_callback()
  File "/config/custom_components/uk_bin_collection/sensor.py", line 159, in _handle_coordinator_update
    self.apply_values()
  File "/config/custom_components/uk_bin_collection/sensor.py", line 179, in apply_values
    self.coordinator.data[self._bin_type], dayfirst=True
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'Recycling'
```

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] If trying to add a specific council, I've checked it is listed as working at https://robbrad.github.io/UKBinCollectionData/3.11/
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by dp247** [comment]
Looks like the site may have changed

**Comment by dp247** [comment]
@pacmac: is this still an issue?

**Comment by dp247** [comment]
Cannot reproduce issue, feel free to reopen if it still affects you.
