### ISSUE TITLE
Please add Rossendale Borough Council

### ISSUE THREAD

**Issue by pk-1966** [robbrad/UKBinCollectionData#612]
### Name of Council

Rossendale Borough Council

### Example Address/Postcode

Post code:UPRN: 100012543726

### Additional Information

The URL is https://www.rossendale.gov.uk/homepage/20003/find-your-bin-collection-day

However, the result is a PDF brochure which contains a calendar, so my suspicion is that integration to this council won't work yet.

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by dp247** [comment]
Yeah, unfortunately, we don't currently support councils with PDF calendars, but maybe sometime in the future 😅
