### ISSUE TITLE
London Borough of Lambeth

### ISSUE THREAD

**Issue by Kalekdan** [robbrad/UKBinCollectionData#615]
### Name of Council

London Borough of Lambeth

### Example Address/Postcode

SW46BS

### Additional Information

UPRN: 100021881738 
The URL to navigate to is: https://wasteservice.lambeth.gov.uk/myaddress (can put for example SW46BS as a postcode). The API that is called behind the scenes is (payload provided using example UPRN above):
https://wasteservice.lambeth.gov.uk/WhitespaceComms/GetServicesByUprn
`{
    "uprn": "100021881738",
    "includeEventTypes": false,
    "includeFlags": true
}`

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by Kalekdan** [comment]
I don't seem able to assign this to myself - but I'm investigating

**Comment by AlexTryHarder** [comment]
+

**Comment by AlexTryHarder** [comment]
@Kalekdan Did you managed to have it working?
It would be super useful.
