### ISSUE TITLE
Mid Sussex District Council Broken

### ISSUE THREAD

**Issue by Bcrutt** [robbrad/UKBinCollectionData#616]
### Name of Council

Mid Sussex District Council

### Issue Information

Hi
After installing and configuring I get the errors in the HA log files below

[Bin Collection Error.txt](https://github.com/robbrad/UKBinCollectionData/files/14343829/Bin.Collection.Error.txt)

I also tried pasting https://www.midsussex.gov.uk/waste-recycling/bin-collection/ -s -p "RH17 7SG" -n 4 but this returned 404 page not found on the Mid Sussex website.

Thanks

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by robbrad** [comment]
Council has changed their website this scraper needs to be updated

**Comment by robbrad** [comment]
Needs Selenium now unfortunatly
