### ISSUE TITLE
Add Oldham Council

### ISSUE THREAD

**Issue by Ubique88** [robbrad/UKBinCollectionData#619]
### Name of Council

Oldham Coluncil

### Example Address/Postcode

OL3 5BH

### Additional Information

https://portal.oldham.gov.uk/bincollectiondates/details?uprn=422000103486

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by dp247** [comment]
Already exists - see #264
