### ISSUE TITLE
Request for Rochford council to be added

### ISSUE THREAD

**Issue by Tailzer** [robbrad/UKBinCollectionData#620]
### Name of Council

Rochford Council

### Example Address/Postcode

SS5 4QA

### Additional Information

https://www.rochford.gov.uk/online-bin-collections-calendar

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by dp247** [comment]
Hands down the zaniest way to present bin dates

**Comment by dp247** [comment]
I've taken the approach that a displayed date should be "week commencing" - I'll add a note to the wiki 😄
