### ISSUE TITLE
Please add Arun district council 

### ISSUE THREAD

**Issue by MinuteLicence** [robbrad/UKBinCollectionData#624]
### Name of Council

Arun district council 

### Example Address/Postcode

BN17 7JF

### Additional Information

https://www1.arun.gov.uk/when-are-my-bins-collected

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by dp247** [comment]
This is probably a good one for Selenium since it relies on UI/address selection from a dropdown

**Comment by georgeherby** [comment]
+1

**Comment by georgeherby** [comment]
PR in for this in #676 

![image](https://github.com/robbrad/UKBinCollectionData/assets/21989833/d3b3bfb2-91f6-440f-a442-d192b35ec460)
