### ISSUE TITLE
Contributor access to write on wiki

### ISSUE THREAD

**Issue by dp247** [robbrad/UKBinCollectionData#63]
Hey @robbrad, just wondered if it was possible to give contributors write permissions to the wiki (totally understandable if not, I don't mind submitting a PR instead 😁). I'd like to use it to provide a list of supported councils, as well as the necessary commands to run the script (as opposed to another markdown file!)

**Comment by robbrad** [comment]
Is it already there? 

![69AE9260-E7C9-4F00-B111-B63ADA8DEFE7](https://user-images.githubusercontent.com/6122503/180848754-575aaba8-0cb6-429e-9273-f04cf0cee5de.jpeg)

**Comment by dp247** [comment]
Oh... for some reason I can't add to it 😅. There's no options to add a new page. 🤣

**Comment by robbrad** [comment]
Hmmm - had to "add" you as a collaborator to the repo - I mean jeeez GH - my man @dp247 is kinda already doing that

**Comment by dp247** [comment]
Hahahaha! You're too kind! 😀. I'll get to work on docs this week!
