### ISSUE TITLE
North Tyneside issues

### ISSUE THREAD

**Issue by hallbchris** [robbrad/UKBinCollectionData#631]
### Name of Council

North Tyneside

### Issue Information

Installed repo into HACS and configured with appropriate UPRN and postcode correctly formatted with space. Tested with door number as well as door number and street name for brevity. 
Returned results in the integration show inaccurate dates/bin colours when compared with the council's schedule 

![image](https://github.com/robbrad/UKBinCollectionData/assets/103254133/89e0784f-4d05-4d9a-aa1c-64e6a3e435e8)

Output in the entity for grey bin
![image](https://github.com/robbrad/UKBinCollectionData/assets/103254133/db57a47e-8643-488b-a646-63720917adbf)
Output in the entity for green bin
![image](https://github.com/robbrad/UKBinCollectionData/assets/103254133/2be9673e-99af-4c4b-9441-6b54a7a93909)

As you can see there's discrepancy there. 

If there's anything I can do to provide more context or test any further please do let me know. 

Much obliged!

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by dp247** [comment]
Can you provide a UPRN and postcode at or near your address? If you don't want to post it here, there are some contact options on my Github profile 😊

**Comment by hallbchris** [comment]
Thanks for the quick response! I've emailed the details over.

**Comment by dp247** [comment]
> Thanks for the quick response! I've emailed the details over.

Should have probably said but, I did get them and I will look into it when I get some free time 😄

**Comment by hallbchris** [comment]
Awesome thanks!

**Comment by AlexHedley** [comment]
#150 #161

**Comment by dp247** [comment]
Turns out passing a cookie defaulted to one address somewhere in Whitley Bay, who would have guessed.

On another note, I'll need to revisit this in the new financial year and/or think about how to differentiate between the green and grey bins.

**Comment by AlexHedley** [comment]
**Week A**

https://my.northtyneside.gov.uk/sites/default/files/bin_collections/Refuse_and_Recycling_Waste_Collection_Calendar_Tuesday_Week_A.pdf

https://my.northtyneside.gov.uk/sites/default/files/bin_collections/Garden_Waste_Collection_Calendar_Saturday_Week_A.pdf

**Week B**

https://my.northtyneside.gov.uk/sites/default/files/bin_collections/Refuse_and_Recycling_Waste_Collection_Calendar_Tuesday_Week_B.pdf

https://my.northtyneside.gov.uk/sites/default/files/bin_collections/Garden_Waste_Collection_Calendar_Saturday_Week_B.pdf

**Comment by mogusbi** [comment]
Wanted to check in to see if there was any progress on this issue?

**Comment by dp247** [comment]
> Wanted to check in to see if there was any progress on this issue?

Nah, I haven't had time to look at this😅

**Comment by psimonkey** [comment]
I've had a go and submitted https://github.com/robbrad/UKBinCollectionData/pull/784.

**Comment by psimonkey** [comment]
That fix has been merged now, and I've verified it working on my HA server.

**Comment by mogusbi-motech** [comment]
All looks good for me except the garden waste bin, which is displaying the wrong week for me. 

Thanks for getting it working @psimonkey

**Comment by mogusbi-motech** [comment]
I've just emailed that across @psimonkey

**Comment by robbrad** [comment]
@psimonkey We have added the ability to specify an icon mapping https://github.com/robbrad/UKBinCollectionData/issues/910#issuecomment-2428792630 - you might want to try this

**Comment by robbrad** [comment]
@hallbchris Is North Tyneside working now?

**Comment by robbrad** [comment]
![image](https://github.com/user-attachments/assets/d22b80a6-c68f-4fd6-a304-8e1088737a15)

**Comment by hallbchris** [comment]
> @hallbchris Is North Tyneside working now?

Appears to be working now thanks guys! Much appreciated 👏
