### ISSUE TITLE
button is not clickable at point

### ISSUE THREAD

**Issue by andrewtoddd** [robbrad/UKBinCollectionData#637]
### Name of Council

Gateshead Council

### Issue Information

when running against gateshead council standalone terminal selenium errors with button not clickable.
have ran against other councils Leeds, Northumberland and they worked correctly

`python3 collect_data.py GatesheadCouncil https://www.gateshead.gov.uk/ -s -p "XXX XX" -n XX -w http://IP:4444`

> An error occurred: Message: element click intercepted: Element <input type="button" value="Find address" id="BINCOLLECTIONCHECKER_ADDRESSSEARCH_ADDRESSLOOKUPSEARCH" name="BINCOLLECTIONCHECKER_ADDRESSSEARCH_ADDRESSLOOKUPSEARCH" class="icminput icminput--button" onclick=""> is not clickable at point (90, 458). Other element would receive the click: <button class="btn btn--contrast btn--complete" name="acceptall" value="true" type="submit">...</button>
>   (Session info: chrome-headless-shell=122.0.6261.69)
> Stacktrace:
> 
> 
> Traceback (most recent call last):
>   File "/home/andrew/UKBinCollectionData/UKBinCollectionData/uk_bin_collection/uk_bin_collection/collect_data.py", line 122, in <module>
>     print(app.run())
>   File "/home/andrew/UKBinCollectionData/UKBinCollectionData/uk_bin_collection/uk_bin_collection/collect_data.py", line 96, in run
>     return self.client_code(
>   File "/home/andrew/UKBinCollectionData/UKBinCollectionData/uk_bin_collection/uk_bin_collection/collect_data.py", line 115, in client_code
>     return get_bin_data_class.template_method(address_url, **kwargs)
>   File "/home/andrew/UKBinCollectionData/UKBinCollectionData/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 78, in template_method
>     bin_data_dict = self.parse_data(
>   File "/home/andrew/UKBinCollectionData/UKBinCollectionData/uk_bin_collection/uk_bin_collection/councils/GatesheadCouncil.py", line 49, in parse_data
>     findAddress.click()
>   File "/home/andrew/.cache/pypoetry/virtualenvs/uk-bin-collection-koTV66Ka-py3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 93, in click
>     self._execute(Command.CLICK_ELEMENT)
>   File "/home/andrew/.cache/pypoetry/virtualenvs/uk-bin-collection-koTV66Ka-py3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 394, in _execute
>     return self._parent.execute(command, params)
>   File "/home/andrew/.cache/pypoetry/virtualenvs/uk-bin-collection-koTV66Ka-py3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 344, in execute
>     self.error_handler.check_response(response)
>   File "/home/andrew/.cache/pypoetry/virtualenvs/uk-bin-collection-koTV66Ka-py3.10/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <input type="button" value="Find address" id="BINCOLLECTIONCHECKER_ADDRESSSEARCH_ADDRESSLOOKUPSEARCH" name="BINCOLLECTIONCHECKER_ADDRESSSEARCH_ADDRESSLOOKUPSEARCH" class="icminput icminput--button" onclick=""> is not clickable at point (90, 458). Other element would receive the click: <button class="btn btn--contrast btn--complete" name="acceptall" value="true" type="submit">...</button>
>   (Session info: chrome-headless-shell=122.0.6261.69)
> Stacktrace:

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by dp247** [comment]
Looks like its getting stuck on some kind of popup for accepting cookies
