### ISSUE TITLE
Please add Colchester council

### ISSUE THREAD

**Issue by Stig2k** [robbrad/UKBinCollectionData#639]
### Name of Council

Colchester City Council

### Example Address/Postcode

CO2 8UN

### Additional Information

https://www.colchester.gov.uk/
https://www.colchester.gov.uk/your-recycling-calendar/
https://www.colchester.gov.uk/your-recycling-calendar/?start=true&step=1&llpgid=1ebfa980-3c27-e711-80fa-5065f38b5681

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by dp247** [comment]
@Stig2k Do you want a bin type for each of these? 
![image](https://github.com/robbrad/UKBinCollectionData/assets/9065463/694c59aa-5d7d-40f8-b547-adbfbddc505c)

**Comment by Stig2k** [comment]
Yes please
