### ISSUE TITLE
Running the script returns `TypeError: 'module' object is not callable`

### ISSUE THREAD

**Issue by tm-kn** [robbrad/UKBinCollectionData#642]
The script path in `pyproject.toml` is incorrect.

# Steps to reproduce the issue

```sh
python3 -m venv venv 
. venv/bin/activate pip install https://github.com/robbrad/UKBinCollectionData/archive/refs/heads/master.zip
uk_bin_collection
```

That returns an error:

```sh
Traceback (most recent call last):
  File "/Users/tomasz/tmp/venv/bin/uk_bin_collection", line 8, in <module>
    sys.exit(collect_data())
             ^^^^^^^^^^^^^^
TypeError: 'module' object is not callable
````

**Comment by dp247** [comment]
Excuse my ignorance but, what exactly does the command do?

**Comment by tm-kn** [comment]
> Excuse my ignorance but, what exactly does the command do?
I am assuming the `uk_bin_collection` is supposed to call the `collect_data.py` script. If you install the package, it creates a script in your bin directory.

**Comment by robbrad** [comment]
@tm-kn is this fixed?
