### ISSUE TITLE
Cheshire West and Chester

### ISSUE THREAD

**Issue by clough81** [robbrad/UKBinCollectionData#655]
### Name of Council

Cheshire West and Chester

### Example Address/Postcode

CW8 1DX

### Additional Information

Here is a link to the collection day part of the website. Thanks for developing this great integration!

https://www.cheshirewestandchester.gov.uk/residents/waste-and-recycling/your-bin-collection/collection-day

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by jamescorday** [comment]
Second vote for Cheshire West and Chester.

I see they make use of an api - https://my.cheshirewestandchester.gov.uk/shared/js/api.js

Not sure if that will be helpful or not, I could never work out how to utilise it for form entry.

Thanks

**Comment by dp247** [comment]
Well since there's two of you, I'll prioritise this

**Comment by dp247** [comment]
Parser is done, I'll add it to a PR in a few hours
