### ISSUE TITLE
Please add South Ribble council

### ISSUE THREAD

**Issue by mrjebanks** [robbrad/UKBinCollectionData#671]
### Name of Council

South Ribble Council

### Example Address/Postcode

23 Walnutwood Avenue PR5 6DT

### Additional Information

https://southribble-ss.achieveservice.com/AchieveForms/?mode=fill&form_uri=sandbox-publish%3A//AF-Process-d3971054-2e93-4a74-8375-494347dd13fd/AF-Stage-2693df73-8a5f-4e24-86b8-456ef81dd4a1/definition.json&process=1&process_uri=sandbox-processes%3A//AF-Process-d3971054-2e93-4a74-8375-494347dd13fd&process_id=AF-Process-d3971054-2e93-4a74-8375-494347dd13fd&accept=yes&consentMessageIds[]=3

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by fuzzysb** [comment]
I will add my request here also as i want this council added.

The main site to input post codes and get the bin collection schedule is [here](https://southribble-ss.achieveservice.com/AchieveForms/?mode=fill&form_uri=sandbox-publish%3A//AF-Process-d3971054-2e93-4a74-8375-494347dd13fd/AF-Stage-2693df73-8a5f-4e24-86b8-456ef81dd4a1/definition.json&process=1&process_uri=sandbox-processes%3A//AF-Process-d3971054-2e93-4a74-8375-494347dd13fd&process_id=AF-Process-d3971054-2e93-4a74-8375-494347dd13fd&accept=yes&consentMessageIds[]=3).

I know that this uses similar software to other councils, but i am not well versed, and looks to implemented differently in this council to others when looking at other council scripts?

I had an auth piece [here](https://southribble-ss.achieveservice.com/authapi/isauthenticated?"uri"="https://southribble-ss.achieveservice.com/AchieveForms"&"hostname"="southribble-ss.achieveservice.com"&"withCredentials"="true") i was working on, but could not figure out how to achieve authentication

and i believe [this](https://southribble-ss.achieveservice.com/fillform/scripts/AchieveForms.min.js?v=1705485038923) post request should return my bin schedule, but without authentication first i struggled.

**Comment by OliverCullimore** [comment]
Similar URL to #244
