### ISSUE TITLE
Rugby Borough Council stopped working

### ISSUE THREAD

**Issue by matt0020190** [robbrad/UKBinCollectionData#681]
### Name of Council

Rugby borough council

### Issue Information

For the past week the entities are unavailable stating the integration is no longer providing this information.
I'm running the latest version, is it a council issue?

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by dp247** [comment]
Could you post your log file please?

**Comment by matt0020190** [comment]
This error originated from a custom integration.

Logger: custom_components.uk_bin_collection.sensor
Source: helpers/update_coordinator.py:315
integration: UK Bin Collection Data (documentation, issues)
First occurred: April 16, 2024 at 7:59:29 AM (3 occurrences)
Last logged: April 16, 2024 at 11:59:49 PM

Unexpected error fetching Chapel Street data: 'NoneType' object has no attribute 'find'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/uk_bin_collection/sensor.py", line 133, in _async_update_data
    data = await self.hass.async_add_executor_job(self.ukbcd.run)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 96, in run
    return self.client_code(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 115, in client_code
    return get_bin_data_class.template_method(address_url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 78, in template_method
    bin_data_dict = self.parse_data(
                    ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/councils/RugbyBoroughCouncil.py", line 72, in parse_data
    table_rows = soup.find("table", {"class": "table"}).find("tbody").find_all("tr")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by robbrad** [comment]
Tests are showing a lot of success recently 
![image](https://github.com/user-attachments/assets/2a963d37-0937-4eb4-88c0-44e48e1d6cc1)

@matt0020190 can you share postcode and uprn ?

**Comment by matt0020190** [comment]
> Tests are showing a lot of success recently ![image](https://private-user-images.githubusercontent.com/6122503/365817723-2a963d37-0937-4eb4-88c0-44e48e1d6cc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MTc5OTEsIm5iZiI6MTcyNTkxNzY5MSwicGF0aCI6Ii82MTIyNTAzLzM2NTgxNzcyMy0yYTk2M2QzNy0wOTM3LTRlYjQtODhjMC00NGU0OGUxZDZjYzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDlUMjEzNDUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWYxYjgwMmY5MzdmOWVjZGY4YTgwOGE0Y2MxNGI2MWI4OWI3NDMyN2Y2NDE1ODBkNjM2YTA0OGZmOGM4Zjc4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-5-BQJBFxDK5ppuF7QjWlStaZMeE9A-awoTgldfvmmc)
> 
> @matt0020190 can you share postcode and uprn ?

Hey thanks for the reply

Seems to be working again for the last few months, fixed itself with an update somewhere.

Thanks for a great integration!
