### ISSUE TITLE
Lancs Council 

### ISSUE THREAD

**Issue by DavidJonesTrucker** [robbrad/UKBinCollectionData#688]
### Name of Council

Lancashire County Council 

### Example Address/Postcode

PR9 8DN

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by m26dvd** [comment]
@robbrad @dp247 This was fixed under #986
