### ISSUE TITLE
Council Request

### ISSUE THREAD

**Issue by onslack** [robbrad/UKBinCollectionData#69]
### Name of Council

Mid Sussex District Council

### Example Postcode

RH10 3XD

### Additional Information

https://www.midsussex.gov.uk/waste-recycling/bin-collection/

**Comment by dp247** [comment]
Oh, it's the funny internet number. Nice.

Also since it looks like a web form, gonna stick this link [here](https://www.thepythoncode.com/article/extracting-and-submitting-web-page-forms-in-python) for later.

**Comment by onslack** [comment]
I hadn't even clocked that lol

Is all the info I've supplied sufficient and correct ?

**Comment by dp247** [comment]
> I hadn't even clocked that lol
> 
> Is all the info I've supplied sufficient and correct ?

Excuse my immature brain 🤣 

Yeah, it's all good. I'll have a look in the next few days and see what can be done.

**Comment by onslack** [comment]
> > I hadn't even clocked that lol
> > Is all the info I've supplied sufficient and correct ?
> 
> Excuse my immature brain 🤣
> 
> Yeah, it's all good. I'll have a look in the next few days and see what can be done.

Don't worry my mind is just as immature lol

Awesome, thank you

**Comment by dp247** [comment]
Updated the wiki with some documentation too :3
