### ISSUE TITLE
West Oxfordshire District Council

### ISSUE THREAD

**Issue by Mccwill** [robbrad/UKBinCollectionData#694]
### Name of Council

West Oxfordshire District Council

### Example Address/Postcode

OX281YA

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by spwatson39** [comment]
Any update on this one please?
