### ISSUE TITLE
Luton Council

### ISSUE THREAD

**Issue by Rogertu71** [robbrad/UKBinCollectionData#697]
### Name of Council

Luton Council

### Example Address/Postcode

LU40SL

### Additional Information

https://m.luton.gov.uk/Page/Show/Environment/Rubbish_waste_and_recycling/Pages/Bin-collection.aspx

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by OliverCullimore** [comment]
Potentially also similar to #244
