### ISSUE TITLE
Braintree Council 

### ISSUE THREAD

**Issue by pheufr** [robbrad/UKBinCollectionData#699]
### Name of Council

Braintree 

### Example Address/Postcode

Co5 9BD

### Additional Information

https://www.braintree.gov.uk/xfp/form/554

Entering postcode above and selecting address returns next scheduled days

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by ScrumpyCyder** [comment]
I'd be interested in having Braintree added too :)
