### ISSUE TITLE
Barnsley - all bins showing same date

### ISSUE THREAD

**Issue by parklife200** [robbrad/UKBinCollectionData#713]
### Name of Council

Barnsley

### Issue Information

On Monday all 3 entities were showing as tomorrow, which differed to the actual detail on the council site. 2 of the 3 entites are now showing Next Week: Tuesday and the 3rd entity is unavailable. Only one of the 3 entities (Grey bin) is actually Tuesday next week 
![Screenshot 2024-05-15 142451](https://github.com/robbrad/UKBinCollectionData/assets/148243893/2039dfee-5895-4dcd-a795-cebf990b2083)

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by robbrad** [comment]
Confirmed this is a bug. code changes needed
