### ISSUE TITLE
Request Chesterfield Council

### ISSUE THREAD

**Issue by joesmylie** [robbrad/UKBinCollectionData#718]
### Name of Council

Chesterfield Borough Council

### Example Address/Postcode

S41 0NJ

### Additional Information

https://www.chesterfield.gov.uk/bins-and-recycling/bin-collections/check-bin-collections.aspx

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by Showcase-Joz** [comment]
Pls add
