### ISSUE TITLE
UK Bin Collection Data Entities

### ISSUE THREAD

**Issue by iendicott** [robbrad/UKBinCollectionData#742]
### Home Assistant Version

2024.05.1

### Installation Method

Using HACS

### Name of Council (if relevant)

North Yorkshire Council

### Issue Information

Have noticed that the entities for North Yorkshire Council are not displaying correctly.
They appear to be duplicating the entity names as per screenshot.
I have completely removed the plugin, rebooted and reinstalled. 

![Screenshot 2024-05-28 135506](https://github.com/robbrad/UKBinCollectionData/assets/73525618/c4079016-19a0-4740-aada-cfdc17124ff2)

To get around this for now I have manually renamed the entities in HA.

Regards

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] If trying to add a specific council, I've checked it is listed as working at https://robbrad.github.io/UKBinCollectionData/3.11/
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by robbrad** [comment]
@iendicott can you send me a sample address for this issue? what does it look like on the website when you run it ?

I just tried it for our sample and this is what I get

![image](https://github.com/user-attachments/assets/f674df6e-6ba6-4d55-85a9-9280e4737f18)

**Comment by iendicott** [comment]
Hey @robbrad I should have closed this down sorry. It seems to be working now.
