### ISSUE TITLE
Flintshire County Council/Sir Y Fflint

### ISSUE THREAD

**Issue by ajroberts67** [robbrad/UKBinCollectionData#750]
### Name of Council

Flintshire County Council

### Example Address/Postcode

CH7 3JU

### Additional Information

https://www.flintshire.gov.uk/en/Resident/Bins-Recycling-and-Waste/Check-your-bin-day.aspx

Post Code: CH7 3JU 

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by MarkStocksUK** [comment]
One more vote for Flintshire council. Thanks.

**Comment by MarkStocksUK** [comment]
Just wanted to say thanks for adding Flintshire in so quickly.
