### ISSUE TITLE
Dorset Council

### ISSUE THREAD

**Issue by LiamJMajor** [robbrad/UKBinCollectionData#756]
### Name of Council

Dorset Council

### Issue Information

Dorset council has changed their website to load collection data using JS after page load, so the current scraping method is not operationals, as the data is no on-page at the time of scrape.

Issue occured on the 6th june. [Link to Allure history](https://robbrad.github.io/UKBinCollectionData/3.11/1944/index.html#packages/83edc06c07f9ae9e47eb6dd1b683e4e2/68ff4646db3f329d/history)

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by RobQuincey-DC** [comment]
Rather than scraping the site, you can use our API directly to get the data in JSON format. This has no authentication requirements on it, and provided people use it sensibly it will stay that way.

The URLs you need are

- https://geoapi.dorsetcouncil.gov.uk/v1/services/recyclingday/{uprn}
- https://geoapi.dorsetcouncil.gov.uk/v1/services/refuseday/{uprn}
- https://geoapi.dorsetcouncil.gov.uk/v1/services/foodwasteday/{uprn}
- https://geoapi.dorsetcouncil.gov.uk/v1/services/gardenwasteday/{uprn}
 (if the premise isn't subscribed to garden waste, an empty result will be returned)

Replace {uprn} with the UPRN of the property.

As with any API, this is provided on a best-endeavours basis, and please make sure you don't send too many requests in a short period of time or your request may be blocked.

**Comment by LiamJMajor** [comment]
Thanks Rob, that's incredibly helpful!
I searched for a while but I couldn't find an open endpoint. 

Leaving this open, the above has solved my problem, but the integration is still broken, so this should remain open.

**Comment by dp247** [comment]
> Rather than scraping the site, you can use our API directly to get the data in JSON format. This has no authentication requirements on it, and provided people use it sensibly it will stay that way.
> 
> The URLs you need are
> 
> * [https://geoapi.dorsetcouncil.gov.uk/v1/services/recyclingday/{uprn}](https://geoapi.dorsetcouncil.gov.uk/v1/services/recyclingday/%7Buprn%7D)
> * [https://geoapi.dorsetcouncil.gov.uk/v1/services/refuseday/{uprn}](https://geoapi.dorsetcouncil.gov.uk/v1/services/refuseday/%7Buprn%7D)
> * [https://geoapi.dorsetcouncil.gov.uk/v1/services/foodwasteday/{uprn}](https://geoapi.dorsetcouncil.gov.uk/v1/services/foodwasteday/%7Buprn%7D)
> * [https://geoapi.dorsetcouncil.gov.uk/v1/services/gardenwasteday/{uprn}](https://geoapi.dorsetcouncil.gov.uk/v1/services/gardenwasteday/%7Buprn%7D)
>   (if the premise isn't subscribed to garden waste, an empty result will be returned)
> 
> Replace {uprn} with the UPRN of the property.
> 
> As with any API, this is provided on a best-endeavours basis, and please make sure you don't send too many requests in a short period of time or your request may be blocked.



> Rather than scraping the site, you can use our API directly to get the data in JSON format. This has no authentication requirements on it, and provided people use it sensibly it will stay that way.
> 
> The URLs you need are
> 
> * [https://geoapi.dorsetcouncil.gov.uk/v1/services/recyclingday/{uprn}](https://geoapi.dorsetcouncil.gov.uk/v1/services/recyclingday/%7Buprn%7D)
> * [https://geoapi.dorsetcouncil.gov.uk/v1/services/refuseday/{uprn}](https://geoapi.dorsetcouncil.gov.uk/v1/services/refuseday/%7Buprn%7D)
> * [https://geoapi.dorsetcouncil.gov.uk/v1/services/foodwasteday/{uprn}](https://geoapi.dorsetcouncil.gov.uk/v1/services/foodwasteday/%7Buprn%7D)
> * [https://geoapi.dorsetcouncil.gov.uk/v1/services/gardenwasteday/{uprn}](https://geoapi.dorsetcouncil.gov.uk/v1/services/gardenwasteday/%7Buprn%7D)
>   (if the premise isn't subscribed to garden waste, an empty result will be returned)
> 
> Replace {uprn} with the UPRN of the property.
> 
> As with any API, this is provided on a best-endeavours basis, and please make sure you don't send too many requests in a short period of time or your request may be blocked.

You are my new favorite local government person

**Comment by RobQuincey-DC** [comment]
> Thanks Rob, that's incredibly helpful! I searched for a while but I couldn't find an open endpoint.
> 
> Leaving this open, the above has solved my problem, but the integration is still broken, so this should remain open.

Its not advertised, and before the change that broke the scraper it didn't even use the API and did it all behind the scenes hidden away, but there's no reason not to make it available!

> You are my new favorite local government person

I'm honoured!
