### ISSUE TITLE
Please add London Borough of Havering

### ISSUE THREAD

**Issue by Hockieknockie** [robbrad/UKBinCollectionData#769]
### Name of Council

London Borough of Havering

### Example Address/Postcode

36 Junction Road RM1 3QR

### Additional Information

https://portal.havering.gov.uk/Process-Waste-CollectionDays/?type=CD&uprn=100021380730&usrn=21301312

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by AntJames96** [comment]
Expressing interest in this council.
