### ISSUE TITLE
Sefton council requested please 

### ISSUE THREAD

**Issue by pmbrady** [robbrad/UKBinCollectionData#770]
### Name of Council

Sefton

### Example Address/Postcode

L20 6GG

### Additional Information

https://www.sefton.gov.uk/bins-and-recycling/bins-and-recycling/when-is-my-bin-collection-day/

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by Mwalton4uk** [comment]
Has this one been added?

**Comment by robbrad** [comment]
> Has this one been added?

Not yet https://github.com/robbrad/UKBinCollectionData/tree/master/uk_bin_collection/uk_bin_collection/councils
