### ISSUE TITLE
Chelmsford Council stopped working

### ISSUE THREAD

**Issue by Johnyb62** [robbrad/UKBinCollectionData#772]
### Name of Council

Chelmsford Council

### Issue Information

Home Assistant Version (core)
:  2024.7.3

Installation Method
: Using HACS
Release: [0.83.0]

Name of Council (if relevant)
: Chelmsford Council

Issue Information
 Looks like its timing out in the logs:

```
Logger: homeassistant.components.sensor
Source: runner.py:190
integration: Sensor (documentation, issues)
First occurred: 2:52:43 PM (1 occurrences)
Last logged: 2:52:43 PM
Setup of sensor platform uk_bin_collection is taking over 10 seconds.

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:408
integration: Sensor (documentation, issues)
First occurred: 2:53:33 PM (1 occurrences)
Last logged: 2:53:33 PM
Setup of platform uk_bin_collection is taking longer than 60 seconds. Startup will proceed without waiting any longer.

```
Logs from Standalone Chrome Docker:

`Starting Selenium Grid Standalone...
Tracing is disabled
14:52:01.211 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
14:52:01.230 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
14:52:02.895 INFO [NodeOptions.getSessionFactories] - Detected 4 available processors
14:52:02.960 INFO [NodeOptions.report] - Adding chrome for {"browserName": "chrome","browserVersion": "126.0","goog:chromeOptions": {"binary": "\u002fusr\u002fbin\u002fgoogle-chrome"},"platformName": "linux","se:noVncPort": 7900,"se:vncEnabled": true} 1 times
14:52:03.013 INFO [Node.<init>] - Binding additional locator mechanisms: relative
14:52:03.070 INFO [GridModel.setAvailability] - Switching Node 898cfd87-45e3-433f-8cce-6dbc98ad1cd1 (uri: http://172.17.0.2:4444) from DOWN to UP
14:52:03.071 INFO [LocalDistributor.add] - Added node 898cfd87-45e3-433f-8cce-6dbc98ad1cd1 at http://172.17.0.2:4444. Health check every 120s
14:52:03.266 INFO [Standalone.execute] - Started Selenium Standalone 4.22.0 (revision c5f3146703): http://172.17.0.2:4444
14:52:33.576 INFO [LocalDistributor.newSession] - Session request received by the Distributor: 
 [Capabilities {browserName: chrome, goog:chromeOptions: {args: [--headless, --no-sandbox, --disable-gpu, --start-maximized, --disable-dev-shm-usage], excludeSwitches: [enable-logging], extensions: []}, pageLoadStrategy: normal, se:name: ChelmsfordCityCouncil}]
14:52:35.824 INFO [LocalNode.newSession] - Session created by the Node. Id: a8c0e28cf6db84ed17123ce8e8194efb, Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome-headless-shell, browserVersion: 126.0.6478.114, chrome: {chromedriverVersion: 126.0.6478.63 (df799988fdc9..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:35911}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://172.17.0.2:4444/sessio..., se:cdpVersion: 126.0.6478.114, se:name: ChelmsfordCityCouncil, se:vnc: ws://172.17.0.2:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.17.0.2:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
14:52:35.829 INFO [LocalDistributor.newSession] - Session created by the Distributor. Id: a8c0e28cf6db84ed17123ce8e8194efb 
 Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome-headless-shell, browserVersion: 126.0.6478.114, chrome: {chromedriverVersion: 126.0.6478.63 (df799988fdc9..., userDataDir: /tmp/.org.chromium.Chromium...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:35911}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:bidiEnabled: false, se:cdp: ws://172.17.0.2:4444/sessio..., se:cdpVersion: 126.0.6478.114, se:name: ChelmsfordCityCouncil, se:vnc: ws://172.17.0.2:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.17.0.2:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
14:53:54.873 INFO [LocalSessionMap.lambda$new$0] - Deleted session from local Session Map, Id: a8c0e28cf6db84ed17123ce8e8194efb
14:53:54.873 INFO [GridModel.release] - Releasing slot for session id a8c0e28cf6db84ed17123ce8e8194efb
14:53:54.874 INFO [SessionSlot.stop] - Stopping session a8c0e28cf6db84ed17123ce8e8194efb`

Here's a test URL for a random property in my area that could be used for testing (link obtained prior to posting):-
https://www.chelmsford.gov.uk/myhome/?entry[655e95fb-5f84-4d1b-ab65-878a2f3e3ce4]=66366413 

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by Johnyb62** [comment]
Think the issue may be server side with Council, as using action 'Home Assistant Core Integration: Reload config entry' will result in the entities working (after a few attempts).  So probably little you can do.

**Comment by robbrad** [comment]
There is an option to change the time of refresh- choose a time to refresh that makes more sense for the council

**Comment by Johnyb62** [comment]
I've just realised there is another way to obtain the schedule for Chelmsford.  Rather than searching via https://www.chelmsford.gov.uk/myhome/, there is a page (https://www.chelmsford.gov.uk/bins-and-recycling/check-your-collection-day/) that shows the collection rounds (eg Tuesday A / Tuesday B).  Would this be a simpler implementation (and overcome some of the delays I get because myhome has been so slow for ages.
Just a thought.
