### ISSUE TITLE
Please add Newcastle-under-Lyme Council

### ISSUE THREAD

**Issue by ALeXXBody** [robbrad/UKBinCollectionData#778]
### Name of Council

Newcastle-under-Lyme Borough Council

### Example Address/Postcode

ST58QX

### Additional Information

https://www.newcastle-staffs.gov.uk/homepage/97/check-your-bin-day

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by SamForster78** [comment]
Expressing interest in this council request!
