### ISSUE TITLE
Calderdale Council Stopped Working - HA Reporting error and asking to make a bug report

### ISSUE THREAD

**Issue by LostkingZ** [robbrad/UKBinCollectionData#779]
### Home Assistant Version

2024.7.4

### Installation Method

Using HACS

### Name of Council (if relevant)

Calderdale Council

### Issue Information

Hi,

The application has stopped working recently and doesn't seem to be able to get any results for my council (Calderdale Council) (Tested and still working for Rochdale Council though).

When looking at the logs I can see this error:

`2024-08-02 04:03:25.794 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'uk_bin_collection' calls async_forward_entry_setups for integration uk_bin_collection with title: Tod and entry_id: 01J48GNC87FV99PC0XKMJTAM3C, during setup without awaiting async_forward_entry_setups, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1 at custom_components/uk_bin_collection/__init__.py, line 35: await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS), please create a bug report at https://github.com/robbrad/UKBinCollectionData/issues`

I am using the following info to get the entities:

UPRN: 010035034598

Postcode: OL14 7EX

Any and all help would be much appreciated.

Debug Mode Log File:
[home-assistant_uk_bin_collection_2024-08-02T03-08-48.531Z.log](https://github.com/user-attachments/files/16464796/home-assistant_uk_bin_collection_2024-08-02T03-08-48.531Z.log)

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] If trying to add a specific council, I've checked it is listed as working at https://robbrad.github.io/UKBinCollectionData/3.11/
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by LostkingZ** [comment]
Looks like this just started working again so I am closing this off for now although the following error is still a cause for concern

**Comment by robbrad** [comment]
Thanks @LostkingZ 

I have raised a PR for this - need to test it a little more and ill release it
