### ISSUE TITLE
Chorley Council - uk_bin_collection raises exception ConfigEntryNotReady

### ISSUE THREAD

**Issue by dannymcc** [robbrad/UKBinCollectionData#786]
### Name of Council

Chorley Council

### Issue Information

When adding the integration for the first time, and adding the configuration options Chorley Council, I am getting an error of `uk_bin_collection raises exception ConfigEntryNotReady` when adding the config.

I have also attempted to run this locally on macOS with the following command:

`python3 collect_data.py ChorleyCouncil https://myaccount.chorley.gov.uk/wastecollections.aspx -s -u 10091495446 -p "PR7 4QE" -w http://10.10.10.75:4444/`

Which returned the following error:

`TypeError: create_webdriver() takes from 0 to 3 positional arguments but 4 were given`
[home-assistant_uk_bin_collection_2024-08-23T13-45-18.854Z.log](https://github.com/user-attachments/files/16729623/home-assistant_uk_bin_collection_2024-08-23T13-45-18.854Z.log)

Here's the config options I chose in the frontend:

![CleanShot 2024-08-23 at 14 51 48@2x](https://github.com/user-attachments/assets/10c130f7-1985-4f59-ac5d-09b735f03fc9)

![CleanShot 2024-08-23 at 14 52 38@2x](https://github.com/user-attachments/assets/b40e7ea1-e959-4a26-856c-8040a140c9ab)

![CleanShot 2024-08-23 at 14 52 55@2x](https://github.com/user-attachments/assets/f3accd79-e8cd-47be-8547-0395d6ccf9f1)

Which does start a headless chrome session:

![CleanShot 2024-08-23 at 14 53 08@2x](https://github.com/user-attachments/assets/71f6aa8a-df69-4dae-89e0-e0852dfe5424)

![CleanShot 2024-08-23 at 14 53 44@2x](https://github.com/user-attachments/assets/3e7b1e48-103b-487a-a8a2-4898d97beb2b)

![CleanShot 2024-08-23 at 14 54 12@2x](https://github.com/user-attachments/assets/b78e1e2a-cdd5-4df2-b3bd-7031bf181ca4)

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by robbrad** [comment]
Hi @dannymcc 

Firstly you need to get the correct UPRN from the Chorley page

I can see your using 10091495446 but it must be formatted like UPRN10091495446 

I also found your UPRN is not in the list for that postcode see:

![image](https://github.com/user-attachments/assets/8bfb0478-096a-4489-8919-81cf490c29c9)

As for the error the Chorley website is taking longer than 60 seconds to load and Home Assistant is giving up on the startup. I could bump this to more, but can you please try the UPRN change and leave it for a bit to see if it improves?

If you want to run manually from macOS the correct command is (this worked for me)

`python3 collect_data.py ChorleyCouncil https://myaccount.chorley.gov.uk/wastecollections.aspx -s -u <UPRN_NUM> -p "PR7 4QE" -w "http://<SELENIUM_IP>:4444"`

Make sure you can hit Selenium from the Home Assistant Server http://<SELENIUM_IP>:4444

You can also try without Selenium remote and try using the Selenium with the local Chrome

`python3 collect_data.py ChorleyCouncil https://myaccount.chorley.gov.uk/wastecollections.aspx -s -u <UPRN_NUM> -p "PR7 4QE" --local_browser`

**Comment by robbrad** [comment]
Looks like the Wiki needs to call this out

Also need to update the command line flags i nthe readme.md

**Comment by dannymcc** [comment]
Thanks for the pointer on the UPRN. 

After correcting the value, I am still seeing the same issue. The session does begin in Selenium which leave me to believe it's a timeout issue. 

Is there a config setting I can edit locally to extend the timeout?

**Comment by robbrad** [comment]
@dannymcc - that's a great suggestion.

Let me make that a configurable item.

You'll notice I added a "reconfigure" option in the latest version of the custom component

**Comment by dannymcc** [comment]
The reconfigure option works perfectly and saves a lot of time when troubleshooting. Thanks for adding that!

Thanks also for your assistance on this!

**Comment by robbrad** [comment]
> The reconfigure option works perfectly and saves a lot of time when troubleshooting. Thanks for adding that!
> 
> Thanks also for your assistance on this!

@dannymcc I have added a sensor timeout option to the config.

I tried this for Chorley and found 300 seconds to work 

Can you give it a try?

**Comment by dannymcc** [comment]
This worked perfectly! The combination of the updated UPRN and the increased timeout (I bumped it to 800 just to be on the safe side) did the job.

Thank you!

**Comment by raldred** [comment]
Thanks for the fix @robbrad.
Chorley changed their site, it's definitely gotten more flakey.
