### ISSUE TITLE
Error: Early warning 'will stop working in Home Assistant 2025.1' : async_forward_entry_setups

### ISSUE THREAD

**Issue by Johnyb62** [robbrad/UKBinCollectionData#788]
### Home Assistant Version

2024.8.3

### Installation Method

Using HACS

### Name of Council (if relevant)

Chelmsford Council

### Issue Information

Error in logs claims integration may stop working after 2025.1
Probably something already aware of but raised just in case. thanks

```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:184
First occurred: 3:02:16 AM (2 occurrences)
Last logged: 2:02:49 PM

Detected that custom integration 'uk_bin_collection' calls async_forward_entry_setups for integration uk_bin_collection with title: H and entry_id: xxxxx, during setup without awaiting async_forward_entry_setups, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1 at custom_components/uk_bin_collection/__init__.py, line 35: await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS), please create a bug report at https://github.com/robbrad/UKBinCollectionData/issues
```

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] If trying to add a specific council, I've checked it is listed as working at https://robbrad.github.io/UKBinCollectionData/3.11/
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by robbrad** [comment]
#779 duplicate

**Comment by Johnyb62** [comment]
Apologies.  I'll close

**Comment by robbrad** [comment]
No worries @Johnyb62.

Iv been delaying this one as long as possible just want to ensure compatibility
