### ISSUE TITLE
Wakefield Council

### ISSUE THREAD

**Issue by nytram-md** [robbrad/UKBinCollectionData#8]
Hi

Any chance of getting Wakefield Council added please ?

Thanks

Martyn

**Comment by nytram-md** [comment]
https://www.wakefield.gov.uk/site/where-i-live?#

Eg Post Code WF6 2de

**Comment by robbrad** [comment]
Added in : 
https://github.com/robbrad/UKBinCollectionData/commit/91a60329cb629c3dcb12b3cd310e8a0f73c1f287

**Comment by nytram-md** [comment]
Hi. Thanks very much. Ill have a look at this straight away.

I guess the garden bin will auto populate again when they re-add the collection as its currently been stopped because of COVID19 ?

Thanks again

Martyn

**Comment by robbrad** [comment]
Yeh should do !

**Comment by cbarratt** [comment]
Was glad to find this already here! Just a random one guys, has anyone got this working with the template sensors in Home Assistant at all? if so please post :D

**Comment by nytram-md** [comment]
> Was glad to find this already here! Just a random one guys, has anyone got this working with the template sensors in Home Assistant at all? if so please post :D

Hi

Did you ever get this into home assistant?

Never got this working and went down the route of a calendar but would love to get working with home assistant if possible.

👍
