### ISSUE TITLE
Integration for Windsor and Maidenhead stopped working

### ISSUE THREAD

**Issue by Duff-Box1** [robbrad/UKBinCollectionData#805]
### Name of Council

Windsor and Maidenhead

### Issue Information

This custom integration used to work perfectly and now does not retrieve the data.
Seems to return fields that are empty, but the website works perfectly for manually retrieved dates.
![IMG_0733](https://github.com/user-attachments/assets/9de7f907-c3e3-45d9-acdb-f5a61b648563)

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by robbrad** [comment]
@Duff-Box1 : Council has changed their website.

Intergration Test Failing: ![image](https://github.com/user-attachments/assets/ae0d5882-cc85-42b3-af96-fa7eb5e6a74f)
![image](https://github.com/user-attachments/assets/2b375d02-4f3f-4a52-9af6-30f0d5b5e307)

This will need reworking

What URL are you using on the manual retrieve?

**Comment by Duff-Box1** [comment]
Hi website at rbwm collection lookup is https://forms.rbwm.gov.uk/bincollections?_gl=1*1lool7p*_ga*OTM5NTE1MDAxLjE3MTk0MDI5NzM.*_ga_B1S76ZFQXK*MTcyNTg2MTg1My41LjEuMTcyNTg2MTg2NS4wLjAuMA..

**Comment by robbrad** [comment]
Had a quick look its going to need a rework - potenitally Selenium
