### ISSUE TITLE
London borough Ealing

### ISSUE THREAD

**Issue by ratajdamian** [robbrad/UKBinCollectionData#811]
### Name of Council

Ealing Council

### Example Address/Postcode

UB54DU

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by dp247** [comment]
Duplicates #758
