### ISSUE TITLE
Requesting Colchester (again) please

### ISSUE THREAD

**Issue by Stig2k** [robbrad/UKBinCollectionData#812]
### Name of Council

Colchester City Council

### Example Address/Postcode

CO2 8UN

### Additional Information

I apologise @dp247.
I'm very new to this and had no idea that you had responded to my initial request for adding Colchester Council.
Is it too late for me to ask again?

https://www.colchester.gov.uk/your-recycling-calendar/?start=true&step=1&llpgid=28bfa980-3c27-e711-80fa-5065f38b5681

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by dp247** [comment]
Oh, sorry I forgot to respond on the ticket lol. The request is still open as #639, so it'll be done sometime. I think I asked a question there, so if you reply, it can be coded.
