### ISSUE TITLE
Blackburn With Darwen borough council 

### ISSUE THREAD

**Issue by Zaid2303** [robbrad/UKBinCollectionData#821]
### Name of Council

Blackburn With Darwen borough council 

### Example Address/Postcode

bb1 7ef

### Additional Information

https://mybins.blackburn.gov.uk/

thats their bins link

Also ty

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by robbrad** [comment]
@dp247 this is the 3rd one I have found where people are requesting Councils that are already in there - could this be a gap in the Wiki ? eg matbe each council doesnt have a wiki entry

**Comment by robbrad** [comment]
Maybe not - I see all entries in the wiki

**Comment by raldred** [comment]
@robbrad I think you can safely close this.

The current parser is working fine

```
uk-bin-collection-kIu0SI8M-py3.12 ❯ python collect_data.py BlackburnCouncil https://www.blackburn.gov.uk -s -u XXXXXXX -w http://192.168.86.15:4444
{
    "bins": [
        {
            "type": "Burgundy 240L (refuse bin)",
            "collectionDate": "12/11/2024"
        },
        {
            "type": "Burgundy 240L (refuse bin)",
            "collectionDate": "12/11/2024"
        },
        {
            "type": "Blue 240L (paper and cardboard bin)",
            "collectionDate": "19/11/2024"
        },
        {
            "type": "Grey 240L (glass, tins and plastics bin)",
            "collectionDate": "03/12/2024"
        }
    ]
}
```

**Comment by dp247** [comment]
> @robbrad I think you can safely close this.
> 
> The current parser is working fine
> 
> ```
> uk-bin-collection-kIu0SI8M-py3.12 ❯ python collect_data.py BlackburnCouncil https://www.blackburn.gov.uk -s -u XXXXXXX -w http://192.168.86.15:4444
> {
>     "bins": [
>         {
>             "type": "Burgundy 240L (refuse bin)",
>             "collectionDate": "12/11/2024"
>         },
>         {
>             "type": "Burgundy 240L (refuse bin)",
>             "collectionDate": "12/11/2024"
>         },
>         {
>             "type": "Blue 240L (paper and cardboard bin)",
>             "collectionDate": "19/11/2024"
>         },
>         {
>             "type": "Grey 240L (glass, tins and plastics bin)",
>             "collectionDate": "03/12/2024"
>         }
>     ]
> }
> ```

Thanks for confirming 😄

**Comment by raldred** [comment]
The only thing I could think in this case is the person searched for Darwen, so maybe updating the Wiki entry to "Blackburn with Darwen"?
