### ISSUE TITLE
Council Request - Royal Borough of Greenwich

### ISSUE THREAD

**Issue by adamlynes** [robbrad/UKBinCollectionData#836]
### Name of Council

Royal Borough of Greenwich

### Example Address/Postcode

SE7 7RL

### Additional Information

https://www.royalgreenwich.gov.uk/info/200171/recycling_and_rubbish/100/find_your_bin_collection_day

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by xATL4S** [comment]
+1 for interest
