### ISSUE TITLE
South Derbyshire District Council

### ISSUE THREAD

**Issue by ins4neuk** [robbrad/UKBinCollectionData#842]
### Name of Council

South Derbyshire District Council

### Example Address/Postcode

de11 7nz

### Additional Information

https://www.southderbyshire.gov.uk/our-services/recycling-bins-and-waste/bin-collection-dates

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by ins4neuk** [comment]
you sir are a legend... how fast was that

**Comment by robbrad** [comment]
All kudos to @m26dvd - contributor of the month!!

@ins4neuk
