### ISSUE TITLE
Hartlepool Borough Council

### ISSUE THREAD

**Issue by djjoereece94** [robbrad/UKBinCollectionData#844]
### Name of Council

Hartlepool Borough Council

### Example Address/Postcode

TS25 4NE

### Additional Information

https://online.hartlepool.gov.uk/service/Refuse_and_recycling___check_bin_day

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by tally1230** [comment]
Can I express interest in this as well please. Thanks
