### ISSUE TITLE
London Borough of Lewisham

### ISSUE THREAD

**Issue by Sir-Gavin** [robbrad/UKBinCollectionData#858]
### Name of Council

London Borough of Lewisham 

### Example Address/Postcode

SE12 9QF

### Additional Information

UPRN: 100021954849

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by Firefishy** [comment]
https://lewisham.gov.uk/myservices/recycling-and-rubbish/your-bins/collection
