### ISSUE TITLE
Add council Northumberland 

### ISSUE THREAD

**Issue by tonypreece2384** [robbrad/UKBinCollectionData#861]
### Name of Council

Northumberland county council

### Example Address/Postcode

NE24  3PR

### Additional Information

https://www.northumberland.gov.uk/Waste.aspx

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by robbrad** [comment]
@tonypreece2384  : Isn't this covered already? https://github.com/robbrad/UKBinCollectionData/blob/master/uk_bin_collection/uk_bin_collection/councils/NorthumberlandCouncil.py

**Comment by kieranlittle667** [comment]
@tonypreece2384 I'm already using this in HA, .. you will need to use a web driver e.g. https://hub.docker.com/r/selenium/standalone-chrome

**Comment by tonypreece2384** [comment]
Thanks for that, I will have to find out how to do this, very new at HA and no idea how to do most things yet.

Thanks again

Tony
