### ISSUE TITLE
Requesting North Ayrshire Council

### ISSUE THREAD

**Issue by celestial69** [robbrad/UKBinCollectionData#869]
### Name of Council

North Ayrshire

### Example Address/Postcode

KA11 1HE

### Additional Information

https://www.north-ayrshire.gov.uk/bins-litter-and-recycling/bin-collection-days

They do allow a calendar download etc. so could be used perhaps as a source, having it in the plugin would be handy.

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by gavyb** [comment]
@robrad can I please request that this issue be reopened. I have tried an address in the council area which does not provide a valid response, but accessing via the web site does provide a valid response.

**Comment by dp247** [comment]
> @robbrad can I please request that this issue be reopened. I have tried an address in the council area which does not provide a valid response, but accessing via the web site does provide a valid response.

Please raise a new issue, providing your HA logs
