### ISSUE TITLE
Add Westmorland and Furness Council

### ISSUE THREAD

**Issue by rickitoy** [robbrad/UKBinCollectionData#870]
### Name of Council

Westmorland and Furness Council

### Example Address/Postcode

24 LA23 2EX

### Additional Information

Link below to the council site that uses UPN now after the recent merges

https://www.westmorlandandfurness.gov.uk/bins-recycling-and-street-cleaning/waste-collection-schedule/view/100110353478

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by ElliotGraham94** [comment]
For houses that were originally part of Eden district council, but are now westmorland - this does not work

https://www.westmorlandandfurness.gov.uk/bins-recycling-and-street-cleaning/bin-collections/check-your-bin-collection-day

Any Eden based UPRNs return an error stating that the address can not be found. It looks manually like the way to access Eden area collection days is done through visiting https://my.eden.gov.uk/myeden.aspx#Refuse_and_Recycling

**Comment by m26dvd** [comment]
@QuirkyTurtle94 if you raise a new council request, I can have a look at it when I have time

I know technically Eden isn't the council anymore but it's still technically a separate site so will need a separate scraper to be built
