### ISSUE TITLE
Request for council : Rotherham Bourugh Council

### ISSUE THREAD

**Issue by Andy8912** [robbrad/UKBinCollectionData#879]
### Name of Council

Rotherham Bourugh Council 

### Example Address/Postcode

S25 2LE

### Additional Information

https://www.rotherham.gov.uk/bin-collections

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by robbrad** [comment]
@Andy8912 : sorry if im missing something but isnt Rotherham already in there ?

https://github.com/robbrad/UKBinCollectionData/blob/master/uk_bin_collection/uk_bin_collection/councils/RotherhamCouncil.py

**Comment by Andy8912** [comment]
ApologiesSent from my iPhone Vom iPhone gesendet On 13 Oct 2024, at 08:50, Robert Bradley ***@***.***> wrote:﻿
@Andy8912 : sorry if im missing something but isnt Rotherham already in there ?
https://github.com/robbrad/UKBinCollectionData/blob/master/uk_bin_collection/uk_bin_collection/councils/RotherhamCouncil.py
