### ISSUE TITLE
Request: East Riding of Yorkshire council

### ISSUE THREAD

**Issue by colinhatfield** [robbrad/UKBinCollectionData#881]
### Name of Council

East Riding of Yorkshire council

### Example Address/Postcode

Cherry Avenue, HU13 0QT

### Additional Information

https://www.eastriding.gov.uk/environment/bins-rubbish-recycling/bins-and-collections/bin-collection-dates/
https://downloads.eastriding.org.uk/corporate/bin-collection-dates/Calendars2024/2d.pdf

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by robbrad** [comment]
EastRiding is already in there but its failing so marked as a bug - this needs to be fixed as the council changed the website again
