### ISSUE TITLE
Carmarthenshire County Council

### ISSUE THREAD

**Issue by ryaaanmorgan** [robbrad/UKBinCollectionData#892]
### Name of Council

Carmarthenshire County Council

### Example Address/Postcode

78 College Street, Ammanford, SA18 2BR.

### Additional Information

https://www.carmarthenshire.gov.wales/council-services/recycling-bins-and-litter/recycling-bin-collections/

There is button to select garden waste - which I regularly check.

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by Codiwr** [comment]
Ditto. Also please include for Hygeine Waste tickbox as per garden waste. Many thanks!
