### ISSUE TITLE
Edinburgh council

### ISSUE THREAD

**Issue by keirlawson** [robbrad/UKBinCollectionData#894]
### Name of Council

City of Edinburgh Council

### Example Address/Postcode

Lasswade Road

### Additional Information

Calendars can be found here: https://www.edinburgh.gov.uk/directory/10251/recycling-and-waste-bin-collections-2022

However they appear to only have PDFs available so not sure it will be possible

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by Scott-Gardner** [comment]
I am also interested in this for Edinburgh

**Comment by rholligan** [comment]
+1

**Comment by m26dvd** [comment]
This one is similar to Babergh Council in that the local authority only provides PDF collection schedules that are difficult to parse.
Instead, I have attempted to predict the correct schedule based on being provided the DAY and WEEK or collection, i.e. Thursday/Week2
This should be provided in the postcode and house number fields as a workaround
