### ISSUE TITLE
Add Watford council

### ISSUE THREAD

**Issue by ianperrin** [robbrad/UKBinCollectionData#902]
### Name of Council

Watford Borough Council

### Example Address/Postcode

WD17 4RD

### Additional Information

https://watfordbc-self.achieveservice.com/service/Bin_collections

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by LAS2014** [comment]
hi , I'm also interested in having Watford added please
