### ISSUE TITLE
Amending EastDevonDC URL

### ISSUE THREAD

**Issue by embrsword** [robbrad/UKBinCollectionData#905]
### Name of Council

East Devon District Council

### Issue Information

Url has changed

Previous
https://eastdevon.gov.uk/recycling-waste/recycling-and-waste-information/when-is-my-bin-collected/future-collections-calendar/?UPRN=XXXXXXXXXXXX

Now
https://eastdevon.gov.uk/recycling-and-waste/recycling-waste-information/when-is-my-bin-collected/future-collections-calendar/?UPRN=XXXXXXXXXXXX

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by robbrad** [comment]
You can just reconfigure the intergration yourself in the HA UI and change it

![image](https://github.com/user-attachments/assets/b46a5936-ff61-41ca-942d-19b452403591)

**Comment by robbrad** [comment]
Also looks like this was fixed in this commit 

https://github.com/robbrad/UKBinCollectionData/commit/496397a9cffc37f144891d991432fa421581d61a

Please update

**Comment by embrsword** [comment]
Already corrected in my own setup

I was just feeding back on the url change so that information in the wiki is current, it still shows the older url

**Comment by robbrad** [comment]
> Already corrected in my own setup
> 
> 
> 
> I was just feeding back on the url change so that information in the wiki is current, it still shows the older url

Thank you 🙏
