### ISSUE TITLE
Matrix build and publish to GH pages causes git clash

### ISSUE THREAD

**Issue by robbrad** [robbrad/UKBinCollectionData#91]
When a matrix build happens on multiple versions of python they clash publishing the allure reports

Behave runs on one version of python and then on the other - causing a git race condition

**Comment by robbrad** [comment]
Not really sure how to fix this.

Options:
A. Publish as distinct features (though they are still different allure reports)
B. Feature to combine Allure reports?
C. Ditch matrix builds
D. Feature in GHPages action to publish to different build ids

**Comment by robbrad** [comment]
fixed in #91

**Comment by dp247** [comment]
Was it option E?

**Comment by robbrad** [comment]
Basically found some functionality in allure reports to publish to sub directories.

So now the GH pages has the 
base_url/python_version/jobid

Instead of base_url/job_id

Which I feel makes more sense as it's kinda a separate run env all together.

Option F. Is where it really got interesting 💥💣
