### ISSUE TITLE
Swale borough council producing an error (may just be Selenium in general or my install)

### ISSUE THREAD

**Issue by Chewbacca222222** [robbrad/UKBinCollectionData#911]
### Name of Council

Swale borough council 

### Issue Information

When setting up the integration with HACS I get the following error in the logs. To note I've tried completely removing and re-installing.

```
This error originated from a custom integration.

Logger: custom_components.uk_bin_collection.sensor
Source: helpers/update_coordinator.py:354
integration: UK Bin Collection Data (documentation, issues)
First occurred: 23:14:14 (3 occurrences)
Last logged: 23:15:45

Unexpected error fetching Home data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/uk_bin_collection/sensor.py", line 163, in _async_update_data
    data = await self.hass.async_add_executor_job(self.ukbcd.run)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 101, in run
    return self.client_code(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 121, in client_code
    return get_bin_data_class.template_method(address_url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 61, in template_method
    bin_data_dict = self.get_and_parse_data(this_url, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 84, in get_and_parse_data
    bin_data_dict = self.parse_data("", url=address_url, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/councils/SwaleBoroughCouncil.py", line 32, in parse_data
    driver = create_webdriver(web_driver, headless, None, __name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/common.py", line 325, in create_webdriver
    return webdriver.Chrome(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 101, in start
    self._start_process(self._path)
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 211, in _start_process
    self.process = subprocess.Popen(
                   ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/root/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver'
```

I apologise in advance if I've missed something obvious in the readme but as far as I can tell everything should be correct!

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by robbrad** [comment]
@Chewbacca222222 : it looks like its trying to use the local Chrome of your HA server. What did you set the URL to for Selenium when you set it up ? Can you hit Selenium from your machine, what url did you use?

This needs to be a selenium url the HA server can "hit" eg: http://192.168.0.1:4444 or if selenium is running locally on the same server as HA then http://localhost:4444

**Comment by Chewbacca222222** [comment]
> @Chewbacca222222 : it looks like its trying to use the local Chrome of your HA server. What did you set the URL to for Selenium when you set it up ? Can you hit Selenium from your machine, what url did you use?
> 
> This needs to be a selenium url the HA server can "hit" eg: http://192.168.0.1:4444 or if selenium is running locally on the same server as HA then http://localhost:4444
> 
> 

Yep my bad sorry, should have read the docs more closely. I'll get selenium installed and try it out and maybe make a PR for updating the readme?

**Comment by robbrad** [comment]
Thank you @Chewbacca222222 that would be amazing. Have a look at this :  https://github.com/robbrad/UKBinCollectionData?tab=readme-ov-file#selenium See if this can be improved at all ?

**Comment by Chewbacca222222** [comment]
> Thank you @Chewbacca222222 that would be amazing. Have a look at this :  https://github.com/robbrad/UKBinCollectionData?tab=readme-ov-file#selenium See if this can be improved at all ?

Doh, embarrassingly I needed to read the docs in more detail yet again! I have a few ideas to make it a little more simple to read but I'll pop them in a PR when I get a minute!

**Comment by robbrad** [comment]
There is another option if you can get chrome installed on the HA server then you don't need a Selenium as a Docker container - the Python Selenium will just use the local chrome if the url on the custom component is left blank (like you initially did)

# How to Install `chromedriver` on Linux

To resolve the error regarding the missing `/root/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver`, follow these steps:

## Step 1: Install Chrome Browser (if not already installed)
First, ensure that Google Chrome is installed on your system since `chromedriver` needs to match your Chrome browser version.

### Ubuntu/Debian:
```bash
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install ./google-chrome-stable_current_amd64.deb
```

### Fedora/CentOS:

```bash

sudo dnf install fedora-workstation-repositories
sudo dnf config-manager --set-enabled google-chrome
sudo dnf install google-chrome-stable
```
