### ISSUE TITLE
Barnsley Metropolitan Borough Council - some bins are "doubled up"

### ISSUE THREAD

**Issue by ezramorris** [robbrad/UKBinCollectionData#918]
### Name of Council

Barnsley Metropolitan Borough Council

### Issue Information

In Barnsley (or at least some areas), in the summer the cycle works as Grey bin, Blue & Green bins, Grey bin, Brown & Green bins.

The integration, when set up, is picking up the next 2-bin cycle as one bin as well as a separate Green bin, i.e. if the next bins are Brown & Green, it will create 4 bins "Grey bin", "Blue bin", "Green bin", "Brown, Green bin"

I would expect there to be one device for each bin, i.e. a "Brown bin" device, not a "Brown, Green bin" device. If they happen to be the same day, so be it.

I'm not sure yet what will happen in the week where Blue & Green bins are on, or in the winter when there is no Green bin and it gets round to Brown.

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by ezramorris** [comment]
![Screenshot 2024-10-22 001717](https://github.com/user-attachments/assets/13fe3f5d-4253-47ee-845c-c9e0730b25e9)

**Comment by robbrad** [comment]
@ezramorris can you share the data from under these bins ? What's in the attribute value from under the combined bin?

**Comment by ezramorris** [comment]
Hi @robbrad

Here is the attribute data from the brown, green combined bin (note the colour is set by me):
```yaml
colour: brown
next_collection: 22/10/2024
days: 0
device_class: bin_collection_schedule
icon: mdi:delete
friendly_name: <redacted location name> Brown, Green bin
```

And here is the raw json:
```json
{"Brown, Green bin": "22/10/2024", "Grey bin": "29/10/2024", "Blue bin": "05/11/2024", "Green bin": "05/11/2024"}
```

**Comment by robbrad** [comment]
@ezramorris thank you

I know why this is happening - this is the raw json from the export and it's where to make that available 

I need to have a think about how that's represented in the front end

**Comment by ezramorris** [comment]
I had some time to investigate this today. There is logic in place which splits the bin string for upcoming collections but not next collection. Raised PR with fix.
