### ISSUE TITLE
Woking Borough Council/JWS

### ISSUE THREAD

**Issue by wrighty001** [robbrad/UKBinCollectionData#938]
### Name of Council

Woking Borough Council 

### Issue Information

Set the integration up yesterday and was working fine but today it is now showing unavailable after a 'change to 2' 15hrs ago 

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by robbrad** [comment]
Can you supply any logs from home assistant?

**Comment by wrighty001** [comment]
Sorry new to the HA world still - is this sufficient?

**Comment by wrighty001** [comment]
[Error log.docx](https://github.com/user-attachments/files/17588773/Error.log.docx)

**Comment by wrighty001** [comment]
this mornings update appears to have resolved the issue :-)
