### ISSUE TITLE
Unit test broken

### ISSUE THREAD

**Issue by robbrad** [robbrad/UKBinCollectionData#94]
Root folder in unit test breaks the module import

ref: https://github.com/robbrad/UKBinCollectionData/commit/4173300d7be7b655c4cb8fe21039eb4b49f407ea

Moving back to 
``` from uk_bin_collection.common import * ```

from recent commit

``` from uk_bin_collection.uk_bin_collection.common import * ```

Seams to work fine

Unit tests run with : poetry run coverage run -m pytest

and also work on VS Code with the venv set

![image](https://user-images.githubusercontent.com/6122503/183233496-e370fd93-6e8b-4351-81e7-983508ed7e12.png)

**Comment by robbrad** [comment]
@ncdimensionalstudios did changing the imports on the unittests work for you? 

I had to change them back to get them to work 

see: 
https://github.com/robbrad/UKBinCollectionData/actions/runs/2807630318

vs:
https://github.com/robbrad/UKBinCollectionData/actions/runs/2807548722

I have changed the merge strategy for the GH action now so this would be picked up before merge https://github.com/robbrad/UKBinCollectionData/commit/a38e9132b8631338da9f947b29a1dc7d7af4ffd8

And it will run nightly :)

**Comment by dp247** [comment]
Ah yeah, the sources root breaking the module import is my bad... I set the project source root up for him in the correct folder 😅
