### ISSUE TITLE
No Devices or Entities

### ISSUE THREAD

**Issue by milesbailey** [robbrad/UKBinCollectionData#942]
### Name of Council

West Northamptonshire Council

### Issue Information

When added, Service returns "No devices or entities".

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by m26dvd** [comment]
Can you supply any logs from home assistant?

**Comment by milesbailey** [comment]
HiShows no events in the logbook..?MSent from my iPhoneOn 31 Oct 2024, at 12:43, m26dvd ***@***.***> wrote:﻿
Can you supply any logs from home assistant?

**Comment by robbrad** [comment]
You should check your HA logs not the logbook

**Comment by robbrad** [comment]
@milesbailey any update?

**Comment by LFishwick** [comment]
I'm seeing something similar in setup for west northants council too. I've tried inputting the postcode in either XXXX XXX and XXXXXXX format into the options. This report is with XXXX XXX format




This error originated from a custom integration.

Logger: custom_components.uk_bin_collection
Source: custom_components/uk_bin_collection/__init__.py:250
integration: UK Bin Collection Data (documentation, issues)
First occurred: 16:28:08 (23 occurrences)
Last logged: 16:41:22

[UKBinCollection] Unexpected error: 'type'
Traceback (most recent call last):
  File "/config/custom_components/uk_bin_collection/__init__.py", line 250, in _async_update_data
    data = await asyncio.wait_for(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 101, in run
    return self.client_code(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 121, in client_code
    return get_bin_data_class.template_method(address_url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 61, in template_method
    bin_data_dict = self.get_and_parse_data(this_url, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 82, in get_and_parse_data
    bin_data_dict = self.parse_data(page, url=address_url, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/councils/WestNorthamptonshireCouncil.py", line 27, in parse_data
    "type": json_data["type"].capitalize(),
            ~~~~~~~~~^^^^^^^^
KeyError: 'type'

**Comment by m26dvd** [comment]
> I'm seeing something similar in setup for west northants council too. I've tried inputting the postcode in either XXXX XXX and XXXXXXX format into the options. This report is with XXXX XXX format
> 
> This error originated from a custom integration.
> 
> Logger: custom_components.uk_bin_collection Source: custom_components/uk_bin_collection/**init**.py:250 integration: UK Bin Collection Data (documentation, issues) First occurred: 16:28:08 (23 occurrences) Last logged: 16:41:22
> 
> [UKBinCollection] Unexpected error: 'type' Traceback (most recent call last): File "/config/custom_components/uk_bin_collection/**init**.py", line 250, in _async_update_data data = await asyncio.wait_for( ^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for return await fut ^^^^^^^^^ File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 101, in run return self.client_code( ^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/collect_data.py", line 121, in client_code return get_bin_data_class.template_method(address_url, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 61, in template_method bin_data_dict = self.get_and_parse_data(this_url, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/get_bin_data.py", line 82, in get_and_parse_data bin_data_dict = self.parse_data(page, url=address_url, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/uk_bin_collection/uk_bin_collection/councils/WestNorthamptonshireCouncil.py", line 27, in parse_data "type": json_data["type"].capitalize(), ~~~~~~~~~^^^^^^^^ KeyError: 'type'

I just tested adding West Northamptonshire with a test postcode of "NN3 2JB" and it works perfectly

**Comment by LFishwick** [comment]
Any idea why I'm getting this error message in my logs then? Which configuration step have I likely missed?

**Comment by dp247** [comment]
> Any idea why I'm getting this error message in my logs then? Which configuration step have I likely missed?

KeyErrors are usually because the dictionary is empty, i.e. no results are found. If you're willing to email me your postcode, I'll be able to take a further look (my email is on my GH profile)

**Comment by LFishwick** [comment]
So I tried the nn3 2jb postcode to see if it was an issue on my setup and that ran fine. The postcode I had been trying was NN11 3ug, or NN11 3QR but neither would work. Perhaps it's not scraping the Daventry area ones.

**Comment by m26dvd** [comment]
@LFishwick Thanks for providing an example postcode. I can see the issue now and have updated the code. This should now work after my next release.

The input will change from postcode to property UPRN which you can find by going to https://www.findmyaddress.co.uk/
