### ISSUE TITLE
Can't install on 2024.11.0b1

### ISSUE THREAD

**Issue by jackwilsdon** [robbrad/UKBinCollectionData#953]
### Home Assistant Version

2024.11.0b1

### Installation Method

Using HACS

### Issue Information

```
 ERROR (SyncWorker_3) [homeassistant.util.package] Unable to install package uk-bin-collection>=0.109.0: × No solution found when resolving dependencies:
  ╰─▶ Because pytest-homeassistant-custom-component==0.13.175 depends
      on pydantic==1.10.17 and pydantic==1.10.18, we can conclude that
      pytest-homeassistant-custom-component==0.13.175 cannot be used.
      And because uk-bin-collection==0.109.0 depends on
      pytest-homeassistant-custom-component==0.13.175, we can conclude that
      uk-bin-collection==0.109.0 cannot be used.
      And because only uk-bin-collection<=0.109.0 is available and you require
      uk-bin-collection>=0.109.0, we can conclude that your requirements are 
      unsatisfiable.
```

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] If trying to add a specific council, I've checked it is listed as working at https://robbrad.github.io/UKBinCollectionData/3.12/
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by robbrad** [comment]
Thanks @jackwilsdon 

I tested on home assistant 2024.10 and it was ok I guess 2024.11b is needed

I may look at alternatives to testing using the pytest-homeassistant as I'm having all sorts of issues with sockets.

Rollback to 107 for now

Rob

**Comment by jackwilsdon** [comment]
Is it possible to exclude test dependencies from the published PyPI package? I assume they're not needed at runtime?

**Comment by robbrad** [comment]
> Is it possible to exclude test dependencies from the published PyPI package? I assume they're not needed at runtime?

Yeh typo on my part. I'll move them over tonight
