### ISSUE TITLE
Cannot use !secret for Unique Property Reference Number

### ISSUE THREAD

**Issue by Stutchbury** [robbrad/UKBinCollectionData#960]
### Home Assistant Version

2024.10.4

### Installation Method

Using HACS

### Name of Council (if relevant)

n/a

### Issue Information

I would like to store my Unique Property Reference Number in the secrets.yaml file but when `!secret uprn` is entered in the UPRN configuration field, none of the entities are populated.

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] If trying to add a specific council, I've checked it is listed as working at https://robbrad.github.io/UKBinCollectionData/3.12/
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by robbrad** [comment]
@Stutchbury is it possible to do this in Home Assistant config flow?

**Comment by Stutchbury** [comment]
Doing a bit of digging, I found this https://community.home-assistant.io/t/how-to-use-secrets-yaml-in-addons/358504/2 so tried re-starting HA (as UKBCD is not an addon). That didn't work, but when I changed the UPRN back to text I didn't need a re-start for it to take effect.

**Comment by robbrad** [comment]
Hi @Stutchbury 

I can't find any information on using the !secret directive in the config flow ui of a home assistant custom components.

I did some other research too and found this.

Config Flows vs. YAML Configuration

Home Assistant offers two primary methods for configuring integrations:
	1.	YAML Configuration: Traditional method where configurations are written directly in YAML files.
	2.	Config Flows (UI-Based): Newer method that provides a user-friendly interface for setting up integrations through the Home Assistant UI.

Using Secrets in Config Flows

For a config flow in a custom component, it's typically guiding the user through a series of UI prompts to gather necessary information. Here’s how secrets are handled in this context:
	•	User Input Handling: During the config flow, when you prompt the user for sensitive information (e.g., passwords or API keys), Home Assistant ensures that these inputs are stored securely in its internal storage system, not directly in configuration.yaml.
	•	No Need for !secret: Since config flows handle the storage of sensitive information securely through the UI, there’s no need to use the !secret directive within the config flow itself. The !secret directive is specifically for YAML files and isn’t directly applicable within the Python code of config flows.

Does that make sense?

I'm not sure how we would implement this so my suggestion is if you are happy with the above, the we close the ticket.
