### ISSUE TITLE
Central Bedfordshire Council Request

### ISSUE THREAD

**Issue by prckmc** [robbrad/UKBinCollectionData#961]
### Name of Council

Central Bedfordshire

### Example Address/Postcode

LU7 9NQ

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by robbrad** [comment]
Already supported
