### ISSUE TITLE
Request for Antrim & Newtownabbey Borough Council

### ISSUE THREAD

**Issue by JonnyBytesMe** [robbrad/UKBinCollectionData#969]
### Name of Council

Antrim & Newtownabbey Borough Council

### Example Address/Postcode

BT42 3DD

### Additional Information

Link to the council bins & recycling page
https://antrimandnewtownabbey.gov.uk/bins/

Schedule for the relevant area
https://antrimandnewtownabbey.gov.uk/residents/bins-recycling/bins-schedule/?Id=643

Search function available here
https://antrimandnewtownabbey.gov.uk/residents/bins-recycling/bins-schedule/

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by njkingston** [comment]
Also looking for Antrim & Newtownabbey Borough Council to be added

Postcode = BT42 3PR

Schedule for the relevant area = https://antrimandnewtownabbey.gov.uk/residents/bins-recycling/bins-schedule/?Id=2253
