### ISSUE TITLE
Calendar error

### ISSUE THREAD

**Issue by yanikdude** [robbrad/UKBinCollectionData#970]
Hi team,

I have an error of "Could not retrieve events for calendars: calendar.bin_colleciotn_days"

I have removed the "UK Bin Collection Data" from HCAS and re-installed V0.112.0 but no fix. 

Also followed the correct steps to set-up the integration. 

https://app.newark-sherwooddc.gov.uk/bincollection/calendar?pid=200001877336

<img width="910" alt="Screenshot 2024-11-07 at 15 27 08" src="https://github.com/user-attachments/assets/62afbc7f-3bc0-4517-93a2-bd8a6a6253d4">

**Comment by robbrad** [comment]
How are you configuring your calendar? Or intergration doesnt have a calender type view.

Are you using this? https://github.com/mampfes/hacs_waste_collection_schedule

**Comment by yanikdude** [comment]
Hey Robert, when initially installed UKBinCollectionData, there were no issues and all the calendar items appeared. I suspect that my partner deleted the calendar for UKBinCollectionData and was hoping that removing it and re-adding the integration would correct this but sadly not. 

thank you for the support.

Yanik

**Comment by robbrad** [comment]
Interesting we never had calendar functionality until last night so I'm not sure how you got calendar access.

Can you update to the latest version and let me know?

**Comment by yanikdude** [comment]
hey Robert,

updated to the latest version. 0.115.0 and I can see some entires for bin collection days. 

I can only see Bin collection data up until 21st November for recycling, garden and Landfill and 23rd December for glass (it's only every collected very 8 weeks). 

huge thank you for your help. 

Yanik.

**Comment by yanikdude** [comment]
Hey Robert, 

Newark & Sherwood DC have published collection data from. 1st November 2024 - 31st October 2025.

https://app.newark-sherwooddc.gov.uk/bincollection/calendar?pid=200001877336 

Made sure I am using the latest link data and running the latest version. 0.116.0.

Yanik

**Comment by robbrad** [comment]
Thanks

The issue is this integration only gets the next collection, and only ever has.

If you want it to have more dates the integration for this council will need changes to get that information
