### ISSUE TITLE
Bins

### ISSUE THREAD

**Issue by cjp40** [robbrad/UKBinCollectionData#983]
### Name of Council

Luton Borough Council

### Example Address/Postcode

LU2 8TZ

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by m26dvd** [comment]
@cjp40 Luton Borough Council has already been added

https://github.com/robbrad/UKBinCollectionData/wiki/Councils#luton-borough-council

**Comment by dp247** [comment]
In that case, duplicate of #697
