### ISSUE TITLE
Add Warwick district council 

### ISSUE THREAD

**Issue by Crippsy999** [robbrad/UKBinCollectionData#985]
### Name of Council

Warwick District Council

### Example Address/Postcode

cv8 1el

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by m26dvd** [comment]
@Crippsy999 Warwick District Council has already been added

https://github.com/robbrad/UKBinCollectionData/wiki/Councils#warwick-district-council

**Comment by dp247** [comment]
I don't think we have an issue for that one. So no duplicate linking here 😂
