### ISSUE TITLE
Mid Suffolk District Council fails setup

### ISSUE THREAD

**Issue by SingingDwarf** [robbrad/UKBinCollectionData#994]
### Name of Council

Mid Suffolk District Council

### Issue Information

Complete the configuration details as required, including entering house number.

System fails to configure, after entering house number of '2' error is given: `Failed setup, will retry: Unexpected error: '2' is not in list`

Not sure how the system will correctly find the collection day with only entering a house number - surely the street address or postcode is also required?

Furthermore, Mid Suffolk and Babergh District Councils no longer appear to publish the day of the week collection on their website (they used to provide pdf files with all streets listed, confirming which day of the week applied to that particular street). Now they only appear to publish a calendar showing which week the recycling or general waste is collected, the householder is expected to know, (or email the council if they do not) which day of the week the collection takes place.

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by m26dvd** [comment]
@SingingDwarf As you have said, Mid Suffolk and Babergh District Councils do not seem to publish collection dates based on individual addresses and only provide a calendar with the householder expected to know which day of the week their collection is on.

Based on this, it wasn't possible to build a scraper that takes the address as input so it has been built to generate the dates on the calendar based on the day of the week that the collection is on.

As such, you should input the day of the week [Monday/Tuesday/Wednesday/Thursday/Friday] into the "House Number" field and it will auto-generate that list of collection dates

See the wiki here - https://github.com/robbrad/UKBinCollectionData/wiki/Councils#mid-suffolk-district-council

**Comment by SingingDwarf** [comment]
My bad - I didn't understand the instructions at first time of reading.
Many thanks for clarifying.

Does the integration take account of alterations to the collection day, e.g. due to a Bank Holiday?

**Comment by m26dvd** [comment]
> My bad - I didn't understand the instructions at first time of reading. Many thanks for clarifying.
> 
> Does the integration take account of alterations to the collection day, e.g. due to a Bank Holiday?

It should take into consideration any bank holiday offsets and feed that through yes.

It is only configured for the current provided calendar so it will need to be redone again when a new calendar is released towards the end of next year
