### ISSUE TITLE
Mid Suffolk District Council - Garden Waste

### ISSUE THREAD

**Issue by SingingDwarf** [robbrad/UKBinCollectionData#995]
### Name of Council

Mid Suffolk District Council

### Example Address/Postcode

IP6 8EJ

### Additional Information

Garden waste (brown bin) is collected on a bi-weekly (i.e. once every two weeks) cycle, with customers being on a Week 1 or Week 2 cycle.

The council helpfully(!) provides different PDF files showing the week of collection, depending upon whether the customer is on the Week 1 or 2 cycle.

[MSDC Check Your Garden Waste Collection Day](https://www.midsuffolk.gov.uk/w/check-your-collection-day#check-your-garden-waste-collection-day)

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by m26dvd** [comment]
This will be added in the next update pack.

It will require [Week 1/Week 2] to be added in the 'postcode' field to determine which week your garden collection is on.
