### ISSUE TITLE
Tendring District Council Request

### ISSUE THREAD

**Issue by Corneloues** [robbrad/UKBinCollectionData#996]
### Name of Council

Tendring District Council

### Example Address/Postcode

CO16 8AA

### Additional Information

It's a fortnightly cycle (red week, green week)

**Main Website:** https://www.tendringdc.gov.uk/services/rubbish-recycling

**Collection Day Checker (as guest):** https://tendring-self.achieveservice.com/en/service/Rubbish_and_recycling_collection_days

Form consists of a text entry box, for postcode and a dropdown box for address, which is populated once the postcode has been validated.

Results of an address check:

![image](https://github.com/user-attachments/assets/bf28dcde-3193-4677-a3f9-2dddc75b1e20)

This information could be scraped.

The download link on the results page is to a PDF.

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by dp247** [comment]
Already exists
https://github.com/robbrad/UKBinCollectionData/wiki/Councils#tendring-district-council
