### ISSUE TITLE
Please add Wealden

### ISSUE THREAD

**Issue by dmw62947** [robbrad/UKBinCollectionData#997]
### Name of Council

Wealden District Council

### Example Address/Postcode

TN221JA

### Additional Information

https://www.wealden.gov.uk/recycling-and-waste/bin-search/?uprn=100060136164

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by dp247** [comment]
Already exists
https://github.com/robbrad/UKBinCollectionData/wiki/Councils#wealden-district-council
