### ISSUE TITLE
Vale of White Horse District Council

### ISSUE THREAD

**Issue by cgddrd-gardin** [robbrad/UKBinCollectionData#999]
### Name of Council

Vale of White Horse District Council

### Example Address/Postcode

SN77WD

### Additional Information

https://www.whitehorsedc.gov.uk/vale-of-white-horse-district-council/recycling-rubbish-and-waste/when-is-your-collection-day/waste-collections-calendar/

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by dp247** [comment]
Already exists
https://github.com/robbrad/UKBinCollectionData/wiki/Councils#vale-of-white-horse-council

**Comment by cgddrd-gardin** [comment]
Doh! Sincere apologies for missing this!
